/*
 * Copyright (c) 2014 - present Adobe Systems Incorporated. All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

define({

    /**
     * Errors
     */

    // General file io error strings
    "GENERIC_ERROR"                     : "(erro {0})",
    "NOT_FOUND_ERR"                     : "Non se puido atopar o ficheiro ou cartafol.",
    "NOT_READABLE_ERR"                  : "Non se puido ler o ficheiro ou cartafol.",
    "EXCEEDS_MAX_FILE_SIZE"             : "Non é posíbel abrir no {APP_NAME} os ficheiros de máis de {0} MB.",
    "NO_MODIFICATION_ALLOWED_ERR"       : "Non é posíbel modificar o cartafol de destino.",
    "NO_MODIFICATION_ALLOWED_ERR_FILE"  : "Os permisos non permiten facer modificacións.",
    "CONTENTS_MODIFIED_ERR"             : "O ficheiro foi modificado fóra do {APP_NAME}.",
    "UNSUPPORTED_ENCODING_ERR"          : "Formato de codificación descoñecido",
    "ENCODE_FILE_FAILED_ERR"            : "{APP_NAME} non puido codificar o contido do ficheiro.",
    "DECODE_FILE_FAILED_ERR"            : "{APP_NAME} non puido descodificar o contido do ficheiro.",
    "UNSUPPORTED_ENCODING_ERR"          : "{APP_NAME} actualmente só soporta ficheiros codificados como UTF-8.",
    "FILE_EXISTS_ERR"                   : "O ficheiro xa existe.",
    "FILE"                              : "ficheiro",
    "FILE_TITLE"                        : "Ficheiro",
    "DIRECTORY"                         : "cartafol",
    "DIRECTORY_TITLE"                   : "Cartafol",
    "DIRECTORY_NAMES_LEDE"              : "nomes de cartafoles",
    "FILENAMES_LEDE"                    : "nomes de ficheiros",
    "FILENAME"                          : "Nome de ficheiro",
    "DIRECTORY_NAME"                    : "Nome de cartafol",

    // Project error strings
    "ERROR_LOADING_PROJECT"             : "Produciuse un erro ao abrir o proxecto",
    "OPEN_DIALOG_ERROR"                 : "Produciuse un erro ó amosar o diálogo de apertura de ficheiro. (error {0})",
    "REQUEST_NATIVE_FILE_SYSTEM_ERROR"  : "Produciuse un erro ó tentar abrir o cartafol <span class='dialog-filename'>{0}</span>. (erro {1})",
    "READ_DIRECTORY_ENTRIES_ERROR"      : "Produciuse un erro ó ler os contidos do cartafol <span class='dialog-filename'>{0}</span>. (erro {1})",

    // File open/save error string
    "ERROR_OPENING_FILE_TITLE"          : "Produciuse un erro ao abrir o ficheiro",
    "ERROR_OPENING_FILE"                : "Produciuse un erro ó tentar abrir o ficheiro <span class='dialog-filename'>{0}</span>. {1}",
    "ERROR_OPENING_FILES"               : "Produciuse un erro ó tentar abrir os seguintes ficheiros:",
    "ERROR_RELOADING_FILE_TITLE"        : "Produciuse un erro ao recargar os trocos dende disco",
    "ERROR_RELOADING_FILE"              : "Produciuse un erro ó tentar recargar o ficheiro <span class='dialog-filename'>{0}</span>. {1}",
    "ERROR_SAVING_FILE_TITLE"           : "Produciuse un erro ao gardar o ficheiro",
    "ERROR_SAVING_FILE"                 : "Produciuse un erro ó tentar gardar o ficheiro <span class='dialog-filename'>{0}</span>. {1}",
    "ERROR_RENAMING_FILE_TITLE"         : "Produciuse un erro ao renomear o ficheiro",
    "ERROR_RENAMING_FILE"               : "Produciuse un erro ó tentar renomear o ficheiro <span class='dialog-filename'>{0}</span>. {1}",
    "ERROR_RENAMING_NOT_IN_PROJECT"     : "O ficheiro ou o cartafol non pertence ao proxecto actualmente aberto. Só se poden renomear neste punto os ficheiros do proxecto.",
    "ERROR_MOVING_FILE_TITLE"           : "Produciuse un erro ao mover o ficheiro {0}",
    "ERROR_MOVING_FILE"                 : "Produciuse un erro ó tentar mover {2} <span class='dialog-filename'>{0}</span>. {1}",
    "ERROR_MOVING_NOT_IN_PROJECT"       : "Non é posíbel mover o ficheiro ou cartafol, xa que non pertence ao proxecto actual.",
    "ERROR_DELETING_FILE_TITLE"         : "Produciuse un erro ao eliminar o ficheiro",
    "ERROR_DELETING_FILE"               : "Produciuse un erro ó tentar eliminar o ficheiro <span class='dialog-filename'>{0}</span>. {1}",
    "INVALID_FILENAME_TITLE"            : "{0} non é válido",
    "INVALID_FILENAME_MESSAGE"          : "Os {0} non poden utilizar ningunha palabra reservada polo sistema, rematar con puntos (.) ou utilizar calquera dos seguintes caracteres: <code class='emphasized'>{1}</code>",
    "ENTRY_WITH_SAME_NAME_EXISTS"       : "Xa existe un ficheiro ou cartafol co nome <span class='dialog-filename'>{0}</span>.",
    "ERROR_CREATING_FILE_TITLE"         : "Produciuse un erro ao crear {0}",
    "ERROR_CREATING_FILE"               : "Produciuse un erro ó tentar crear o {0} <span class='dialog-filename'>{1}</span>. {2}",
    "ERROR_MIXED_DRAGDROP"              : "Non é posíbel abrir o cartafol ó mesmo tempo que hai abertos outros ficheiros.",

    // User key map error strings
    "ERROR_KEYMAP_TITLE"                : "Produciuse un erro ao ler os atallos de teclado",
    "ERROR_KEYMAP_CORRUPT"              : "O ficheiro de atallos de teclado non ten un formato JSON válido. O ficheiro abrirase para que poidas corrixir o formato.",
    "ERROR_LOADING_KEYMAP"              : "O ficheiro de atallos de teclado non está codificado como UTF-8 e non é posíbel cargalo.",
    "ERROR_RESTRICTED_COMMANDS"         : "Non podes asignar de novo os atallos de teclado aos seguintes comandos: {0}",
    "ERROR_RESTRICTED_SHORTCUTS"        : "Non podes asignar de novo os seguintes atallos de teclado: {0}",
    "ERROR_MULTIPLE_SHORTCUTS"          : "Estás a volver asignar múltiples atallos de teclado aos seguintes comandos: {0}",
    "ERROR_DUPLICATE_SHORTCUTS"         : "Hai múltiples aparicións dos seguintes atallos de teclado: {0}",
    "ERROR_INVALID_SHORTCUTS"           : "Os seguintes atallos de teclado non son válidos: {0}",
    "ERROR_NONEXISTENT_COMMANDS"        : "Estás a asignar atallos de teclado a comandos inexistentes: {0}",

    // Application preferences corrupt error strings
    "ERROR_PREFS_CORRUPT_TITLE"         : "Produciuse un erro ao ler os axustes",
    "ERROR_PREFS_CORRUPT"               : "O ficheiro de axustes non ten o formato JSON válido. O ficheiro abrirase para que poidas corrixir o formato. Despois terás de reiniciar {APP_NAME} para que os trocos teñan efecto.",
    "ERROR_PROJ_PREFS_CORRUPT"          : "O ficheiro de preferencias para o proxecto non ten o formato JSON válido. O ficheiro abrirase para que poidas corrixir o formato. Terás que cargar de novo o proxecto para que os trocos teñan efecto.",

    // Application error strings
    "ERROR_IN_BROWSER_TITLE"            : "Vaia... semella que {APP_NAME} aínda non funciona en navegadores.",
    "ERROR_IN_BROWSER"                  : "{APP_NAME} está desenvolvido en HTML, pero polo de agora funciona coma unha aplicación de escritorio para que poidas editar ficheiros en local. Por favor, utiliza a aplicación do repositorio <b>github.com/adobe/brackets-shell</b> para executar {APP_NAME}.",

    // ProjectManager max files error string
    "ERROR_MAX_FILES_TITLE"             : "Produciuse un erro ao indexar ficheiros",
    "ERROR_MAX_FILES"                   : "Este proxecto contén máis de 30.000 ficheiros. Funcións que operan sobre múltiples ficheiros poden estar desactivadas ou funcionar igual que se o proxecto estivese baleiro. <a href='https://github.com/adobe/brackets/wiki/Large-Projects'>Ler máis sobre como traballar con proxectos grandes</a>.",

    // Live Preview error strings
    "ERROR_LAUNCHING_BROWSER_TITLE"     : "Produciuse un erro ao iniciar o navegador",
    "ERROR_CANT_FIND_CHROME"            : "No se puido atopar o navegador Google Chrome. Por favor, asegúrate de que está instalado correctamente.",
    "ERROR_LAUNCHING_BROWSER"           : "Produciuse un erro ó iniciar o navegador. (erro {0})",

    "LIVE_DEVELOPMENT_ERROR_TITLE"      : "Produciuse un erro na Vista Previa ao Vivo",
    "LIVE_DEVELOPMENT_RELAUNCH_TITLE"   : "Conectando co navegador",
    "LIVE_DEVELOPMENT_ERROR_MESSAGE"    : "Para poder iniciar o modo de Vista Previa ao Vivo, Chrome tense que iniciar activando a depuración remota.<br /><br />Queres reiniciar Chrome e activar a depuración remota?",
    "LIVE_DEV_LOADING_ERROR_MESSAGE"    : "Non foi posíbel cargar a páxina para Vista Previa ao Vivo",
    "LIVE_DEV_NEED_HTML_MESSAGE"        : "Abre un ficheiro HTML ou asegúrate de que hai un index.html no teu proxecto para poder iniciar o modo de Vista Previa ao Vivo.",
    "LIVE_DEV_NEED_BASEURL_MESSAGE"     : "Tes que especificar un URL base neste proxecto para poder iniciar a Vista Previa ao Vivo con ficheiros do servidor.",
    "LIVE_DEV_SERVER_NOT_READY_MESSAGE" : "Erro iniciando o servidor HTTP para Vista Previa ao Vivo. Por favor, téntao de novo.",
    "LIVE_DEVELOPMENT_INFO_TITLE"       : "Benvido/a á Vista Previa ao Vivo!",
    "LIVE_DEVELOPMENT_INFO_MESSAGE"     : "Vista Previa ao Vivo conecta {APP_NAME} co teu navegador. Lanza unha vista previa do teu ficheiro HTML no navegador e actualízaa segundo modificas o teu código.<br /><br />Nesta versión preliminar de {APP_NAME}, o desenvolvemento ao vivo só funciona ao facer trocos en <strong>ficheiros CSS ou HTML</strong> e únicamente no <strong>Google Chrome</strong>. Os trocos nos ficheiros Javascript recárganse automaticamente ao se gardar.<br /><br />(Non volverás ver esta mensaxe.)",
    "LIVE_DEVELOPMENT_TROUBLESHOOTING"  : "Para máis información, consulta <a href='{0}' title='{0}'>Solución de Problemas de conexión na Vista Previa ao Vivo</a>.",

    "LIVE_DEV_STATUS_TIP_NOT_CONNECTED" : "Vista Previa ao Vivo",
    "LIVE_DEV_STATUS_TIP_PROGRESS1"     : "Vista Previa ao Vivo: Conectando\u2026",
    "LIVE_DEV_STATUS_TIP_PROGRESS2"     : "Vista Previa ao Vivo: Iniciando\u2026",
    "LIVE_DEV_STATUS_TIP_CONNECTED"     : "Rematar Vista Previa ao Vivo",
    "LIVE_DEV_STATUS_TIP_OUT_OF_SYNC"   : "Vista Previa ao Vivo (garda o ficheiro para actualizar)",
    "LIVE_DEV_STATUS_TIP_SYNC_ERROR"    : "Vista Previa ao Vivo (non é posíbel debido a un erro de sintaxe)",

    "LIVE_DEV_DETACHED_REPLACED_WITH_DEVTOOLS" : "Vista Previa ao Vivo detívose ao abrirse as ferramentas de desenvolvemento",
    "LIVE_DEV_DETACHED_TARGET_CLOSED"          : "Vista Previa ao Vivo detívose ao pecharse a páxina no navegador",
    "LIVE_DEV_NAVIGATED_AWAY"                  : "Vista Previa ao Vivo detívose ao acceder a unha páxina que non é parte do proxecto actual",
    "LIVE_DEV_CLOSED_UNKNOWN_REASON"           : "Vista Previa ao Vivo detívose por motivos descoñecidos ({0})",

    "SAVE_CLOSE_TITLE"                  : "Gardar trocos",
    "SAVE_CLOSE_MESSAGE"                : "Queres gardar os trocos existentes no documento <span class='dialog-filename'>{0}</span>?",
    "SAVE_CLOSE_MULTI_MESSAGE"          : "Queres gardar os teus trocos nos seguintes documentos?",
    "EXT_MODIFIED_TITLE"                : "Trocos externos",
    "CONFIRM_DELETE_TITLE"              : "Confirmar eliminación",
    "CONFIRM_FILE_DELETE"               : "Tes a certeza de querer eliminar o ficheiro <span class='dialog-filename'>{0}</span>?",
    "CONFIRM_FOLDER_DELETE"             : "Tes a certeza de querer eliminar o cartafol <span class='dialog-filename'>{0}</span>?",
    "FILE_DELETED_TITLE"                : "Ficheiro eliminado",
    "EXT_MODIFIED_WARNING"              : "<span class='dialog-filename'>{0}</span> foi modificado no disco.<br /><br />Queres gardar o ficheiro e sobrescribir eses trocos?",
    "EXT_MODIFIED_MESSAGE"              : "<span class='dialog-filename'>{0}</span> foi modificado, pero tamén ten trocos no {APP_NAME}.<br /><br />Que versión queres conservar?",
    "EXT_DELETED_MESSAGE"               : "<span class='dialog-filename'>{0}</span> foi eliminado, pero ten trocos sen gardar no {APP_NAME}.<br /><br />Queres conservar os teus trocos?",
    
    // Window unload warning messages
    "WINDOW_UNLOAD_WARNING"                      : "Tes a certeza de querer saír do Brackets e navegar a un URL diferente?",
    "WINDOW_UNLOAD_WARNING_WITH_UNSAVED_CHANGES" : "Hai trocos sen gardar! Tes a certeza de querer saír do Brackets e navegar a un URL diferente?",

    // Generic dialog/button labels
    "DONE"                              : "Aceptar",
    "OK"                                : "Aceptar",
    "CANCEL"                            : "Cancelar",
    "DONT_SAVE"                         : "Non gardar",
    "SAVE"                              : "Gardar",
    "SAVE_AS"                           : "Gardar como\u2026",
    "SAVE_AND_OVERWRITE"                : "Sobrescribir",
    "DELETE"                            : "Eliminar",
    "BUTTON_YES"                        : "Si",
    "BUTTON_NO"                         : "Non",

    // Find, Replace, Find in Files
    "FIND_MATCH_INDEX"                  : "{0} de {1}",
    "FIND_NO_RESULTS"                   : "Sen resultados",
    "FIND_QUERY_PLACEHOLDER"            : "Atopado\u2026",
    "FIND_HISTORY_MAX_COUNT"            : "Número máximo de elementos no historial de buscas",
    "REPLACE_PLACEHOLDER"               : "Substituír por\u2026",
    "BUTTON_REPLACE_ALL"                : "Substituír todo",
    "BUTTON_REPLACE_ALL"                : "Todo\u2026",
    "BUTTON_REPLACE_ALL_IN_FILES"       : "Substituír\u2026",
    "BUTTON_REPLACE"                    : "Substituír",
    "BUTTON_NEXT"                       : "\u25B6",
    "BUTTON_PREV"                       : "\u25C0",
    "BUTTON_NEXT_HINT"                  : "Seguinte coincidencia",
    "BUTTON_PREV_HINT"                  : "Anterior coincidencia",
    "BUTTON_CASESENSITIVE_HINT"         : "Sensíbel ás maiúsculas",
    "BUTTON_REGEXP_HINT"                : "Expresión regular",
    "REPLACE_WITHOUT_UNDO_WARNING_TITLE": "Substituír sen volta atrás",
    "REPLACE_WITHOUT_UNDO_WARNING"      : "Debido a que máis de {0} ficheiros precisan ser cambiados, {APP_NAME} modificará ficheiros non abertos.<br />Non poderás desfacer estes cambios.",
    "BUTTON_REPLACE_WITHOUT_UNDO"       : "Substituír sen volta atrás",

    "OPEN_FILE"                         : "Abrir ficheiro",
    "SAVE_FILE_AS"                      : "Gardar ficheiro",
    "CHOOSE_FOLDER"                     : "Selecciona un cartafol",

    "RELEASE_NOTES"                     : "Notas sobre a versión",
    "NO_UPDATE_TITLE"                   : "Brackets está actualizado!",
    "NO_UPDATE_MESSAGE"                 : "Está instalada a última versión do {APP_NAME}.",

    // Find and Replace
    "FIND_REPLACE_TITLE_LABEL"          : "Substituír",
    "FIND_REPLACE_TITLE_WITH"           : "por",
    "FIND_TITLE_LABEL"                  : "Atopado",
    "FIND_TITLE_SUMMARY"                : "&mdash; {0} {1} {2} en {3}",

    // Find in Files
    "FIND_NUM_FILES"                    : "{0} {1}",
    "FIND_IN_FILES_SCOPED"              : "no <span class='dialog-filename'>{0}</span>",
    "FIND_IN_FILES_NO_SCOPE"            : "no proxecto",
    "FIND_IN_FILES_ZERO_FILES"          : "O filtro exclúe tódolos ficheiros {0}",
    "FIND_IN_FILES_FILE"                : "ficheiro",
    "FIND_IN_FILES_FILES"               : "ficheiros",
    "FIND_IN_FILES_MATCH"               : "coincidencia",
    "FIND_IN_FILES_MATCHES"             : "coincidencias",
    "FIND_IN_FILES_MORE_THAN"           : "Máis de ",
    "FIND_IN_FILES_PAGING"              : "{0}&mdash;{1}",
    "FIND_IN_FILES_FILE_PATH"           : "<span class='dialog-filename'>{0}</span> {2} <span class='dialog-path'>{1}</span>",  // We should use normal dashes on Windows instead of em dash eventually
    "FIND_IN_FILES_EXPAND_COLLAPSE"     : "Ctrl/Cmd clic para expandir/contraer todo",
    "FIND_IN_FILES_INDEXING"            : "Indexando para busca instantánea\u2026",
    "REPLACE_IN_FILES_ERRORS_TITLE"     : "Substituír Erros",
    "REPLACE_IN_FILES_ERRORS"           : "Os seguintes ficheiros non se modificaron ao se mudar despois da busca ou non poden ser modificados.",

    "ERROR_FETCHING_UPDATE_INFO_TITLE"  : "Produciuse un erro ao obter información sobre actualizacións",
    "ERROR_FETCHING_UPDATE_INFO_MSG"    : "Houbo un problema ó obter a información sobre as últimas actualizacións dende o servidor. Por favor, asegúrate de estar conectado a internet e téntao de novo.",

    // File exclusion filters
    "NEW_FILE_FILTER"                   : "Novo conxunto de filtros\u2026",
    "CLEAR_FILE_FILTER"                 : "Non excluír ficheiros",
    "NO_FILE_FILTER"                    : "Sen ficheiros excluídos",
    "EXCLUDE_FILE_FILTER"               : "Excluír {0}",
    "EDIT_FILE_FILTER"                  : "Editar\u2026",
    "FILE_FILTER_DIALOG"                : "Editar conxunto de filtros",
    "FILE_FILTER_INSTRUCTIONS"          : "Excluír ficheiros e cartafoles que coincidan con algunha das seguintes cadeas / subcadeas ou <a href='{0}' title='{0}'>comodíns</a>. Escribe unha cadea por liña.",
    "FILTER_NAME_PLACEHOLDER"           : "Nomear este conxunto de filtros (opcional)",
    "FILTER_NAME_REMAINING"             : "Faltan {0} caracteres",
    "FILE_FILTER_CLIPPED_SUFFIX"        : "e {0} máis",
    "FILTER_COUNTING_FILES"             : "Contando ficheiros\u2026",
    "FILTER_FILE_COUNT"                 : "Permite {0} de {1} ficheiros {2}",
    "FILTER_FILE_COUNT_ALL"             : "Permite tódolos {0} ficheiros {1}",

    // Quick Edit
    "ERROR_QUICK_EDIT_PROVIDER_NOT_FOUND"   : "A Edición Rápida non está dispoñíbel para a posición actual do cursor",
    "ERROR_CSSQUICKEDIT_BETWEENCLASSES"     : "Edición Rápida para CSS: coloca o cursor sobre o nome dunha clase",
    "ERROR_CSSQUICKEDIT_CLASSNOTFOUND"      : "Edición Rápida para CSS: atributo de clase incompleto",
    "ERROR_CSSQUICKEDIT_IDNOTFOUND"         : "Edición Rápida para CSS: atributo de identificación incompleto",
    "ERROR_CSSQUICKEDIT_UNSUPPORTEDATTR"    : "Edición Rápida para CSS: coloca o cursor sobre unha etiqueta, clase ou id",
    "ERROR_TIMINGQUICKEDIT_INVALIDSYNTAX"   : "Edición Rápida para Funcións de Temporización de CSS: sintaxe non válida",
    "ERROR_JSQUICKEDIT_FUNCTIONNOTFOUND"    : "Edición Rápida para JS: coloca o cursor sobre o nome dunha función",

    // Quick Docs
    "ERROR_QUICK_DOCS_PROVIDER_NOT_FOUND"   : "A Documentación Rápida non está dispoñíbel para a posición actual do cursor",

    /**
     * ProjectManager
     */
    "PROJECT_LOADING"   : "Cargando\u2026",
    "UNTITLED"          : "Sen título",
    "WORKING_FILES"     : "Área de traballo",

    /**
     * MainViewManager
     */
    "TOP"               : "Arriba",
    "BOTTOM"            : "Abaixo",
    "LEFT"              : "Esquerda",
    "RIGHT"             : "Dereita",

    "CMD_SPLITVIEW_NONE"        : "Non Dividir",
    "CMD_SPLITVIEW_VERTICAL"    : "División Vertical",
    "CMD_SPLITVIEW_HORIZONTAL"  : "División Horizontal",
    "SPLITVIEW_MENU_TOOLTIP"    : "Dividir o editor vertical ou horizontalmente",
    "GEAR_MENU_TOOLTIP"         : "Configurar espazo de traballo",

    "SPLITVIEW_INFO_TITLE"              : "Xa está aberto",
    "SPLITVIEW_MULTIPANE_WARNING"       : "O ficheiro xa está aberto noutro panel. {APP_NAME} pronto soportará abrir o mesmo ficheiro noutro panel. Até entón, o ficheiro amosarase no panel que xa está aberto en.<br /><br />(Só verás esta mensaxe unha vez.)",

    /**
     * Keyboard modifiers and special key names
     */
    "KEYBOARD_CTRL"         : "Ctrl",
    "KEYBOARD_SHIFT"        : "Mai",
    "KEYBOARD_SPACE"        : "Espazo",
    "KEYBOARD_PAGE_UP"      : "Retroceso",
    "KEYBOARD_PAGE_DOWN"    : "Avance",
    "KEYBOARD_HOME"         : "Inicio",
    "KEYBOARD_END"          : "Fin",
    "KEYBOARD_INSERT"       : "Inserir",
    "KEYBOARD_DELETE"       : "Eliminar",

    /**
     * StatusBar strings
     */
    "STATUSBAR_CURSOR_POSITION"             : "Liña {0}, Columna {1}",
    "STATUSBAR_SELECTION_CH_SINGULAR"       : " \u2014 {0} columna seleccionada",
    "STATUSBAR_SELECTION_CH_PLURAL"         : " \u2014 {0} columnas seleccionadas",
    "STATUSBAR_SELECTION_LINE_SINGULAR"     : " \u2014 {0} liña seleccionada",
    "STATUSBAR_SELECTION_LINE_PLURAL"       : " \u2014 {0} liñas seleccionadas",
    "STATUSBAR_SELECTION_MULTIPLE"          : " \u2014 {0} seleccións",
    "STATUSBAR_INDENT_TOOLTIP_SPACES"       : "Fai clic para usar espazos na sangría",
    "STATUSBAR_INDENT_TOOLTIP_TABS"         : "Fai clic para usar tabulacións na sangría",
    "STATUSBAR_INDENT_SIZE_TOOLTIP_SPACES"  : "Fai clic para trocar o número de espazos usados na sangría",
    "STATUSBAR_INDENT_SIZE_TOOLTIP_TABS"    : "Fai clic para trocar o largo das tabulacións",
    "STATUSBAR_SPACES"                      : "Espazos:",
    "STATUSBAR_TAB_SIZE"                    : "Tamaño do tabulador:",
    "STATUSBAR_LINE_COUNT_SINGULAR"         : "\u2014 {0} liña",
    "STATUSBAR_LINE_COUNT_PLURAL"           : "\u2014 {0} liñas",
    "STATUSBAR_USER_EXTENSIONS_DISABLED"    : "Extensións desactivadas",
    "STATUSBAR_INSERT"                      : "INS",
    "STATUSBAR_OVERWRITE"                   : "SOB",
    "STATUSBAR_INSOVR_TOOLTIP"              : "Fai clic para trocar entre o modo inserir (INS) e o modo sobrescribir (SOB)",
    "STATUSBAR_LANG_TOOLTIP"                : "Fai clic para trocar o tipo de ficheiro",
    "STATUSBAR_CODE_INSPECTION_TOOLTIP"     : "{0}. Fai clic para amosar/ocultar o panel de informes.",
    "STATUSBAR_DEFAULT_LANG"                : "(predefinido)",
    "STATUSBAR_SET_DEFAULT_LANG"            : "Marcar como predefinido para os ficheiros .{0}",
    "STATUSBAR_ENCODING_TOOLTIP"            : "Seleccionar a codificación",

    // CodeInspection: errors/warnings
    "ERRORS_PANEL_TITLE_MULTIPLE"           : "Problemas de {0}",
    "SINGLE_ERROR"                          : "1 problema de {0}",
    "MULTIPLE_ERRORS"                       : "{1} problemas de {0}",
    "NO_ERRORS"                             : "Non se atoparon problemas de {0} - Bo traballo!",
    "NO_ERRORS_MULTIPLE_PROVIDER"           : "Non se atoparon problemas - Bo traballo!",
    "LINT_DISABLED"                         : "A inspección de código está desactivada",
    "NO_LINT_AVAILABLE"                     : "Non hai inspección de código dispoñible para {0}",
    "NOTHING_TO_LINT"                       : "Non hai nada para inspeccionar",
    "LINTER_TIMED_OUT"                      : "{0} esgotou o tempo despois de agardar {1} ms",
    "LINTER_FAILED"                         : "{0} rematou con erro: {1}",

    /**
     * Command Name Constants
     */

    // File menu commands
    "FILE_MENU"                           : "Ficheiro",
    "CMD_FILE_NEW_UNTITLED"               : "Novo",
    "CMD_FILE_NEW"                        : "Novo ficheiro",
    "CMD_FILE_NEW_FOLDER"                 : "Novo cartafol",
    "CMD_FILE_OPEN"                       : "Abrir\u2026",
    "CMD_RECENT_FILES_OPEN"               : "Abrir recentes\u2026",
    "CMD_ADD_TO_WORKING_SET"              : "Engadir ao espazo de traballo",
    "CMD_OPEN_DROPPED_FILES"              : "Abrir ficheiros eliminados",
    "CMD_OPEN_FOLDER"                     : "Abrir cartafol\u2026",
    "CMD_FILE_CLOSE"                      : "Pechar",
    "CMD_FILE_CLOSE_ALL"                  : "Pechar todo",
    "CMD_FILE_CLOSE_LIST"                 : "Pechar listaxe",
    "CMD_FILE_CLOSE_OTHERS"               : "Pechar outros",
    "CMD_FILE_CLOSE_ABOVE"                : "Pechar outros por enriba",
    "CMD_FILE_CLOSE_BELOW"                : "Pechar outros por debaixo",
    "CMD_FILE_SAVE"                       : "Gardar",
    "CMD_FILE_SAVE_ALL"                   : "Gardar todo",
    "CMD_FILE_SAVE_AS"                    : "Gardar como\u2026",
    "CMD_LIVE_FILE_PREVIEW"               : "Vista Previa ao Vivo",
    "CMD_TOGGLE_LIVE_PREVIEW_MB_MODE"     : "Activar a Vista Previa ao Vivo",
    "CMD_RELOAD_LIVE_PREVIEW"             : "Forzar Recargar a Vista Previa ao Vivo",
    "CMD_PROJECT_SETTINGS"                : "Configuración do proxecto\u2026",
    "CMD_FILE_RENAME"                     : "Renomear",
    "CMD_FILE_DELETE"                     : "Eliminar",
    "CMD_INSTALL_EXTENSION"               : "Instalar extensión\u2026",
    "CMD_EXTENSION_MANAGER"               : "Xestionar extensións\u2026",
    "CMD_FILE_REFRESH"                    : "Actualizar árbore de ficheiros",
    "CMD_QUIT"                            : "Saír",
    // Used in native File menu on Windows
    "CMD_EXIT"                            : "Saír",

    // Edit menu commands
    "EDIT_MENU"                           : "Edición",
    "CMD_UNDO"                            : "Desfacer",
    "CMD_REDO"                            : "Refacer",
    "CMD_CUT"                             : "Cortar",
    "CMD_COPY"                            : "Copiar",
    "CMD_PASTE"                           : "Pegar",
    "CMD_SELECT_ALL"                      : "Seleccionar todo",
    "CMD_SELECT_LINE"                     : "Seleccionar liña",
    "CMD_SPLIT_SEL_INTO_LINES"            : "Dividir selección en liñas",
    "CMD_ADD_CUR_TO_NEXT_LINE"            : "Engadir cursor á seguinte liña",
    "CMD_ADD_CUR_TO_PREV_LINE"            : "Engadir cursor á liña anterior",
    "CMD_INDENT"                          : "Aumentar sangría",
    "CMD_UNINDENT"                        : "Diminuír sangría",
    "CMD_DUPLICATE"                       : "Duplicar",
    "CMD_DELETE_LINES"                    : "Eliminar liña",
    "CMD_COMMENT"                         : "Comentar/Descomentar liña",
    "CMD_BLOCK_COMMENT"                   : "Comentar/Descomentar bloque",
    "CMD_LINE_UP"                         : "Subir liña",
    "CMD_LINE_DOWN"                       : "Baixar liña",
    "CMD_OPEN_LINE_ABOVE"                 : "Crear liña arriba",
    "CMD_OPEN_LINE_BELOW"                 : "Crear liña abaixo",
    "CMD_TOGGLE_CLOSE_BRACKETS"           : "Completar parénteses automaticamente",
    "CMD_SHOW_CODE_HINTS"                 : "Amosar suxestións de código",

    // Search menu commands
    "FIND_MENU"                           : "Buscar",
    "CMD_FIND"                            : "Buscar",
    "CMD_FIND_NEXT"                       : "Buscar seguinte",
    "CMD_FIND_PREVIOUS"                   : "Buscar anterior",
    "CMD_FIND_ALL_AND_SELECT"             : "Buscar todo e seleccionar",
    "CMD_ADD_NEXT_MATCH"                  : "Engadir a seguinte coincidencia á selección",
    "CMD_SKIP_CURRENT_MATCH"              : "Omitir e engadir a seguinte coincidencia",
    "CMD_FIND_IN_FILES"                   : "Buscar en ficheiros",
    "CMD_FIND_IN_SUBTREE"                 : "Buscar en\u2026",
    "CMD_REPLACE"                         : "Substituír",
    "CMD_REPLACE_IN_FILES"                : "Substituír en ficheiros",
    "CMD_REPLACE_IN_SUBTREE"              : "Substituír en\u2026",

    // View menu commands
    "VIEW_MENU"                           : "Ver",
    "CMD_HIDE_SIDEBAR"                    : "Ocultar menú lateral",
    "CMD_SHOW_SIDEBAR"                    : "Amosar menú lateral",
    "CMD_TOGGLE_SIDEBAR"                  : "Alternar menú lateral",
    "CMD_TOGGLE_PANELS"                   : "Alternar paneis",
    "CMD_TOGGLE_PURE_CODE"                : "Sen distraccións",
    "CMD_INCREASE_FONT_SIZE"              : "Aumentar tamaño da fonte",
    "CMD_DECREASE_FONT_SIZE"              : "Diminuír tamaño da fonte",
    "CMD_RESTORE_FONT_SIZE"               : "Restabelecer tamaño da fonte",
    "CMD_SCROLL_LINE_UP"                  : "Desprazar cara arriba",
    "CMD_SCROLL_LINE_DOWN"                : "Desprazar cara abaixo",
    "CMD_TOGGLE_LINE_NUMBERS"             : "Amosar números de liña",
    "CMD_TOGGLE_ACTIVE_LINE"              : "Resaltar liña actual",
    "CMD_TOGGLE_WORD_WRAP"                : "Activar axuste de liña",
    "CMD_LIVE_HIGHLIGHT"                  : "Resaltado en Vista Previa ao Vivo",
    "CMD_VIEW_TOGGLE_INSPECTION"          : "Inspeccionar o código ó gardar",
    "CMD_WORKINGSET_SORT_BY_ADDED"        : "Ordenar por Engadido",
    "CMD_WORKINGSET_SORT_BY_NAME"         : "Ordenar por Nome",
    "CMD_WORKINGSET_SORT_BY_TYPE"         : "Ordenar por Tipo",
    "CMD_WORKING_SORT_TOGGLE_AUTO"        : "Ordenación automática",
    "CMD_THEMES"                          : "Temas\u2026",
    "CMD_TOGGLE_SEARCH_AUTOHIDE"          : "Pechar automaticamente Buscar",

    // Navigate menu Commands
    "NAVIGATE_MENU"                       : "Navegación",
    "CMD_QUICK_OPEN"                      : "Apertura rápida",
    "CMD_GOTO_LINE"                       : "Ir á liña",
    "CMD_GOTO_DEFINITION"                 : "Busca rápida de definición",
    "CMD_GOTO_FIRST_PROBLEM"              : "Ir ó primeiro Erro/Advertencia",
    "CMD_TOGGLE_QUICK_EDIT"               : "Edición rápida",
    "CMD_TOGGLE_QUICK_DOCS"               : "Documentación rápida",
    "CMD_QUICK_EDIT_PREV_MATCH"           : "Coincidencia anterior",
    "CMD_QUICK_EDIT_NEXT_MATCH"           : "Coincidencia seguinte",
    "CMD_CSS_QUICK_EDIT_NEW_RULE"         : "Nova norma",
    "CMD_NEXT_DOC"                        : "Documento seguinte",
    "CMD_PREV_DOC"                        : "Documento anterior",
    "CMD_NAVIGATE_BACKWARD"               : "Ir cara atrás",
    "CMD_NAVIGATE_FORWARD"                : "Ir cara adiante",
    "CMD_NEXT_DOC_LIST_ORDER"             : "Documento seguinte na listaxe",
    "CMD_PREV_DOC_LIST_ORDER"             : "Documento anterior na listaxe",
    "CMD_SHOW_IN_TREE"                    : "Amosar na árbore de cartafoles",
    "CMD_SHOW_IN_EXPLORER"                : "Amosar no Explorador",
    "CMD_SHOW_IN_FINDER"                  : "Amosar no Finder",
    "CMD_SHOW_IN_OS"                      : "Amosar no Sistema Operativo",
    "CMD_SWITCH_PANE_FOCUS"               : "Mudar o foco do panel",

    // Help menu commands
    "HELP_MENU"                           : "Axuda",
    "CMD_CHECK_FOR_UPDATE"                : "Buscar actualizacións",
    "CMD_HOW_TO_USE_BRACKETS"             : "Como empregar {APP_NAME}",
    "CMD_SUPPORT"                         : "Soporte de {APP_NAME}",
    "CMD_SUGGEST"                         : "Suxerir unha mellora",
    "CMD_RELEASE_NOTES"                   : "Notas da versión",
    "CMD_GET_INVOLVED"                    : "Involúcrate",
    "CMD_SHOW_EXTENSIONS_FOLDER"          : "Abrir cartafol de extensións",
    "CMD_HEALTH_DATA_STATISTICS"          : "Informe de estadísticas",
    "CMD_HOMEPAGE"                        : "Páxina principal do {APP_TITLE}",
    "CMD_TWITTER"                         : "{TWITTER_NAME} no Twitter",
    "CMD_ABOUT"                           : "Sobre o {APP_TITLE}",
    "CMD_OPEN_PREFERENCES"                : "Abrir ficheiro de axustes",
    "CMD_OPEN_KEYMAP"                     : "Abrir ficheiro de atallos de teclado",

    // Strings for main-view.html
    "EXPERIMENTAL_BUILD"                   : "versión experimental",
    "RELEASE_BUILD"                        : "versión",
    "DEVELOPMENT_BUILD"                    : "versión de desenvolvemento",
    "PRERELEASE_BUILD"                     : "versión previa á final",
    "RELOAD_FROM_DISK"                     : "Volver cargar dende disco",
    "KEEP_CHANGES_IN_EDITOR"               : "Conservar os trocos do editor",
    "CLOSE_DONT_SAVE"                      : "Pechar (Non gardar)",
    "RELAUNCH_CHROME"                      : "Reiniciar Chrome",
    "ABOUT"                                : "Sobre\u2026",
    "CLOSE"                                : "Pechar",
    "ABOUT_TEXT_LINE1"                     : "Versión {VERSION_MAJOR}.{VERSION_MINOR} {BUILD_TYPE} {VERSION}",
    "ABOUT_TEXT_BUILD_TIMESTAMP"           : "data da compilación: ",
    "ABOUT_TEXT_LINE3"                     : "Os avisos, termos e condicións pertencentes a software de terceiros atópanse en <a href='{ADOBE_THIRD_PARTY}'>{ADOBE_THIRD_PARTY}</a> e inclúense aquí como referencia.",
    "ABOUT_TEXT_LINE4"                     : "Podes atopar a documentación e código fonte en <a href='https://github.com/adobe/brackets/'>https://github.com/adobe/brackets/</a>",
    "ABOUT_TEXT_LINE5"                     : "Feito con \u2764 e JavaScript por:",
    "ABOUT_TEXT_LINE6"                     : "Moita xente (pero agora mesmo temos problemas para cargar eses datos).",
    "ABOUT_TEXT_MDN_DOCS"                  : "O contido de MDN Docs e o logo de MDN están dispoñíbeis baixo unha Licencia de Recoñecemento de Creative Commons, <a href='{MDN_DOCS_LICENSE}'>CC-BY-SA 2.5 Unported</a>.",
    "UPDATE_NOTIFICATION_TOOLTIP"          : "Hai unha nova versión do {APP_NAME} dispoñible! Fai clic aquí para máis detalles.",
    "UPDATE_AVAILABLE_TITLE"               : "Actualización dispoñíbel",
    "UPDATE_MESSAGE"                       : "Hai dispoñíbel unha nova versión do {APP_NAME}! Estas son algunhas das novas características:",
    "GET_IT_NOW"                           : "Conségueo agora!",
    "PROJECT_SETTINGS_TITLE"               : "Configuración do proxecto para: {0}",
    "PROJECT_SETTING_BASE_URL"             : "URL base para Vista Previa ao Vivo",
    "PROJECT_SETTING_BASE_URL_HINT"        : "(deixar baleiro para urls de tipo \"file\")",
    "BASEURL_ERROR_INVALID_PROTOCOL"       : "Vista Previa ao Vivo non soporta o protocolo {0}. Por favor, utiliza http: ou https: .",
    "BASEURL_ERROR_SEARCH_DISALLOWED"      : "O URL base non pode conter parámetros de busca como \"{0}\".",
    "BASEURL_ERROR_HASH_DISALLOWED"        : "A URL base non pode conter hashes como \"{0}\".",
    "BASEURL_ERROR_INVALID_CHAR"           : "Os caracteres especiais como '{0}' deben codificarse en formato %.",
    "BASEURL_ERROR_UNKNOWN_ERROR"          : "Erro descoñecido analizando o URL base",

    // Strings for Pane.js
    "EMPTY_VIEW_HEADER"                    : "<em>Selecciona un ficheiro mentres esta vista está activa</em>",
    "FLIPVIEW_BTN_TOOLTIP"                 : "Inverter esta vista no panel {0}",

    // Strings for themes-settings.html and themes-general.html
    "CURRENT_THEME"                        : "Tema actual",
    "USE_THEME_SCROLLBARS"                 : "Usar barras de desprazamento do tema",
    "FONT_SIZE"                            : "Tamaño da fonte",
    "FONT_FAMILY"                          : "Tipo de fonte",
    "THEMES_SETTINGS"                      : "Preferencias dos temas",

    // CSS Quick Edit
    "BUTTON_NEW_RULE"                      : "Nova regra",

    // Extension Management strings
    "INSTALL"                              : "Instalar",
    "UPDATE"                               : "Actualizar",
    "REMOVE"                               : "Eliminar",
    "DISABLE"                              : "Desactivar",
    "ENABLE"                               : "Activar",
    "OVERWRITE"                            : "Sobrescribir",
    "CANT_REMOVE_DEV"                      : "As extensións no cartafol \"dev\" débense eliminar manualmente.",
    "CANT_UPDATE"                          : "A actualización non é compatíbel con esta versión do {APP_NAME}.",
    "CANT_UPDATE_DEV"                      : "As extensións no cartafol \"dev\" non se poden actualizar automaticamente.",
    "INSTALL_EXTENSION_TITLE"              : "Instalar extensión",
    "UPDATE_EXTENSION_TITLE"               : "Actualizar extensión",
    "INSTALL_EXTENSION_LABEL"              : "URL da extensión",
    "INSTALL_EXTENSION_HINT"               : "URL do ficheiro ZIP da extensión ou do repositorio de Github",
    "INSTALLING_FROM"                      : "Instalando extensión dende {0}\u2026",
    "INSTALL_SUCCEEDED"                    : "Instalación completada!",
    "INSTALL_FAILED"                       : "Erro na instalación.",
    "CANCELING_INSTALL"                    : "Cancelando\u2026",
    "CANCELING_HUNG"                       : "Cancelouse a instalación por tardar de máis. Pode que se producira un erro interno.",
    "INSTALL_CANCELED"                     : "Instalación cancelada.",
    "VIEW_COMPLETE_DESCRIPTION"            : "Ver descrición completa",
    "VIEW_TRUNCATED_DESCRIPTION"           : "Ver descrición curta",
    "SORT_EXTENSION_METHOD"                : "Ordenar extensións empregando downloadCount ou publishedDate",
    // These must match the error codes in ExtensionsDomain.Errors.* :
    "INVALID_ZIP_FILE"                     : "O contido descargado non é un ficheiro zip válido.",
    "MISSING_PACKAGE_JSON"                 : "O paquete non contén o ficheiro package.json.",
    "INVALID_PACKAGE_JSON"                 : "O ficheiro package.json non é válido (error: {0}).",
    "MISSING_PACKAGE_NAME"                 : "O ficheiro package.json non especifica un nome de paquete.",
    "BAD_PACKAGE_NAME"                     : "{0} non é un nome de paquete válido.",
    "MISSING_PACKAGE_VERSION"              : "O ficheiro package.json non especifica a versión do paquete.",
    "INVALID_VERSION_NUMBER"               : "O número de paquete da versión ({0}) non é válido.",
    "INVALID_BRACKETS_VERSION"             : "O código de compatibilidade do {APP_NAME} {{0}} non é válido.",
    "DISALLOWED_WORDS"                     : "As palabras {{1}} non están permitidas no campo {{0}}.",
    "NPM_INSTALL_FAILED"                   : "fallou o comando de instalación npm: {0}",
    "API_NOT_COMPATIBLE"                   : "A extensión non é compatible con esta versión do {APP_NAME}. Está no cartafol de extensións desactivadas.",
    "MISSING_MAIN"                         : "O paquete non contén o ficheiro main.js.",
    "EXTENSION_ALREADY_INSTALLED"          : "Instalar este paquete sobrescribirá unha extensión instalada previamente. Queres sobrescribir a antiga extensión?",
    "EXTENSION_SAME_VERSION"               : "A versión deste paquete é a mesma que a instalada. Queres sobrescribir a instalación actual?",
    "EXTENSION_OLDER_VERSION"              : "A versión {0} deste paquete é máis antiga que a instalada ({1}). Queres sobrescribir a instalación actual?",
    "DOWNLOAD_ID_IN_USE"                   : "Erro interno: o ID da descarga xa se está a utilizar.",
    "NO_SERVER_RESPONSE"                   : "Non é posíbel conectar co servidor.",
    "BAD_HTTP_STATUS"                      : "Ficheiro non atopado no servidor (HTTP {0}).",
    "CANNOT_WRITE_TEMP"                    : "Non se puido gardar a descarga nun ficheiro temporal.",
    "ERROR_LOADING"                        : "A extensión atopou un erro ó arrancar.",
    "MALFORMED_URL"                        : "O URL non é válido. Por favor, comproba que o escribiches correctamente.",
    "UNSUPPORTED_PROTOCOL"                 : "O URL ten que ser un enderezo http ou https.",
    "UNKNOWN_ERROR"                        : "Erro interno descoñecido.",
    // For NOT_FOUND_ERR, see generic strings above
    "EXTENSION_MANAGER_TITLE"              : "Xestor de extensións",
    "EXTENSION_MANAGER_ERROR_LOAD"         : "Non foi posíbel acceder ao rexistro de extensións. Por favor, téntao de novo máis tarde.",
    "INSTALL_EXTENSION_DRAG"               : "Arrastra o .zip aquí ou",
    "INSTALL_EXTENSION_DROP"               : "Solta o .zip para instalar",
    "INSTALL_EXTENSION_DROP_ERROR"         : "A Instalación/Actualizacións foi cancelada polos seguintes erros:",
    "INSTALL_FROM_URL"                     : "Instalar dende URL\u2026",
    "INSTALL_EXTENSION_VALIDATING"         : "Validando\u2026",
    "EXTENSION_AUTHOR"                     : "Autor",
    "EXTENSION_DATE"                       : "Data",
    "EXTENSION_INCOMPATIBLE_NEWER"         : "Esta extensión precisa dunha versión máis actualizada do {APP_NAME}.",
    "EXTENSION_INCOMPATIBLE_OLDER"         : "Neste intre esta extensión só funciona con versións anteriores do {APP_NAME}.",
    "EXTENSION_LATEST_INCOMPATIBLE_NEWER"  : "A versión {0} desta extensión precisa dunha versión superior do {APP_NAME}. Podes instalar a versión anterior {1}.",
    "EXTENSION_LATEST_INCOMPATIBLE_OLDER"  : "A versión {0} desta extensión só funciona con versións anteriores do {APP_NAME}. Podes instalar a versión anterior {1}.",
    "EXTENSION_NO_DESCRIPTION"             : "Sen descrición",
    "EXTENSION_MORE_INFO"                  : "Máis información...",
    "EXTENSION_ERROR"                      : "Erro na extensión",
    "EXTENSION_KEYWORDS"                   : "Palabras chave",
    "EXTENSION_TRANSLATED_USER_LANG"       : "Traducido a {0} linguas, incluída a túa",
    "EXTENSION_TRANSLATED_GENERAL"         : "Traducido a {0} linguas",
    "EXTENSION_TRANSLATED_LANGS"           : "Esta extensión foi traducida ás seguintes linguas: {0}",
    "EXTENSION_INSTALLED"                  : "Instalada",
    "EXTENSION_UPDATE_INSTALLED"           : "Descargouse a actualización desta extensión, instalarase despois de recargar {APP_NAME}.",
    "EXTENSION_SEARCH_PLACEHOLDER"         : "Buscar",
    "EXTENSION_MORE_INFO_LINK"             : "Máis",
    "BROWSE_EXTENSIONS"                    : "Explorar extensións",
    "EXTENSION_MANAGER_REMOVE"             : "Eliminar extensión",
    "EXTENSION_MANAGER_REMOVE_ERROR"       : "Non se puido eliminar unha ou máis extensións: {{0}}. {APP_NAME} recargarase igualmente.",
    "EXTENSION_MANAGER_UPDATE"             : "Actualizar extensión",
    "EXTENSION_MANAGER_UPDATE_ERROR"       : "Non se puido actualizar unha ou máis extensións: {{0}}. {APP_NAME} recargarase igualmente.",
    "EXTENSION_MANAGER_DISABLE"            : "Desactivar extensións",
    "EXTENSION_MANAGER_DISABLE_ERROR"      : "Non foi posíbel desactivar unha ou máis extensións: {0}. {APP_NAME} continuará a se recargar.",
    "MARKED_FOR_REMOVAL"                   : "Marcada para eliminar",
    "UNDO_REMOVE"                          : "Desfacer",
    "MARKED_FOR_UPDATE"                    : "Marcada para actualizar",
    "UNDO_UPDATE"                          : "Desfacer",
    "MARKED_FOR_DISABLING"                 : "Marcada para desactivar",
    "UNDO_DISABLE"                         : "Desfacer",
    "CHANGE_AND_RELOAD_TITLE"              : "Trocar extensións",
    "CHANGE_AND_RELOAD_MESSAGE"            : "Para actualizar ou eliminar as extensións marcadas, precisas recargar {APP_NAME}. Solicitarase confirmación para gardar os trocos pendentes.",
    "REMOVE_AND_RELOAD"                    : "Eliminar extensións e recargar",
    "CHANGE_AND_RELOAD"                    : "Trocar extensións e recargar",
    "UPDATE_AND_RELOAD"                    : "Actualizar extensións e recargar",
    "DISABLE_AND_RELOAD"                   : "Desactivar extensións e recargar",
    "PROCESSING_EXTENSIONS"                : "Procesando os trocos nas extensións\u2026",
    "EXTENSION_NOT_INSTALLED"              : "Non se puido eliminar a extensión {{0}} porque non está instalada.",
    "NO_EXTENSIONS"                        : "Aínda non hai ningunha extensión instalada.<br />Fai clic na lapela \"Dispoñíbeis\" para comenzar.",
    "NO_EXTENSION_MATCHES"                 : "Non hai extensións que coincidan coa túa busca.",
    "REGISTRY_SANITY_CHECK_WARNING"        : "NOTA: Estas extensións poden provir de diferentes autores a {APP_NAME}. As extensións non son revisadas e teñen todos os privilexios locais. Ten coidado cando instales extensións dunha fonte descoñecida.",
    "EXTENSIONS_INSTALLED_TITLE"           : "Instaladas",
    "EXTENSIONS_DEFAULT_TITLE"             : "Predefinida",
    "EXTENSIONS_AVAILABLE_TITLE"           : "Dispoñíbeis",
    "EXTENSIONS_THEMES_TITLE"              : "Temas",
    "EXTENSIONS_UPDATES_TITLE"             : "Actualizacións",
    "EXTENSIONS_LAST_UPDATED"              : "Últimas Actualizacións",
    "EXTENSIONS_DOWNLOADS"                 : "Descargas",

    "INLINE_EDITOR_NO_MATCHES"             : "Sen coincidencias dispoñíbeis.",
    "INLINE_EDITOR_HIDDEN_MATCHES"         : "Tódalas coincidencias están ocultas. Expande os ficheiros listados á dereita para ver coincidencias.",
    "CSS_QUICK_EDIT_NO_MATCHES"            : "Sen regras CSS existentes que coincidan coa túa selección.<br> Fai clic en \"Nova regra\" para crear unha.",
    "CSS_QUICK_EDIT_NO_STYLESHEETS"        : "Sen follas de estilos no teu proxecto.<br>Crea unha para engadir regras CSS.",

    // Custom Viewers
    "IMAGE_VIEWER_LARGEST_ICON"            : "máis grande",

    /**
     * Unit names
     */
    "UNIT_PIXELS"                          : "píxeles",

    // extensions/default/DebugCommands
    "DEBUG_MENU"                                : "Desenvolvemento",
    "ERRORS"                                    : "Erros",
    "CMD_SHOW_DEV_TOOLS"                        : "Amosar ferramentas para desenvolvedores",
    "CMD_REFRESH_WINDOW"                        : "Recargar con extensións",
    "CMD_RELOAD_WITHOUT_USER_EXTS"              : "Recargar sen extensións",
    "CMD_NEW_BRACKETS_WINDOW"                   : "Nova xanela do {APP_NAME}",
    "CMD_LAUNCH_SCRIPT_MAC"                     : "Instalar atallo dende a liña de ordes",
    "CMD_SWITCH_LANGUAGE"                       : "Trocar a lingua",
    "CMD_RUN_UNIT_TESTS"                        : "Executar probas",
    "CMD_SHOW_PERF_DATA"                        : "Amosar información de rendemento",
    "CMD_ENABLE_NODE_DEBUGGER"                  : "Activar depuración de Node",
    "CMD_LOG_NODE_STATE"                        : "Amosar estado de Node na Consola",
    "CMD_RESTART_NODE"                          : "Reiniciar Node",
    "CMD_SHOW_ERRORS_IN_STATUS_BAR"             : "Amosar erros na barra de estado",
    "CMD_OPEN_BRACKETS_SOURCE"                  : "Ver o código do Brackets",

    "CREATING_LAUNCH_SCRIPT_TITLE"              : "Atallo ao {APP_NAME} dende a liña de ordes",
    "ERROR_CREATING_LAUNCH_SCRIPT"              : "Produciuse un erro ao instalar o atallo dende a liña de ordes. Por favor, proba <a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments#troubleshooting'>estas suxestión á solución de problemas</a>.<br><br>Razón: {0}",
    "ERROR_CLTOOLS_RMFAILED"                    : "Non foi posíbel eliminar a ligazón simbólica existente <code>/usr/local/bin/brackets</code>.",
    "ERROR_CLTOOLS_MKDIRFAILED"                 : "Non foi posíbel crear o cartafol <code>/usr/local/bin</code>.",
    "ERROR_CLTOOLS_LNFAILED"                    : "Non foi posíbel crear a ligazón simbólica <code>/usr/local/bin/brackets</code>.",
    "ERROR_CLTOOLS_SERVFAILED"                  : "Erro interno.",
    "ERROR_CLTOOLS_NOTSUPPORTED"                : "O atallo por liña de ordes non é compatíbel con este sistema operativo.",
    "LAUNCH_SCRIPT_CREATE_SUCCESS"              : "Parabéns! Xa podes abrir dun xeito doado o {APP_NAME} dende a liña de ordes: <code>brackets ficheiro.txt</code> para abrir un ficheiro ou <code>brackets cartafol</code> para trocar de proxecto.<br><br><a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments'>Saber máis</a> sobre como empregar o {APP_NAME} dende a liña de ordes.",

    "LANGUAGE_TITLE"                            : "Trocar lingua",
    "LANGUAGE_MESSAGE"                          : "Lingua:",
    "LANGUAGE_SUBMIT"                           : "Reiniciar {APP_NAME}",
    "LANGUAGE_CANCEL"                           : "Cancelar",
    "LANGUAGE_SYSTEM_DEFAULT"                   : "Lingua predeterminada",

    // extensions/default/HealthData
    "HEALTH_DATA_NOTIFICATION"                  : "Preferencias do informe de estatísticas",
    "HEALTH_FIRST_POPUP_TITLE"                  : "Informe de estatísticas do {APP_NAME}",
    "HEALTH_DATA_DO_TRACK"                      : "Compartir información anónima sobre como emprego o {APP_NAME}",
    "HEALTH_DATA_NOTIFICATION_MESSAGE"          : "Para poder mellorar o {APP_NAME}, enviamos periodicamente pequenas estatísticas <strong>anónimas</strong> a Adobe sobre como é empregado o {APP_NAME}. Esta información axuda a dar prioridade ás características a desenvolver, atopar erros e problemas de usabilidade.<br><br>Podes ver os teus datos ou non compartirlos seleccionando <strong>Axuda > Informe de estatísticas</strong>.<br><br><a href='https://github.com/adobe/brackets/wiki/Health-Data'>Para saber máis sobre o informe de estatísticas de {APP_NAME}</a>",
    "HEALTH_DATA_PREVIEW"                       : "Informe de estatísticas do {APP_NAME}",
    "HEALTH_DATA_PREVIEW_INTRO"                 : "<p>Para poder mellorar o {APP_NAME}, enviamos periodicamente pequenas estatísticas <strong>anónimas</strong> a Adobe sobre como é empregado o {APP_NAME}. Esta información axuda a dar prioridade ás características a desenvolver, atopar erros e problemas de usabilidade. <a href='https://github.com/adobe/brackets/wiki/Health-Data'>Para saber máis sobre o Informe de estatísticas do {APP_NAME}</a> e como beneficia á comunidade do {APP_NAME} mentres protexe a túa privacidade.</p><p>A seguir verás a información a enviar no seguinte Informe de estatísticas <em>se</em> está activado.</p>",

    // extensions/default/InlineTimingFunctionEditor
    "INLINE_TIMING_EDITOR_TIME"                 : "Tempo",
    "INLINE_TIMING_EDITOR_PROGRESSION"          : "Progresión",
    "BEZIER_EDITOR_INFO"                        : "<kbd>↑</kbd><kbd>↓</kbd><kbd>←</kbd><kbd>→</kbd> Moven o punto seleccionado<br><kbd class='text'>Shift</kbd> Move de a dez unidades<br><kbd class='text'>Tab</kbd> Troca o punto seleccionado",
    "STEPS_EDITOR_INFO"                         : "<kbd>↑</kbd><kbd>↓</kbd> Incrementa ou decrementa os pasos<br><kbd>←</kbd><kbd>→</kbd> 'Start' ou 'End'",
    "INLINE_TIMING_EDITOR_INVALID"              : "O valor vello <code>{0}</code> non é válido, polo tanto, foi modificado a <code>{1}</code>. O documento será actualizado despois da primeira edición.",

    // extensions/default/InlineColorEditor
    "COLOR_EDITOR_CURRENT_COLOR_SWATCH_TIP"     : "Cor actual",
    "COLOR_EDITOR_ORIGINAL_COLOR_SWATCH_TIP"    : "Cor orixinal",
    "COLOR_EDITOR_RGBA_BUTTON_TIP"              : "Formato RGBa",
    "COLOR_EDITOR_HEX_BUTTON_TIP"               : "Formato Hex",
    "COLOR_EDITOR_HSLA_BUTTON_TIP"              : "Formato HSLa",
    "COLOR_EDITOR_0X_BUTTON_TIP"                : "Formato Hex (0x)",
    "COLOR_EDITOR_USED_COLOR_TIP_SINGULAR"      : "{0} (Empregado {1} vez)",
    "COLOR_EDITOR_USED_COLOR_TIP_PLURAL"        : "{0} (Empregado {1} veces)",

    // extensions/default/JavaScriptCodeHints
    "CMD_JUMPTO_DEFINITION"                     : "Ir á definición",
    "CMD_SHOW_PARAMETER_HINT"                   : "Amosar suxestións de parámetros",
    "NO_ARGUMENTS"                              : "<sen parámetros>",
    "DETECTED_EXCLUSION_TITLE"                  : "Problema de inferencia cun ficheiro JavaScript",
    "DETECTED_EXCLUSION_INFO"                   : "Brackets atopouse con problemas procesando:<br><br>{0}<br><br>Este ficheiro non volverá a ser procesado para as suxestións de código e saltar á definición. Para activalo de novo, abre <code>.brackets.json</code> no seu proxecto e elimina o ficheiro de jscodehints.detectedExclusions.",

    // extensions/default/JavascriptRefactoring
    "CMD_REFACTOR"                              : "Refactorizar",
    "CMD_EXTRACTTO_VARIABLE"                    : "Extraer a variable",
    "CMD_EXTRACTTO_FUNCTION"                    : "Extraer a función",
    "ERROR_TERN_FAILED"                         : "Non é posíbel obter datos do Tern",
    "ERROR_EXTRACTTO_VARIABLE_NOT_VALID"        : "A selección non forma unha expresión",
    "ERROR_EXTRACTTO_FUNCTION_NOT_VALID"        : "O bloque seleccionado ten que representar un conxunto de instrucións ou unha expresión",
    "ERROR_EXTRACTTO_VARIABLE_MULTICURSORS"     : "Extraer a variable non funciona con múltiples cursores",
    "ERROR_EXTRACTTO_FUNCTION_MULTICURSORS"     : "Extraer a función non funciona con múltiples cursores",
    "EXTRACTTO_FUNCTION_SELECT_SCOPE"           : "Seleccionar ámbito de destino",
    "EXTRACTTO_VARIABLE_SELECT_EXPRESSION"      : "Seleccionar unha expresión",
    "CMD_REFACTORING_RENAME"                    : "Renomear",
    "CMD_REFACTORING_TRY_CATCH"                 : "Axustar no 'Try Catch'",
    "CMD_REFACTORING_CONDITION"                 : "Axustar á Condición",
    "CMD_REFACTORING_GETTERS_SETTERS"           : "Crear Getters/Setters",
    "CMD_REFACTORING_ARROW_FUNCTION"            : "Converter Convert to Arrow Function",
    "DESCRIPTION_CODE_REFACTORING"              : "Activar/desactivar a refactorización de código JavaScript",
    "ERROR_TRY_CATCH"                           : "Seleccionar código válido para axustar a un bloque Try-catch",
    "ERROR_WRAP_IN_CONDITION"                   : "Seleccionar código válido para axustar a un bloque condicional",
    "ERROR_ARROW_FUNCTION"                      : "Coloca o cursor dentro dunha expresión de función",
    "ERROR_GETTERS_SETTERS"                     : "Coloca o cursor no membro dun obxecto de expresión",
    "ERROR_RENAME_MULTICURSOR"                  : "Non é posíbel renomear ao empregar múltiples cursores",
    "ERROR_RENAME_QUICKEDIT"                    : "Non é posíbel renomear este identificador, xa que esta referenciado fora desta función",
    "ERROR_RENAME_GENERAL"                      : "Non é posíbel renomear o texto seleccionado",

    // extensions/default/JSLint
    "JSLINT_NAME"                               : "JSLint",

    // extensions/default/QuickView
    "CMD_ENABLE_QUICK_VIEW"                     : "Vista rápida co cursor",

    // extensions/default/RecentProjects
    "CMD_TOGGLE_RECENT_PROJECTS"                : "Proxectos recentes",

    // extensions/default/MDNDocs
    "DOCS_MORE_LINK"                            : "Máis"

    // extensions/default/CodeFolding
    "COLLAPSE_ALL"                  : "Colapsar todo",
    "EXPAND_ALL"                    : "Expandir todo",
    "COLLAPSE_CURRENT"              : "Colapsar actual",
    "EXPAND_CURRENT"                : "Expandir actual",

    // extensions/default/NavigationAndHistory
    "RECENT_FILES_DLG_HEADER"                    : "Ficheiros recentes",
    "RECENT_FILES_DLG_CLEAR_BUTTON_LABEL"        : "Limpar",
    "RECENT_FILES_DLG_CLEAR_BUTTON_TITLE"        : "Limpar ficheiros que non están na Área de traballo",

    // Descriptions of core preferences
    "DESCRIPTION_CLOSE_BRACKETS"                     : "true para pechar automaticamente as chaves, os corchetes e as parénteses",
    "DESCRIPTION_CLOSE_OTHERS_ABOVE"                 : "false para eliminar \"Pechar outros por enriba\" do menú contextual da Área de traballo",
    "DESCRIPTION_CLOSE_OTHERS_BELOW"                 : "false para eliminar \"Pechar outros por abaixo\" do menú contextual da Área de traballo",
    "DESCRIPTION_CLOSE_OTHERS"                       : "false para eliminar \"Pechar outros\" do menú contextual da Área de traballo",
    "DESCRIPTION_CLOSE_TAGS"                         : "Configura os axustes de peche de etiquetas automático",
    "DESCRIPTION_CLOSE_TAGS_DONT_CLOSE_TAGS"         : "Un vector de etiquetas que non deben pecharse automaticamente",
    "DESCRIPTION_CLOSE_TAGS_WHEN_OPENING"            : "Pechar ao escribir \">\" da etiqueta de apertura",
    "DESCRIPTION_CLOSE_TAGS_WHEN_CLOSING"            : "Pechar ao escribir \"/\" da etiqueta de clausura",
    "DESCRIPTION_CLOSE_TAGS_INDENT_TAGS"             : "Un vector de etiquetas que cuando se cierran generan una linea en blanco entre las etiquetas",
    "DESCRIPTION_CODE_FOLDING_ALWAY_USE_INDENT_FOLD" : "true para siempre generar marcadores plegables cuando cambia el nivel de indentación",
    "DESCRIPTION_CODE_FOLDING_ENABLED"               : "true para activar el colapsado del código",
    "DESCRIPTION_CODE_FOLDING_HIDE_UNTIL_MOUSEOVER"  : "true para hacer marcadores de sección plegables visible só cando se move o cursor sobre o espazo á esquerda do código",
    "DESCRIPTION_CODE_FOLDING_MAX_FOLD_LEVEL"        : "Limita a cantos niveis de profundidade aplica \"Colapsar todo\"",
    "DESCRIPTION_CODE_FOLDING_MIN_FOLD_SIZE"         : "Cantidade mínima de liñas antes de que apareza unha icona de sección colapsábel",
    "DESCRIPTION_CODE_FOLDING_SAVE_FOLD_STATES"      : "true para lembrar as seccións colapsadas despois de pechar e abrir un ficheiro ou proxecto",
    "DESCRIPTION_CODE_FOLDING_MAKE_SELECTIONS_FOLDABLE": "true to enable code folding on selected text in the editor",
    "DESCRIPTION_DISABLED_DEFAULT_EXTENSIONS"        : "Extensión predefinidas que están desactivadas",
    "DESCRIPTION_ATTR_HINTS"                         : "Activar/desactivar as suxestións de código para os atributos de HTML",
    "DESCRIPTION_CSS_PROP_HINTS"                     : "Activar/desactivar as suxestións de código para as propiedades de CSS/LESS/SCSS",
    "DESCRIPTION_JS_HINTS"                           : "Activar/desactivar as suxestións de código de JavaScript",
    "DESCRIPTION_JS_HINTS_TYPE_DETAILS"              : "Activar/desactivar as suxestións de tipos de datos no código Javascript",
    "DESCRIPTION_PREF_HINTS"                         : "Activar/desactivar as suxestións de código para as Preferencias",
    "DESCRIPTION_SPECIAL_CHAR_HINTS"                 : "Activar/desactivar as suxestións de código para as entidades no HTML",
    "DESCRIPTION_SVG_HINTS"                          : "Activar/desactivar as suxestións de código no SVG",
    "DESCRIPTION_HTML_TAG_HINTS"                     : "Activar/desactivar as suxestións de código para as etiquetas no HTML",
    "DESCRIPTION_URL_CODE_HINTS"                     : "Activar/desactivar as suxestións de código para os URLs no HTML & CSS/LESS/SCSS",
    "DESCRIPTION_DRAG_DROP_TEXT"                     : "Activar/desactivar a funcionalidade de arrastrar e soltar",
    "DESCRIPTION_HEALTH_DATA_TRACKING"               : "Activar o seguimento dos Informes de estatísticas",
    "DESCRIPTION_HIGHLIGHT_MATCHES"                  : "Activa o resaltado automático das cadeas que coinciden no documento",
    "DESCRIPTION_HIGHLIGHT_MATCHES_SHOW_TOKEN"       : "Resaltar tódalas cadeas que coincidan coa cadea onde se atopa o cursor (non se precisa selección)",
    "DESCRIPTION_HIGHLIGHT_MATCHES_WORDS_ONLY"       : "Resaltar só cando a selección é unha cadea completa",
    "DESCRIPTION_INSERT_HINT_ON_TAB"                 : "true para inserir a suxestión de código ao premer o tabulador",
    "DESCRIPTION_NO_HINTS_ON_DOT"                    : "true para ocultar suxestións de código automaticamente en JS cando \".\" é tipado",
    "DESCRIPTION_JSLINT_OPTIONS"                     : "Un obxecto cos axustes predefinidos de JSLint",
    "DESCRIPTION_JSLINT_OPTIONS_ASS"                 : "true para permitir expresións de asignación",
    "DESCRIPTION_JSLINT_OPTIONS_BITWISE"             : "true para permitir os operadores bit a bit",
    "DESCRIPTION_JSLINT_OPTIONS_BROWSER"             : "true se as variábeis/funcións globais do navegador deben estar predefinidas",
    "DESCRIPTION_JSLINT_OPTIONS_CLOSURE"             : "true para permitir modismos do Google Closure",
    "DESCRIPTION_JSLINT_OPTIONS_CONTINUE"            : "true para permitir a declaración \"continue\"",
    "DESCRIPTION_JSLINT_OPTIONS_COUCH"               : "true se as variábeis/funcións globais de CouchDB deben estar predefinidas",
    "DESCRIPTION_JSLINT_OPTIONS_DEBUG"               : "true para permitir declaracións do depurador",
    "DESCRIPTION_JSLINT_OPTIONS_DEVEL"               : "true se as variábeis/funcións globais do navegador para o desenvolvemento deben estar predefinidas",
    "DESCRIPTION_JSLINT_OPTIONS_EQEQ"                : "true para permitir == e !=",
    "DESCRIPTION_JSLINT_OPTIONS_ES6"                 : "true se as variábeis/funcións globais de ES6 deben estar predefinidas",
    "DESCRIPTION_JSLINT_OPTIONS_EVIL"                : "true para permitir eval",
    "DESCRIPTION_JSLINT_OPTIONS_FORIN"               : "true para permitir \"for ... in\" sen filtrar",
    "DESCRIPTION_JSLINT_OPTIONS_INDENT"              : "Define un largo para o tabulador",
    "DESCRIPTION_JSLINT_OPTIONS_MAXERR"              : "A cantidade máxima de advertencias informadas",
    "DESCRIPTION_JSLINT_OPTIONS_MAXLEN"              : "A cantidade máxima de caracteres por liña",
    "DESCRIPTION_JSLINT_OPTIONS_NEWCAP"              : "true para permitir construtores sen maiúsculas",
    "DESCRIPTION_JSLINT_OPTIONS_NODE"                : "true se as variábeis/funcións globais de Node.js deben estar predefinidas",
    "DESCRIPTION_JSLINT_OPTIONS_NOMEN"               : "true para permitir o guión baixo diante dos identificadores",
    "DESCRIPTION_JSLINT_OPTIONS_PASSFAIL"            : "true para deter no primeiro erro",
    "DESCRIPTION_JSLINT_OPTIONS_PLUSPLUS"            : "true para permitir ++ e --",
    "DESCRIPTION_JSLINT_OPTIONS_REGEXP"              : "true para permitir . e [^...]. na RegExp",
    "DESCRIPTION_JSLINT_OPTIONS_RHINO"               : "true se as variábeis/funcións globais de Rhino deben estar predefinidas",
    "DESCRIPTION_JSLINT_OPTIONS_SLOPPY"              : "true para permitir a ausencia do pragma `use strict`",
    "DESCRIPTION_JSLINT_OPTIONS_STUPID"              : "true se e posíbel o uso os métodos de bloqueo ('...Sync')",
    "DESCRIPTION_JSLINT_OPTIONS_SUB"                 : "true para permitir subíndices ineficientes",
    "DESCRIPTION_JSLINT_OPTIONS_TODO"                : "true para permitir comentarios TODO",
    "DESCRIPTION_JSLINT_OPTIONS_UNPARAM"             : "true para permitir parámetros non usados",
    "DESCRIPTION_JSLINT_OPTIONS_VARS"                : "true para permitir máis dunha variable nas funcións",
    "DESCRIPTION_JSLINT_OPTIONS_WHITE"               : "true para ignorar as regras de espazado",
    "DESCRIPTION_LANGUAGE"                           : "Preferencias específicas dunha linguaxe",
    "DESCRIPTION_LANGUAGE_FILE_EXTENSIONS"           : "Asignacións adicionais de extensión de ficheiro a nome da linguaxe",
    "DESCRIPTION_LANGUAGE_FILE_NAMES"                : "Asignacións adicionais de nome de ficheiro a nome da linguaxe",
    "DESCRIPTION_LINEWISE_COPY_CUT"                  : "Ao copiar e pegar sen ter nada seleccionado na liña copiará ou cortará a liña completa onde estea o cursor",
    "DESCRIPTION_INPUT_STYLE"                        : "Selects the way CodeMirror handles input and focus. It can be textarea, which is the default, or contenteditable which is better for screen readers (unstable)",
    "DESCRIPTION_LINTING_ENABLED"                    : "true para activar a inspeción de código",
    "DESCRIPTION_ASYNC_TIMEOUT"                      : "O tempo en milisegundos a agardar polos inspectores de código asincrónicos",
    "DESCRIPTION_LINTING_PREFER"                     : "Vector de inspectores de código a executar primeiro",
    "DESCRIPTION_LIVE_DEV_MULTIBROWSER"              : "true para activar a Vista previa dinámica experimental",
    "DESCRIPTION_USE_PREFERED_ONLY"                  : "true para executar só os provedores especificados no linting.prefer",
    "DESCRIPTION_MAX_CODE_HINTS"                     : "Máxima cantidade de suxestións de código a amosar dunha vez",
    "DESCRIPTION_PATH"                               : "Axustes especificos para as rutas de ficheiro",
    "DESCRIPTION_PROXY"                              : "O URL do servidor proxy empregado para a instalación de extensións",
    "DESCRIPTION_SCROLL_PAST_END"                    : "true permitir o desprazamento más alá do final do documento",
    "DESCRIPTION_SHOW_CODE_HINTS"                    : "false para desactivar tódalas suxestións de código",
    "DESCRIPTION_SHOW_CURSOR_WHEN_SELECTING"         : "Mantén visíbel o cursor intermitente ao ter seleccionado un texto",
    "DESCRIPTION_SHOW_LINE_NUMBERS"                  : "true para amosar os números de lína nunha marxe á esquerda do código",
    "DESCRIPTION_SMART_INDENT"                       : "Sangrar automaticamente cando se crea un novo bloque",
    "DESCRIPTION_SOFT_TABS"                          : "false para desactivar o comportamento de \"soft tabs\"",
    "DESCRIPTION_SORT_DIRECTORIES_FIRST"             : "true para ordenar os cartafoles primeiro na árbore do proxecto",
    "DESCRIPTION_SPACE_UNITS"                        : "Cantidade de espazos a empregar no sangrado baseado en espazos",
    "DESCRIPTION_STATIC_SERVER_PORT"                 : "Porto que o servidor empregará para a Vista Previa ao Vivo",
    "DESCRIPTION_STYLE_ACTIVE_LINE"                  : "true para resaltar a liña na que se atopa o cursor",
    "DESCRIPTION_TAB_SIZE"                           : "Cantidade de espazos empregados para a tabulación",
    "DESCRIPTION_USE_TAB_CHAR"                       : "true para empregar tabulacións no canto de espazos",
    "DESCRIPTION_UPPERCASE_COLORS"                   : "true para xerar cor en maiúsculas no editor de cores",
    "DESCRIPTION_WORD_WRAP"                          : "Axustar as liñas que superan o largo do viewport",
    "DESCRIPTION_WORD_WRAP"                          : "Axustar as liñas que sobrepasen o longo da xanela",
    "DESCRIPTION_DETECTED_EXCLUSIONS"                : "Unha listaxe dos ficheiros detectados e que provocan que o Tern non funcione correctamente",
    "DESCRIPTION_INFERENCE_TIMEOUT"                  : "A cantidade de veces despois da que o Tern deixará de tentar entender os ficheiros",
    "DESCRIPTION_SHOW_ERRORS_IN_STATUS_BAR"          : "true para amosar erros na barra de estado",
    "DESCRIPTION_QUICK_VIEW_ENABLED"                 : "true para activar a Vista rápida",
    "DESCRIPTION_EXTENSION_LESS_IMAGE_PREVIEW"       : "true para amosar a vista previa de imaxes para URLs sen extensión",
    "DESCRIPTION_THEME"                              : "Seleccionar un tema para {APP_NAME}",
    "DESCRIPTION_USE_THEME_SCROLLBARS"               : "true para activar a barra de desprazamento personalizada",
    "DESCRIPTION_LINTING_COLLAPSED"                  : "true para contraer o panel de inspeción de código",
    "DESCRIPTION_FONT_FAMILY"                        : "Trocar a fonte",
    "DESCRIPTION_FONT_SIZE"                          : "Trocar o tamaño da fonte, ex.: 13px",
    "DESCRIPTION_FIND_IN_FILES_NODE"                 : "true para activar as buscas baseadas en node",
    "DESCRIPTION_FIND_IN_FILES_INSTANT"              : "true para activar a busca instantánea",
    "DESCRIPTION_FONT_SMOOTHING"                     : "Só para Mac: \"subpixel-antialiased\" para activar sub-píxel antialiasing ou \"antialiased\" para antialiasing en escala de grises",
    "DESCRIPTION_OPEN_PREFS_IN_SPLIT_VIEW"           : "false para desactivar a apertura do ficheiro de preferencias na vista dividida",
    "DESCRIPTION_OPEN_USER_PREFS_IN_SECOND_PANE"     : "false para abrir o ficheiro de preferencias no panel da esquerda/arriba",
    "DESCRIPTION_MERGE_PANES_WHEN_LAST_FILE_CLOSED"  : "true para contraer os paneis despois que o último ficheiro se peche dende o botón da cabeceira do panel",
    "DESCRIPTION_SHOW_PANE_HEADER_BUTTONS"           : "Toggle when to show the close and flip-view buttons on the header.",
    "DEFAULT_PREFERENCES_JSON_HEADER_COMMENT"        : "/*\n * Este é un ficheiro de só lectura coas preferencias soportadas\n * por {APP_NAME}.\n * Emprega este ficheiro como referencia para modificar o teu ficheiro de\n * preferencias \"brackets.json\" aberto no outro panel.\n * Para máis información de como usar as preferencias dentro d0\n * {APP_NAME}, podes consultar a páxina web https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences\n */",
    "DEFAULT_PREFERENCES_JSON_DEFAULT"               : "Predefinido"
    "DESCRIPTION_PURE_CODING_SURFACE"                : "true para activar o modo de só código e ocultar tódolos outros elementos da interface no {APP_NAME}",
    "DESCRIPTION_INDENT_LINE_COMMENT"                : "true para activar o sangrado das liñas de comentarios",
    "DESCRIPTION_RECENT_FILES_NAV"                   : "Activar/desactivar a navegación nos ficheiros recentes",
    "DESCRIPTION_LIVEDEV_WEBSOCKET_PORT"             : "Porto no que se executa a Vista Previa ao Vivo",
    "DESCRIPTION_LIVE_DEV_HIGHLIGHT_SETTINGS"        : "Axuste do resaltado da Vista Previa ao Vivo",
    "DESCRIPTION_LIVEDEV_ENABLE_REVERSE_INSPECT"     : "false para desactivar a inspección reversa da Vista Previa ao Vivo"
    
    // Strings for Auto Update
    "DOWNLOAD_FAILED"                                : "Produciuse un erro na descarga.",
    "DOWNLOAD_COMPLETE"                              : "Descarga completada!",
    "UPDATE_SUCCESSFUL"                              : "Actualización con éxito!",
    "UPDATE_FAILED"                                  : "Produciuse un erro na actualización!",
    "VALIDATION_FAILED"                              : "Produciuse un erro na validación!",
    "INITIALISATION_FAILED"                          : "Produciuse un erro na inicialización!",
    "CLEANUP_FAILED"                                 : "Produciuse un erro na limpeza!",
    "WARNING_TYPE"                                   : "Atención!",
    "CLICK_RESTART_TO_UPDATE"                        : "Preme en Reiniciar para actualizar o Brackets.",
    "UPDATE_ON_NEXT_LAUNCH"                          : "A actualización aplicarase ao reiniciar.",
    "GO_TO_SITE"                                     : "Vai a <a href = \"http://brackets.io/\"> brackets.io </a> para tentar de novo.",
    "INTERNET_UNAVAILABLE"                           : "Sen conexión a Internet dispoñíbel.",
    "UPDATEDIR_READ_FAILED"                          : "Non se puido ler no cartafol de actualizacións.",
    "UPDATEDIR_CLEAN_FAILED"                         : "Non se puido limpar o cartafol de actualizacións.",
    "INITIAL_DOWNLOAD"                               : "Descargando actualizacións...",
    "RETRY_DOWNLOAD"                                 : "Produciuse un erro na descarga. Tentando de novo ",
    "VALIDATING_INSTALLER"                           : "Descarga completada! Verificando o instalador...",
    "CHECKSUM_DID_NOT_MATCH"                         : "O Checksum non coincide.",
    "INSTALLER_NOT_FOUND"                            : "Non se atopou o instalador.",
    "DOWNLOAD_ERROR"                                 : "Prouciuse un erro ao descargar.",
    "NETWORK_SLOW_OR_DISCONNECTED"                   : "Rede desconectada ou moi lenta.",
    "RESTART_BUTTON"                                 : "Reiniciar",
    "LATER_BUTTON"                                   : "Máis tarde",
    "DESCRIPTION_AUTO_UPDATE"                        : "Activar/Desactivar actualización automática do Brackets",
    "AUTOUPDATE_ERROR"                               : "Erro!",
    "AUTOUPDATE_IN_PROGRESS"                         : "Hai unha actualización en progreso.",
    
    "NUMBER_WITH_PERCENTAGE"                         : "{0}%",
    // Strings for Related Files
    "CMD_FIND_RELATED_FILES"                         : "Buscar ficheiros relacionados"
});

/* Last translated for a4e9a06605cfca5dff5ab5dbacfb1d97c604b6f0 */
