/*jslint vars: true, plusplus: true, devel: true, nomen: true, indent: 4, maxerr: 50 */
/*global define */

define({
    "ATTRIBUTE_IN_CLOSING_TAG": "<p><em data-highlight='[[closeTag.start]],[[closeTag.end]]'>ここ</em> の終了タグ <code>&lt;/[[closeTag.name]]&gt;</code> は属性を含む事はできません。</p>",
    "CLOSE_TAG_FOR_VOID_ELEMENT": "<p><em data-highlight='[[closeTag.start]],[[closeTag.end]]'>ここ</em> のタグを閉じる <code>&lt;/[[closeTag.name]]&gt;</code> タグは無効な要素です (このタグは閉じる必要がありません)。</p>",
    "CSS_MIXED_ACTIVECONTENT": "<p><em data-highlight='[[cssValue.start]],[[cssValue.end]]'>ここ</em> の CSS プロパティ <em data-highlight='[[cssProperty.start]],[[cssProperty.end]]'>[[cssProperty.property]]</em> に 安全でないリソースへリンクした url() 値が書かれています。このエラーは Webmaker にログインすると表示されなくなります。モダンブラウザが、どのように安全でないコンテンツを警告するかについての詳細は <a href='https://developer.mozilla.org/ja/docs/Security/MixedContent'>このリンク</a> を訪問してください。</p>",
    "EVENT_HANDLER_ATTR_NOT_ALLOWED": "<p>申し訳ありませんが、サイトのセキュリティ上の制限により、<em data-highlight='[[name.start]],[[name.end]]'>ここ</em> に書かれた JavaScript イベントハンドラ属性は使用できません。JavaScript を本当に使用する必要がある場合は、<a href='http://jsbin.com/'>jsbin</a> や <a href='http://jsfiddle.net/'>jsfiddle</a> をご利用ください。</p>",
    "HTML_CODE_IN_CSS_BLOCK": "<p>HTML コードが、CSS 内の <em data-highlight='[[html.start]],[[html.end]]'>ここ</em> で検知されました。</p>",
    "HTTP_LINK_FROM_HTTPS_PAGE": "<p><code>&lt;[[openTag.name]]&gt;</code> タグの <code>[[attribute.name.value]]</code> 属性 (<em data-highlight='[[attribute.value.start]],[[attribute.value.end]]'>ここ</em>) は、安全でないリソースを参照しています。Webmaker にログインするとこのエラーは消えます。モダンブラウザが安全でないコンテンツを警告することについての詳しい情報は、<a href='https://developer.mozilla.org/ja/docs/Security/MixedContent'>このリンク</a> を訪問してください。</p>",
    "INVALID_ATTR_NAME": "<p><em data-highlight='[[start]],[[end]]'>ここの</em> 属性は HTML5 の命名規則で許可されていない名前です。</p>",
    "UNSUPPORTED_ATTR_NAMESPACE": "<p><em data-highlight='[[start]],[[end]]'>この</em> 属性は HTML5 の名前空間で許可されていない名前です。</p>",
    "MULTIPLE_ATTR_NAMESPACES": "<p><em data-highlight='[[start]],[[end]]'>この</em> 属性は、複数の名前空間を持っています。テキストを確認して、属性が 1 つの名前空間に従うようにして下さい。</p>",
    "INVALID_CSS_DECLARATION": "<p><em data-highlight='[[cssDeclaration.start]],[[cssDeclaration.end]]'>この</em> CSS 宣言は閉じられていません。</p>",
    "INVALID_CSS_PROPERTY_NAME": "<p><em data-highlight='[[cssProperty.start]],[[cssProperty.end]]'>[[cssProperty.property]]</em> という CSS プロパティは、存在しません。<p><a href=https://developer.mozilla.org/ja/CSS/CSS_Reference'>CSS プロパティのスト</a> をご覧ください。</p>",
    "INVALID_CSS_RULE": "<p><em data-highlight='[[cssRule.start]],[[cssRule.end]]'>この</em> CSS ルールは正しい CSS ではありません。</p>",
    "INVALID_TAG_NAME": "<p><em data-highlight='[[openTag.start]],[[openTag.end]]'>ここ</em> の <code>&lt;</code> の記号は、タグの開始に使用されますが、タグの名前が正しくありません。</p> <p>Web ページ上に <code>&lt;</code> を表示させたい場合は、<code>&amp;lt;</code> を代わりに使用してください。</p> <p>または、<a href='https://developer.mozilla.org/en/docs/Web/Guide/HTML/HTML5/HTML5_element_list'> HTML5 タグのリスト</a> をご覧ください。</p>",
    "JAVASCRIPT_URL_NOT_ALLOWED": "<p>申し訳ありませんが、サイトのセキュリティ上の制限により、<em data-highlight='[[value.start]],[[value.end]]'>ここ</em> に書かれた <code>javascript:</code> URL は使用できません。JavaScript を本当に使用する必要がある場合は、<a href='http://jsbin.com/'>jsbin</a> や <a href='http://jsfiddle.net/'>jsfiddle</a> を使用してください。</p>",
    "MISMATCHED_CLOSE_TAG": "<p><em data-highlight='[[closeTag.start]],[[closeTag.end]]'>ここ</em> の要素を閉じる <code>&lt;/[[closeTag.name]]&gt;</code> タグは、<em data-highlight='[[openTag.start]],[[openTag.end]]'>ここ</em> の要素を開く <code>&lt;[[openTag.name]]&gt;</code> タグとペアになっていません。<code>&lt;/[[openTag.name]]&gt;</code> タグが不足しているかもしれません。",
    "MISSING_CSS_BLOCK_CLOSER": "<p>ブロックを閉じる括弧または <em data-highlight='[[cssValue.start]],[[cssValue.end]]'>[[cssValue.value]]</em> に続く次の「プロパティ:値;」のペアが足りません。</p>",
    "MISSING_CSS_BLOCK_OPENER": "<p><em data-highlight='[[cssSelector.start]],[[cssSelector.end]]'>[[cssSelector.selector]]</em> についてのブロックを開く括弧が足りません。</p>",
    "MISSING_CSS_PROPERTY": "<p><em data-highlight='[[cssSelector.start]],[[cssSelector.end]]'>[[cssSelector.selector]]</em> にプロパティが足りません。</p>",
    "MISSING_CSS_SELECTOR": "<p> <em data-highlight='[[cssBlock.start]],[[cssBlock.end]]'>ここ</em> に、新しい CSS セレクタか &lt;/style&gt; タグが不足しています。</p>",
    "MISSING_CSS_VALUE": "<p><em data-highlight='[[cssProperty.start]],[[cssProperty.end]]'>[[cssProperty.property]]</em> に値が足りません。</p>",
    "SCRIPT_ELEMENT_NOT_ALLOWED": "<p>申し訳ありませんが、サイトのセキュリティ上の制限により、<em data-highlight='[[openTag.start]],[[closeTag.end]]'>ここ</em> に書かれた <code>&lt;script&gt;</code> タグは使用できません。JavaScript を本当に使用する必要がある場合は、<a href='http://jsbin.com/'>jsbin</a> や <a href='http://jsfiddle.net/'>jsfiddle</a> をご利用ください。</p>",
    "SELF_CLOSING_NON_VOID_ELEMENT": "<p><code>&lt;[[name]]&gt;</code> は空要素ではないため、<em data-highlight='[[start]],[[end]]'>ここ</em> に書かれた <code>&lt;[[name]]&gt;</code> タグは単独で閉じることはできません。 もう一つの <code>&lt;/[[name]]&gt;</code> タグで閉じてください。</p>",
    "UNCAUGHT_CSS_PARSE_ERROR": "<p>予期しない外部エラーが発生しました: <em data-highlight='[[error.start]],[[error.end]]'>[[error.msg]]</em></p>",
    "UNCLOSED_TAG": "<p><em data-highlight='[[openTag.start]],[[openTag.end]]'>ここ</em> の <code>&lt;/[[closeTag.name]]&gt;</code> タグが、閉じられていません。</p>",
    "UNEXPECTED_CLOSE_TAG": "<p><em data-highlight='[[closeTag.start]],[[closeTag.end]]'>ここ</em> の要素を閉じる <code>&lt;/[[closeTag.name]]&gt;</code> タグは、閉じるタグが必要な開いたタグがないため、どのタグともペアになっていません。</p>",
    "UNFINISHED_CSS_PROPERTY": "<p>プロパティ名 <em data-highlight='[[cssProperty.start]],[[cssProperty.end]]'>[[cssProperty.property]]</em> の後に : (コロン) を書く必要があります。</p>",
    "UNFINISHED_CSS_SELECTOR": "<p>セレクタ <em data-highlight='[[cssSelector.start]],[[cssSelector.end]]'>[[cssSelector.selector]]</em> の後に { を書く必要があります。</p>",
    "UNFINISHED_CSS_VALUE": "<p><em data-highlight='[[cssValue.start]],[[cssValue.end]]'>[[cssValue.value]]</em> の値の後に ; (セミコロン) を書く必要があります。</p>",
    "UNKOWN_CSS_KEYWORD": "<p><em data-highlight='[[cssKeyword.start]],[[cssKeyword.end]]'>[[cssKeyword.value]]</em> の CSS @規則はどの @規則とも一致しません。</p>",
    "UNQUOTED_ATTR_VALUE": "<p><em data-highlight='[[start]]'>ここ</em> の属性値は、値を囲むダブルクォートで始めてください。</p>",
    "UNTERMINATED_ATTR_VALUE": "<p><em data-highlight='[[attribute.value.start]]'>ここ</em> の <code>&lt;[[openTag.name]]&gt;</code> タグの <code>[[attribute.name.value]]</code> 属性はの値がダブルクォーテーション (\") で終了していません。</p>",
    "UNTERMINATED_CLOSE_TAG": "<p><em data-highlight='[[closeTag.start]],[[closeTag.end]]'>ここ</em> の要素を閉じる <code>&lt;/[[closeTag.name]]&gt;</code> タグは、<code>&gt;</code> で終了していません。</p>",
    "UNTERMINATED_COMMENT": "<p><em data-highlight='[[start]]'>ここ</em> のコメントは <code>--&gt;</code> で終わっていません。</p>",
    "UNTERMINATED_CSS_COMMENT": "<p><em data-highlight='[[start]]'>ここの</em> CSS のコメントが、<code>*/</code> で終了していません。</p>",
    "UNTERMINATED_OPEN_TAG": "<p><em data-highlight='[[openTag.start]],[[openTag.end]]'>ここ</em> のタグを開く <code>&lt;/[[closeTag.name]]&gt;</code> タグは、<code>&gt;</code> で終了していません。</p>"
});
