/*
 * Copyright (c) 2012 - present Adobe Systems Incorporated. All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

/*jslint vars: true, plusplus: true, devel: true, nomen: true, indent: 4, maxerr: 50 */
/*global define */

define({

    /**
     * Errors
     */

    // General file io error strings
    "GENERIC_ERROR"                     : "(błąd {0})",
    "NOT_FOUND_ERR"                     : "Nie znaleziono pliku.",
    "NOT_READABLE_ERR"                  : "Nie można odczytać pliku.",
    "EXCEEDS_MAX_FILE_SIZE"             : "Pliki są większe niż {0} MB nie mogą być otworzone w {APP_NAME}.",
    "NO_MODIFICATION_ALLOWED_ERR"       : "Nie można zmienić folderu docelowego.",
    "NO_MODIFICATION_ALLOWED_ERR_FILE"  : "Brak pozwolenia na modyfikację.",
    "CONTENTS_MODIFIED_ERR"             : "Plik został zmodyfikowany z zewnątrz.",
    "UNSUPPORTED_ENCODING_ERR"          : "{APP_NAME} aktualnie obsługuje jedynie pliki zakdowane w UTF-8",
    "FILE_EXISTS_ERR"                   : "Ten plik lub folder już istnieje",
    "FILE"                              : "plik",
    "FILE_TITLE"                        : "Plik",
    "DIRECTORY"                         : "folder",
    "DIRECTORY_TITLE"                   : "Folder",
    "DIRECTORY_NAMES_LEDE"              : "Nazwy folderów",
    "FILENAMES_LEDE"                    : "Nazwy plików",
    "FILENAME"                          : "Nazwa pliku",
    "DIRECTORY_NAME"                    : "Nazaw folderu",

    // Project error strings
    "ERROR_LOADING_PROJECT"             : "Wystąpił błąd podczas ładowania projektu.",
    "OPEN_DIALOG_ERROR"                 : "Wystąpił błąd podczas wyświetlania okna otwierania pliku. (błąd {0})",
    "REQUEST_NATIVE_FILE_SYSTEM_ERROR"  : "Wystąpił błąd przy próbie otwarcia katalogu <span class='dialog-filename'>{0}</span>. (błąd {1})",
    "READ_DIRECTORY_ENTRIES_ERROR"      : "Wystąpił błąd podczas odczytu zawartości katalogu <span class='dialog-filename'>{0}</span>. (błąd {1})",

    // File open/save error string
    "ERROR_OPENING_FILE_TITLE"          : "Błąd podczas otwierania pliku",
    "ERROR_OPENING_FILE"                : "Wystąpił błąd podczas próby otwarcia pliku <span class='dialog-filename'>{0}</span>. {1}",
    "ERROR_OPENING_FILES"               : "Podczas próby otwierania następujących plików wystąpił błąd:",
    "ERROR_RELOADING_FILE_TITLE"        : "Błąd podczas przeładowywania zmian z dysku",
    "ERROR_RELOADING_FILE"              : "Wystąpił bład podczas próby przeładowania pliku <span class='dialog-filename'>{0}</span>. {1}",
    "ERROR_SAVING_FILE_TITLE"           : "Nie można zapisać pliku",
    "ERROR_SAVING_FILE"                 : "Wystąpił błąd podczas próby zapisu następującego pliku <span class='dialog-filename'>{0}</span>. {1}",
    "ERROR_RENAMING_FILE_TITLE"         : "Nie można zmienić nazwy następującego pliku {0}",
    "ERROR_RENAMING_FILE"               : "Wystąpił błąd podczas próby zmiany nazwy następującego pliku {2} <span class='dialog-filename'>{0}</span>. {1}",
    "ERROR_DELETING_FILE_TITLE"         : "Nie można usunąć następującego pliku {0}",
    "ERROR_DELETING_FILE"               : "Wystąpił błąd przy próbie zmiany nazwy następującego pliku {2} <span class='dialog-filename'>{0}</span>. {1}",
    "INVALID_FILENAME_TITLE"            : "Nieprawidłowana nazwa pliku {0}",
    "INVALID_FILENAME_MESSAGE"          : "{0} Nie można używać żadnych słow zarezerwowanych przez system zakończonych kropkami (.) oraz żadnych z wymienonych: <code class='emphasized'>{1}</code>",
    "ENTRY_WITH_SAME_NAME_EXISTS"       : "Plik lub folder o podanej nazwie <span class='dialog-filename'>{0}</span> już istnieje.",
    "ERROR_CREATING_FILE_TITLE"         : "Nie można utworzyć pliku {0}",
    "ERROR_CREATING_FILE"               : "Wystąpił błąd przy próbie utworzenia pliku {0} <span class='dialog-filename'>{1}</span>. {2}",
    "ERROR_MIXED_DRAGDROP"              : "Nie można otworzyć folderu w czasie otwierania innego pliku.",

    // User key map error strings
    "ERROR_KEYMAP_TITLE"                : "Błąd podczas wczytywania niestandardowej mapy znaków",
    "ERROR_KEYMAP_CORRUPT"              : "Twój plik mapy znaków nie jest w poprawnym plikiem JSON. Plik zostanie otworzony w celu umożliwienia Ci poprawy błędów.",
    "ERROR_LOADING_KEYMAP"              : "Twój plik mapy znaków jest zakodowany w innym formacie niż UTF-8 prez co nie zostanie załadowany",
    "ERROR_RESTRICTED_COMMANDS"         : "Nie możesz ponownie przypisać skrótów do następujących komend: {0}",
    "ERROR_RESTRICTED_SHORTCUTS"        : "Nie możesz ponownie przypisać tych skrótów: {0}",
    "ERROR_MULTIPLE_SHORTCUTS"          : "Zostało utworzonych wiele skrótów do następujących komend: {0}",
    "ERROR_DUPLICATE_SHORTCUTS"         : "Następujące skróty mają zbyt wiele powiązań: {0}",
    "ERROR_INVALID_SHORTCUTS"           : "Ten skrót jest nieprawidłowy: {0}",
    "ERROR_NONEXISTENT_COMMANDS"        : "Następujące skróty zostały przypisane do niestniejących komend: {0}",

    // Application preferences corrupt error strings
    "ERROR_PREFS_CORRUPT_TITLE"         : "Błąd podczas odczytywania ustawień",
    "ERROR_PREFS_CORRUPT"               : "Tój plik ustawień nie jest prawidłowym plikiem JSON. Plik zostanie otworzony w celu umożliwienia Ci poprawy błędów. Musisz zrestartować {APP_NAME} aby zobaczyć efekt.",
    "ERROR_PROJ_PREFS_CORRUPT"          : "Twój plik ustawień projektu nie jest poprawnym plikiem JSON. Plik zostanie otworzony w celu umoeżliwienia Ci poprawy błędów. You will need to reload the project for the changes to take effect.",

    // Application error strings
    "ERROR_IN_BROWSER_TITLE"            : "Oops! {APP_NAME} jeszcze nie działa w przeglądarce.",
    "ERROR_IN_BROWSER"                  : "{APP_NAME} został napisany w HTML, jednak na razie działa jedynie jako samodzielna aplikacja. Możesz użyć jej do edycji plików na dysku. Aby uruchomić {APP_NAME} użyj aplikacji dostępnej w tym repozytorium <b>github.com/adobe/brackets-shell</b>.",

    // ProjectManager max files error string
    "ERROR_MAX_FILES_TITLE"             : "Błąd podczas indeksowana plików",
    "ERROR_MAX_FILES"                   : "Ten projekt zawiera więcej niż 30,000 plików. Funkcje operujące na wielu plikach mogą nie działać lub zachowywać się jak by prejekt był pusty. <a href='https://github.com/adobe/brackets/wiki/Large-Projects'>Przeczytaj aby dowiedzieć się więcej o pracy z dużymi projektami</a>.",

    // Live Preview error strings
    "ERROR_LAUNCHING_BROWSER_TITLE"     : "Błąd podczas uruchamiania przeglądarki",
    "ERROR_CANT_FIND_CHROME"            : "Nie znaleziono przeglądarki Google Chrome. Sprawdź czy jest zainstalowana.",
    "ERROR_LAUNCHING_BROWSER"           : "Wystąpił błąd podczas uruchamiania przeglądarki. (Błąd {0})",

    "LIVE_DEVELOPMENT_ERROR_TITLE"      : "Błąd podglądu na żywo",
    "LIVE_DEVELOPMENT_RELAUNCH_TITLE"   : "Łączenie z przeglądarką",
    "LIVE_DEVELOPMENT_ERROR_MESSAGE"    : "W celu włączenia błyskawicznego podglądu, Chrome musi zostać zrestartowany z włączonym zdalnym debugowaniem.<br /><br />Czy chcesz włączyć zdalne debugowanie i zrestartować Chrome?<br /><br />",
    "LIVE_DEV_LOADING_ERROR_MESSAGE"    : "Nie można załadować strony podglądu na żywo.",
    "LIVE_DEV_NEED_HTML_MESSAGE"        : "Otwórz plik HTMl lub upewnij się że nazywa się index.html aby uruchomić podglą na żywo.",
    "LIVE_DEV_NEED_BASEURL_MESSAGE"     : "Aby uruchomić podgląd na żywo z plików po stronie serwera, należy określić adres URL dla tego projektu.",
    "LIVE_DEV_SERVER_NOT_READY_MESSAGE" : "Błąd podczas uruchamiania serwera HTTP dla podglądu na żywo. Spróbuj uruchomić go ponownie.",
    "LIVE_DEVELOPMENT_INFO_TITLE"       : "Witaj w podglądzie na żywo!",
    "LIVE_DEVELOPMENT_INFO_MESSAGE"     : "Podgląd na żywo podłączył {APP_NAME} do twojej przeglądarki. Pokazuje on twoją stronę HTML bezpośrednio w&nbsp;przeglądarce, oraz aktualizuje ją natychmiast po wprowadzeniu zmian w&nbsp;kodzie.<br /><br />W aktualnej wersji {APP_NAME}, podgląd na żywo działa wyłącznie z&nbsp;<strong>Google Chrome</strong> i&nbsp;aktualizuje w czasie rzeczywistym <strong>pliki CSS</strong>. Zmiany w plikach HTML lub JavaScript są ładowane automatycznie po zapisaniu pliku.<br /><br />(Ta wiadomość wyświetla się tylko raz)",
    "LIVE_DEVELOPMENT_TROUBLESHOOTING"  : "Więcej informacji znajdziesz w tym dokumencie <a href='{0}' title='{0}'>Rozwiązywanie problemów z podglądem na żywo</a>.",

    "LIVE_DEV_STATUS_TIP_NOT_CONNECTED" : "Podgląd na żywo",
    "LIVE_DEV_STATUS_TIP_PROGRESS1"     : "Podgląd na żwyo: Łączenie\u2026",
    "LIVE_DEV_STATUS_TIP_PROGRESS2"     : "Podgląd na żywo: Uruchamianie\u2026",
    "LIVE_DEV_STATUS_TIP_CONNECTED"     : "Rozłącz z podglądem na żywo",
    "LIVE_DEV_STATUS_TIP_OUT_OF_SYNC"   : "Podgląd na żywo (Zapisz plik aby odświerzyć)",
    "LIVE_DEV_STATUS_TIP_SYNC_ERROR"    : "Podgląd na żywo (nie odświerzony z powodu błędu w składni)",

    "LIVE_DEV_DETACHED_REPLACED_WITH_DEVTOOLS" : "Podgląd na żywo został anulowany, ponieważ narzędzia deweloperskie przeglądarki były uruchomione",
    "LIVE_DEV_DETACHED_TARGET_CLOSED"          : "Podgląd na żywo został anulowany, ponieważ strona w przeglądarce została zamknięta",
    "LIVE_DEV_NAVIGATED_AWAY"                  : "Podglą na żywo został anulowany, ponieważ przeglądarka odwiedziłą link, który nie należy do aktualnego projektu",
    "LIVE_DEV_CLOSED_UNKNOWN_REASON"           : "Podgląd na żywo został anulowany z nieznanego powodu ({0})",

    "SAVE_CLOSE_TITLE"                  : "Zapisz zmiany",
    "SAVE_CLOSE_MESSAGE"                : "Czy chcesz zapisać zmiany w dokumencie <span class='dialog-filename'>{0}</span>?",
    "SAVE_CLOSE_MULTI_MESSAGE"          : "Czy chcesz zapisać zmiany w następujących plikach?",
    "EXT_MODIFIED_TITLE"                : "Zmiany zewnętrzne",
    "CONFIRM_FOLDER_DELETE_TITLE"       : "Potwierdź usunięcie",
    "CONFIRM_FOLDER_DELETE"             : "Jesteś pewien że chce usunąć folder <span class='dialog-filename'>{0}</span>?",
    "FILE_DELETED_TITLE"                : "Plik został usunięty",
    "EXT_MODIFIED_WARNING"              : "<span class='dialog-filename'>{0}</span> został zmodyfikowany na dysku poza {APP_NAME}.<br /><br />Czy chcesz nadpisać plik aktualie otwrtą wersją?",
    "EXT_MODIFIED_MESSAGE"              : "<span class='dialog-filename'>{0}</span> został zmodyfikowany na dysku poza {APP_NAME}, ale zawiera niezapisane zmiany w {APP_NAME}.<br /><br />Którą wersję chcesz zachować?",
    "EXT_DELETED_MESSAGE"               : "<span class='dialog-filename'>{0}</span> został usunięty z dysku poza {APP_NAME}, ale posiada niezapiane zmiany w {APP_NAME}.<br /><br />Czy chcesz zachować swoje zmieny?",

    // Generic dialog/button labels
    "DONE"                              : "Gotowe",
    "OK"                                : "OK",
    "CANCEL"                            : "Anuluj",
    "DONT_SAVE"                         : "Nie zapisuj",
    "SAVE"                              : "Zapisz",
    "SAVE_AS"                           : "Zapisz jako\u2026",
    "SAVE_AND_OVERWRITE"                : "Nadpisz",
    "DELETE"                            : "Usuń",
    "BUTTON_YES"                        : "Tak",
    "BUTTON_NO"                         : "Nie",

    // Find, Replace, Find in Files
    "FIND_MATCH_INDEX"                  : "{0} z {1}",
    "FIND_NO_RESULTS"                   : "Brak wyników",
    "FIND_QUERY_PLACEHOLDER"            : "Znajdź\u2026",
    "REPLACE_PLACEHOLDER"               : "Zmień na\u2026",
    "BUTTON_REPLACE_ALL"                : "Zmień wszystko\u2026",
    "BUTTON_REPLACE_ALL_IN_FILES"       : "Zmień wszystko w plikach\u2026",
    "BUTTON_REPLACE"                    : "Zmień",
    "BUTTON_NEXT"                       : "\u25B6",
    "BUTTON_PREV"                       : "\u25C0",
    "BUTTON_NEXT_HINT"                  : "Nasępny",
    "BUTTON_PREV_HINT"                  : "Poprzedni",
    "BUTTON_CASESENSITIVE_HINT"         : "Rozróżniaj wielkie i małe litery",
    "BUTTON_REGEXP_HINT"                : "Wyrażenie regularne",
    "REPLACE_WITHOUT_UNDO_WARNING_TITLE": "Zmiana bez cofania",
    "REPLACE_WITHOUT_UNDO_WARNING"      : "Ponieważ więcej niż {0} zostanie zmienionych, {APP_NAME} zmodyfikuje nieotworzone pliki na dysku.<br />Nie będziesz w stanie cofnąć zmian w tych plikach.",
    "BUTTON_REPLACE_WITHOUT_UNDO"       : "Zmień bez cofania",

    "OPEN_FILE"                         : "Otwórz plik",
    "SAVE_FILE_AS"                      : "Zapisz plik",
    "CHOOSE_FOLDER"                     : "Wybierz folder",

    "RELEASE_NOTES"                     : "Informacje o wydaniu",
    "NO_UPDATE_TITLE"                   : "Aktualny!",
    "NO_UPDATE_MESSAGE"                 : "Używasz najnowszej wersji {APP_NAME}.",

    // Find and Replace
    "FIND_REPLACE_TITLE_LABEL"          : "Zmień",
    "FIND_REPLACE_TITLE_WITH"           : "z",
    "FIND_TITLE_LABEL"                  : "Znaleziono",
    "FIND_TITLE_SUMMARY"                : "&mdash; {0} {1} {2} w {3}",

    // Find in Files
    "FIND_NUM_FILES"                    : "{0} {1}",
    "FIND_IN_FILES_SCOPED"              : "w <span class='dialog-filename'>{0}</span>",
    "FIND_IN_FILES_NO_SCOPE"            : "w projekcie",
    "FIND_IN_FILES_ZERO_FILES"          : "Filtr wyklucza wszystkie pliki {0}",
    "FIND_IN_FILES_FILE"                : "plik",
    "FIND_IN_FILES_FILES"               : "pliki",
    "FIND_IN_FILES_MATCH"               : "dopasowanie",
    "FIND_IN_FILES_MATCHES"             : "dopasowania",
    "FIND_IN_FILES_MORE_THAN"           : "Więcej niż ",
    "FIND_IN_FILES_PAGING"              : "{0}&mdash;{1}",
    "FIND_IN_FILES_FILE_PATH"           : "<span class='dialog-filename'>{0}</span> {2} <span class='dialog-path'>{1}</span>", // We should use normal dashes on Windows instead of em dash eventually
    "FIND_IN_FILES_EXPAND_COLLAPSE"     : "Użyj Ctrl/Cmd aby zwinąć lub rozwinąć wszystkie",
    "FIND_IN_FILES_INDEXING"            : "Indeksowanie dla błyskawicznego wyszukiwania\u2026",
    "REPLACE_IN_FILES_ERRORS_TITLE"     : "Błąd przy zmianie",
    "REPLACE_IN_FILES_ERRORS"           : "Następujące pliki nie mogły zostać zmodyfikowane ponieważ zostały zmienione przed wyszukiwaniem lub nie mogą zostać zapisane.",

    "ERROR_FETCHING_UPDATE_INFO_TITLE"  : "Błąd podczas pobierania informacji o aktualizacji",
    "ERROR_FETCHING_UPDATE_INFO_MSG"    : "Wystąpił problem podczas pobierania informacji o najnowszej wersji aplikacji. Upewnij się, że jesteś podłączony do Internetu i spróbuj ponownie.",

    // File exclusion filters
    "NEW_FILE_FILTER"                   : "Ustaw nowe wykluczenie\u2026",
    "CLEAR_FILE_FILTER"                 : "Nie wykluczaj plików",
    "NO_FILE_FILTER"                    : "Brak wykluczonych plików",
    "EXCLUDE_FILE_FILTER"               : "Wyklucz {0}",
    "EDIT_FILE_FILTER"                  : "Edytuj\u2026",
    "FILE_FILTER_DIALOG"                : "Edytuj wykluczenia",
    "FILE_FILTER_INSTRUCTIONS"          : "Możesz wykluczyć pliki o nazwach pasujących do poniższych wzorów lub <a href='{0}' title='{0}'>masek</a>. Każdą regułę umieść w osobnej linii.",
    "FILTER_NAME_PLACEHOLDER"           : "Nazwa wykluczenia (opcjonalnie)",
    "FILE_FILTER_CLIPPED_SUFFIX"        : "i {0} więcej",
    "FILTER_COUNTING_FILES"             : "Zliczanie plików\u2026",
    "FILTER_FILE_COUNT"                 : "Przeszukane zostanie {0} z {1} plików {2}",
    "FILTER_FILE_COUNT_ALL"             : "Przeszukane sotanie wszystkie {0} plików {1}",

    // Quick Edit
    "ERROR_QUICK_EDIT_PROVIDER_NOT_FOUND"   : "Nie można użyć szybkiej edycji w tym miejscu",
    "ERROR_CSSQUICKEDIT_BETWEENCLASSES"     : "Szybka edycja CSS: umieść kursor na nazwie klasy",
    "ERROR_CSSQUICKEDIT_CLASSNOTFOUND"      : "Szybka edycja CSS: nieprawidłowa klasa",
    "ERROR_CSSQUICKEDIT_IDNOTFOUND"         : "Szybka edycja CSS: nieprawidłowy identyfikator",
    "ERROR_CSSQUICKEDIT_UNSUPPORTEDATTR"    : "Szybka edycja CSS: umieść kursor na nazwie znacznika, klasy lub identyfikatora",
    "ERROR_TIMINGQUICKEDIT_INVALIDSYNTAX"   : "Szybka edycja CSS: nieprawidłowa składnia funkcji czasu",
    "ERROR_JSQUICKEDIT_FUNCTIONNOTFOUND"    : "Szybka edycja JS: umieść kursor na nazwie funkcji",

    // Quick Docs
    "ERROR_QUICK_DOCS_PROVIDER_NOT_FOUND"   : "Nie znaleziono dokumentacji dla bieżącego miejsca.",

    /**
     * ProjectManager
     */
    "PROJECT_LOADING"   : "Ładowanie\u2026",
    "UNTITLED"          : "Bez_nazwy",
    "WORKING_FILES"     : "Otwrte pliki",

    /**
     * MainViewManager
     */
    "TOP"               : "Góra",
    "BOTTOM"            : "Dół",
    "LEFT"              : "Lewo",
    "RIGHT"             : "Prawo",

    "CMD_SPLITVIEW_NONE"        : "Brak dzielenia",
    "CMD_SPLITVIEW_VERTICAL"    : "Dzielenie pionowe",
    "CMD_SPLITVIEW_HORIZONTAL"  : "Dzielenie poziome",
    "SPLITVIEW_MENU_TOOLTIP"    : "Podziel edytor pionowo lub poziomo",
    "GEAR_MENU_TOOLTIP"         : "Konfiguruj obszar roboczy",

    "SPLITVIEW_INFO_TITLE"              : "Już Otworzony",
    "SPLITVIEW_MULTIPANE_WARNING"       : "Plik jest już otwrty w innym panelu. {APP_NAME} wkrótce będzie obsługiwał otwieranie tego samego pliku w kilku panelach. Do tego czasu, plik zostanie wyświetlony w panelu w którym jest otworzony.<br /><br />(Zobaczysz tą wiadomość tylko raz.)",

    /**
     * Keyboard modifiers and special key names
     */
    "KEYBOARD_CTRL"         : "Ctrl",
    "KEYBOARD_SHIFT"        : "Shift",
    "KEYBOARD_SPACE"        : "SPacja",
    "KEYBOARD_PAGE_UP"      : "Page Up",
    "KEYBOARD_PAGE_DOWN"    : "Page Down",
    "KEYBOARD_HOME"         : "Home",
    "KEYBOARD_END"          : "End",
    "KEYBOARD_INSERT"       : "Insert",
    "KEYBOARD_DELETE"       : "Delete",

    /**
     * StatusBar strings
     */
    "STATUSBAR_CURSOR_POSITION"             : "Linia {0}, Kolumna {1}",
    "STATUSBAR_SELECTION_CH_SINGULAR"       : " \u2014 Zaznaczono {0} kolumnę",
    "STATUSBAR_SELECTION_CH_PLURAL"         : " \u2014 Zaznaczono {0} kolumn(y)",
    "STATUSBAR_SELECTION_LINE_SINGULAR"     : " \u2014 Zaznaczono {0} linie",
    "STATUSBAR_SELECTION_LINE_PLURAL"       : " \u2014 Zaznaczono {0} linii",
    "STATUSBAR_SELECTION_MULTIPLE"          : " \u2014 {0} zaznaczeń",
    "STATUSBAR_INDENT_TOOLTIP_SPACES"       : "Kliknij, by zmienić wcięcia na spacje.",
    "STATUSBAR_INDENT_TOOLTIP_TABS"         : "Kliknij, by zmienić wcięcia na tabulacje.",
    "STATUSBAR_INDENT_SIZE_TOOLTIP_SPACES"  : "Kliknij, by zmienić ilość spacji we wcięciach",
    "STATUSBAR_INDENT_SIZE_TOOLTIP_TABS"    : "Kliknij, by zmienić szerokość tabulacji.",
    "STATUSBAR_SPACES"                      : "Spacje:",
    "STATUSBAR_TAB_SIZE"                    : "Tabulacje:",
    "STATUSBAR_LINE_COUNT_SINGULAR"         : "\u2014 {0} Linia",
    "STATUSBAR_LINE_COUNT_PLURAL"           : "\u2014 {0} Linii",
    "STATUSBAR_USER_EXTENSIONS_DISABLED"    : "Rozszerzenia wyłączone",
    "STATUSBAR_INSERT"                      : "WST",
    "STATUSBAR_OVERWRITE"                   : "ZAS",
    "STATUSBAR_INSOVR_TOOLTIP"              : "Kliknij aby zmienić kursor pomiędzy wprowadzeniami (WST) i zastąpić (ZAS) trybami",
    "STATUSBAR_LANG_TOOLTIP"                : "Kliknij aby zmienić typ pliku",
    "STATUSBAR_CODE_INSPECTION_TOOLTIP"     : "{0}. Kliknij aby przłączyć panel zgłoszeń.",
    "STATUSBAR_DEFAULT_LANG"                : "(domyślnie)",
    "STATUSBAR_SET_DEFAULT_LANG"            : "Ustaw domyślnie dla .{0} Plików",

    // CodeInspection: errors/warnings
    "ERRORS_PANEL_TITLE_MULTIPLE"           : "{0} Problemów",
    "SINGLE_ERROR"                          : "1 błąd {0}",
    "MULTIPLE_ERRORS"                       : "{1} błędów {0} ",
    "NO_ERRORS"                             : "Brak {0} znalezionych błędów - Dobra robota!",
    "NO_ERRORS_MULTIPLE_PROVIDER"           : "Nie znaleziono błędów - Dobra robota!",
    "LINT_DISABLED"                         : "Sprawdzanie poprawnośći jest wyłączone",
    "NO_LINT_AVAILABLE"                     : "Sprawdzanie poprawności nie jest dostępne dla {0}",
    "NOTHING_TO_LINT"                       : "Brak plików do sprawdzenia",
    "LINTER_TIMED_OUT"                      : "{0} upłynął limit czasu {1} ms",
    "LINTER_FAILED"                         : "{0} zakończył z błędem: {1}",

    /**
     * Command Name Constants
     */

    // File menu commands
    "FILE_MENU"                           : "Plik",
    "CMD_FILE_NEW_UNTITLED"               : "Nowy",
    "CMD_FILE_NEW"                        : "Nowy Plik",
    "CMD_FILE_NEW_FOLDER"                 : "Nowy Folder",
    "CMD_FILE_OPEN"                       : "Otwórz\u2026",
    "CMD_ADD_TO_WORKING_SET"              : "Otwórz jako nowy projekt",
    "CMD_OPEN_DROPPED_FILES"              : "Otwórz przeciągnięte pliki",
    "CMD_OPEN_FOLDER"                     : "Otórz Folder\u2026",
    "CMD_FILE_CLOSE"                      : "Zamknij",
    "CMD_FILE_CLOSE_ALL"                  : "Zamknij wszystko",
    "CMD_FILE_CLOSE_LIST"                 : "Zamknij listę",
    "CMD_FILE_CLOSE_OTHERS"               : "Zamknij inne",
    "CMD_FILE_CLOSE_ABOVE"                : "Zamknij inne powyżej",
    "CMD_FILE_CLOSE_BELOW"                : "Zamknij inne poniżej",
    "CMD_FILE_SAVE"                       : "Zapisz",
    "CMD_FILE_SAVE_ALL"                   : "Zapisz wszystko",
    "CMD_FILE_SAVE_AS"                    : "Zapisz jako\u2026",
    "CMD_LIVE_FILE_PREVIEW"               : "Podgląd na żywo",
    "CMD_TOGGLE_LIVE_PREVIEW_MB_MODE"     : "Włącz podgląd na żywo (Wersja rozwojowa)",
    "CMD_RELOAD_LIVE_PREVIEW"             : "Przeładuj podgląd na żywo",
    "CMD_PROJECT_SETTINGS"                : "Ustawienia projektu\u2026",
    "CMD_FILE_RENAME"                     : "Zmień Nazwę",
    "CMD_FILE_DELETE"                     : "Usuń",
    "CMD_INSTALL_EXTENSION"               : "Zainstaluj Rozszerzenie\u2026",
    "CMD_EXTENSION_MANAGER"               : "Menadżer Rozszerzeń\u2026",
    "CMD_FILE_REFRESH"                    : "Odświerz drzewo plików",
    "CMD_QUIT"                            : "Wyjdź",
    // Used in native File menu on Windows
    "CMD_EXIT"                            : "Wyjdź",

    // Edit menu commands
    "EDIT_MENU"                           : "Edytuj",
    "CMD_UNDO"                            : "Cofnij",
    "CMD_REDO"                            : "Ponów",
    "CMD_CUT"                             : "Wytnij",
    "CMD_COPY"                            : "Kopiuj",
    "CMD_PASTE"                           : "Wklej",
    "CMD_SELECT_ALL"                      : "Zaznacz wszystko",
    "CMD_SELECT_LINE"                     : "Zaznacz jedną linię",
    "CMD_SPLIT_SEL_INTO_LINES"            : "Podziel zaznaczenie na linie",
    "CMD_ADD_CUR_TO_NEXT_LINE"            : "Rozszerz kursor na następną linię",
    "CMD_ADD_CUR_TO_PREV_LINE"            : "Rozszerz kursor na poprzednią linię",
    "CMD_INDENT"                          : "Zwiększ wcięcie",
    "CMD_UNINDENT"                        : "Zmniejsz wcięcie",
    "CMD_DUPLICATE"                       : "Powiel",
    "CMD_DELETE_LINES"                    : "Usuń linię",
    "CMD_COMMENT"                         : "Wstaw komentarz liniowy",
    "CMD_BLOCK_COMMENT"                   : "Wstaw komentarz blokowy",
    "CMD_LINE_UP"                         : "Przenieś linię wyżej",
    "CMD_LINE_DOWN"                       : "Przenieś linię niżej",
    "CMD_OPEN_LINE_ABOVE"                 : "Otwóz linię wyżej (?)",
    "CMD_OPEN_LINE_BELOW"                 : "Otwóz linię poniżej (?)",
    "CMD_TOGGLE_CLOSE_BRACKETS"           : "Automatyczne zamykanie klamr",
    "CMD_SHOW_CODE_HINTS"                 : "Pokaż podpowiedzi",

    // Search menu commands
    "FIND_MENU"                           : "Wyszukiwanie",
    "CMD_FIND"                            : "Znajdż",
    "CMD_FIND_NEXT"                       : "Znajdź następny",
    "CMD_FIND_PREVIOUS"                   : "Znajdź poprzedni",
    "CMD_FIND_ALL_AND_SELECT"             : "Znajdź wszystkie i zaznacz",
    "CMD_ADD_NEXT_MATCH"                  : "Dodaj następny do zaznaczenia",
    "CMD_SKIP_CURRENT_MATCH"              : "Pomiń i dodaj następny",
    "CMD_FIND_IN_FILES"                   : "Znajdź w plikach",
    "CMD_FIND_IN_SUBTREE"                 : "Znajdź w\u2026",
    "CMD_REPLACE"                         : "Zamień",
    "CMD_REPLACE_IN_FILES"                : "Zamień w plikach",
    "CMD_REPLACE_IN_SUBTREE"              : "Zamień w\u2026",

    // View menu commands
    "VIEW_MENU"                           : "Widok",
    "CMD_HIDE_SIDEBAR"                    : "Ukryj pasek boczny",
    "CMD_SHOW_SIDEBAR"                    : "SPokaż pasek boczny",
    "CMD_TOGGLE_SIDEBAR"                  : "Przełącz pasek boczny",
    "CMD_TOGGLE_PANELS"                   : "Przełącz panele",
    "CMD_TOGGLE_PURE_CODE"                : "Czysty kod",
    "CMD_INCREASE_FONT_SIZE"              : "Powiększ czcionkę",
    "CMD_DECREASE_FONT_SIZE"              : "Zmniejsz czcionkę",
    "CMD_RESTORE_FONT_SIZE"               : "Przywróć domyślny rozmiar czcionki",
    "CMD_SCROLL_LINE_UP"                  : "Przewiń linię wyżej",
    "CMD_SCROLL_LINE_DOWN"                : "Przewiń linię niżej",
    "CMD_TOGGLE_LINE_NUMBERS"             : "Wyświetlaj numery linii",
    "CMD_TOGGLE_ACTIVE_LINE"              : "Podświetlenie bierzącej linii",
    "CMD_TOGGLE_WORD_WRAP"                : "Zawijanie wierszy",
    "CMD_LIVE_HIGHLIGHT"                  : "Podświetlenie przy podglądzie na żywo",
    "CMD_VIEW_TOGGLE_INSPECTION"          : "Sprawdzaj poprawność przy zapisywaniu",
    "CMD_WORKINGSET_SORT_BY_ADDED"        : "Sortuj według dodanych",
    "CMD_WORKINGSET_SORT_BY_NAME"         : "Sortuj według nazwy",
    "CMD_WORKINGSET_SORT_BY_TYPE"         : "Sortuj według typu",
    "CMD_WORKING_SORT_TOGGLE_AUTO"        : "Automatyczne sortowanie",
    "CMD_THEMES"                          : "Motywy\u2026",

    // Navigate menu commands
    "NAVIGATE_MENU"                       : "Nawigacja",
    "CMD_QUICK_OPEN"                      : "Szybkie otwieranie",
    "CMD_GOTO_LINE"                       : "Idź do linii",
    "CMD_GOTO_DEFINITION"                 : "Idź do definicji",
    "CMD_GOTO_FIRST_PROBLEM"              : "Idź do pierwszego błędu",
    "CMD_TOGGLE_QUICK_EDIT"               : "Szybka edycja",
    "CMD_TOGGLE_QUICK_DOCS"               : "Szybka dokumentacja",
    "CMD_QUICK_EDIT_PREV_MATCH"           : "Poprzedni wynik",
    "CMD_QUICK_EDIT_NEXT_MATCH"           : "Następny wynik",
    "CMD_CSS_QUICK_EDIT_NEW_RULE"         : "Nowa reguła",
    "CMD_NEXT_DOC"                        : "Następny dokument",
    "CMD_PREV_DOC"                        : "Poprzedni dokument",
    "CMD_NEXT_DOC_LIST_ORDER"             : "Następny dokument z listy",
    "CMD_PREV_DOC_LIST_ORDER"             : "Poprzedni dokument z listy",
    "CMD_SHOW_IN_TREE"                    : "Pokarz w drzewie katalogów",
    "CMD_SHOW_IN_EXPLORER"                : "Pokarz w Eksloratorze",
    "CMD_SHOW_IN_FINDER"                  : "Pokaż w wyszukiwarce (?)",
    "CMD_SHOW_IN_OS"                      : "Pokaż w systemie plików",

    // Help menu commands
    "HELP_MENU"                           : "Pomoc",
    "CMD_CHECK_FOR_UPDATE"                : "Sprawdź aktualizacje",
    "CMD_HOW_TO_USE_BRACKETS"             : "Jak używać {APP_NAME}",
    "CMD_SUPPORT"                         : "Wsparcie {APP_NAME}",
    "CMD_SUGGEST"                         : "Zaproponuj funkcję",
    "CMD_RELEASE_NOTES"                   : "Informacje o wydaniu",
    "CMD_GET_INVOLVED"                    : "Zangażuj się",
    "CMD_SHOW_EXTENSIONS_FOLDER"          : "Pokaż folder rozszerzeń",
    "CMD_HEALTH_DATA_STATISTICS"          : "Raport zdrowia",
    "CMD_HOMEPAGE"                        : "Strona o {APP_TITLE}",
    "CMD_TWITTER"                         : "{TWITTER_NAME} na Twitterze",
    "CMD_ABOUT"                           : "O {APP_TITLE}",
    "CMD_OPEN_PREFERENCES"                : "Otwórz plik konfiguracyjny",
    "CMD_OPEN_KEYMAP"                     : "Otórz swoją konfigurację klawiatury",

    // Strings for main-view.html
    "EXPERIMENTAL_BUILD"                   : "wersja eksperymentalna",
    "RELEASE_BUILD"                        : "kompilacja",
    "DEVELOPMENT_BUILD"                    : "wersja rozwojowa",
    "RELOAD_FROM_DISK"                     : "Załduj ponownie z dysku",
    "KEEP_CHANGES_IN_EDITOR"               : "Zachowuj zmiany w edytorze",
    "CLOSE_DONT_SAVE"                      : "Zamknij (Bez zapisywania)",
    "RELAUNCH_CHROME"                      : "Zrestartuj Chrome",
    "ABOUT"                                : "O programie",
    "CLOSE"                                : "Zamknij",
    "ABOUT_TEXT_LINE1"                     : "Wydanie {VERSION_MAJOR}.{VERSION_MINOR} {BUILD_TYPE} {VERSION}",
    "ABOUT_TEXT_BUILD_TIMESTAMP"           : "Czas kompilacji (timestamp): ",
    "ABOUT_TEXT_LINE3"                     : "Adnotacje dotyczące warunków używania aplikacji firm trzecich znajdują się tutaj: <a href='{ADOBE_THIRD_PARTY}'>{ADOBE_THIRD_PARTY}</a> i zostały załączone jako odnośnik.",
    "ABOUT_TEXT_LINE4"                     : "Dokumentacja i pliki żródłowe dostępne po adresem: <a href='https://github.com/adobe/brackets/'>https://github.com/adobe/brackets/</a>",
    "ABOUT_TEXT_LINE5"                     : "Wykonali z \u2764 i JavaScript:",
    "ABOUT_TEXT_LINE6"                     : "nóstwo ludzi (niestety mamy problem z załadowaniem pełnej listy w tym momencie).",
    "ABOUT_TEXT_WEB_PLATFORM_DOCS"         : "Dokumentacja Web Platform oraz logo Web Platform są rozpowszechniane na zasadach licencji Creative Commons Attribution, <a href='{WEB_PLATFORM_DOCS_LICENSE}'>CC-BY 3.0 Unported</a>.",
    "UPDATE_NOTIFICATION_TOOLTIP"          : "Dostępna jest nowa wersja aplikacji {APP_NAME}! Kliknij by dowiedzieć się więcej.",
    "UPDATE_AVAILABLE_TITLE"               : "Dostępna jest nowa wersja programu",
    "UPDATE_MESSAGE"                       : "Dostępna jest nowa wersja aplikacji {APP_NAME}. Oto kilka nowości w tej wersji:",
    "GET_IT_NOW"                           : "Pobierz teraz!",
    "PROJECT_SETTINGS_TITLE"               : "Ustawienia projektu: {0}",
    "PROJECT_SETTING_BASE_URL"             : "Adres podglądu na żywo",
    "PROJECT_SETTING_BASE_URL_HINT"        : "Aby używać lokalnego serwera podaj adres URL np. http://localhost:8000/",
    "BASEURL_ERROR_INVALID_PROTOCOL"       : "Protokół {0} nie jest wspierany przez podgląd na żywo&mdash;proszę użyć http: lub https: .",
    "BASEURL_ERROR_SEARCH_DISALLOWED"      : "Adres URL nie może zawierać parametrów wyszukiwania takich jak \"{0}\".",
    "BASEURL_ERROR_HASH_DISALLOWED"        : "Adres URL nie może zawierać znaku hash: \"{0}\".",
    "BASEURL_ERROR_INVALID_CHAR"           : "Znaki specjalne takie jak '{0}' muszą zostać %-zakodowane.",
    "BASEURL_ERROR_UNKNOWN_ERROR"          : "Nieznany błąd podczas parsowania adresu URL.",

    // Strings for Pane.js
    "EMPTY_VIEW_HEADER"                    : "<em>Otwórz plik kiedy panel będzie podświetlony</em>",
    "FLIPVIEW_BTN_TOOLTIP"                 : "Przenieś ten widok do {0} panelu",

    // Strings for themes-settings.html and themes-general.html
    "CURRENT_THEME"                        : "Używany motyw",
    "USE_THEME_SCROLLBARS"                 : "Użyj pasków przewijania z motywu",
    "FONT_SIZE"                            : "Wielkość czcionki",
    "FONT_FAMILY"                          : "Rodzina czcionek",
    "THEMES_SETTINGS"                      : "Ustawienia motywi",

    // CSS Quick Edit
    "BUTTON_NEW_RULE"                      : "Nowa reguła",

    // Extension Management strings
    "INSTALL"                              : "Zainstaluj",
    "UPDATE"                               : "Aktualizuj",
    "REMOVE"                               : "Usuń",
    "DISABLE"                              : "Wyłącz",
    "ENABLE"                               : "Włącz",
    "OVERWRITE"                            : "Nadpisz",
    "CANT_REMOVE_DEV"                      : "Rozszerzenia z folderu \"dev\" muszą być usunięte ręcznie.",
    "CANT_UPDATE"                          : "Ta aktualizacja nie jest kompatybilna z tą wersją {APP_NAME}.",
    "CANT_UPDATE_DEV"                      : "Rozszerzenia z folderu \"dev\" nie mogą być aktualizowane automatycznie.",
    "INSTALL_EXTENSION_TITLE"              : "Zainstaluj rozszerzenie",
    "UPDATE_EXTENSION_TITLE"               : "Aktualizuj rozszerzenie",
    "INSTALL_EXTENSION_LABEL"              : "Adres URL rozszerzenia",
    "INSTALL_EXTENSION_HINT"               : "Adres URL do pliku ZIP lub repozytorium na GitHub dla rozszerzenia",
    "INSTALLING_FROM"                      : "Zainstaluj rozszerzenie z {0}\u2026",
    "INSTALL_SUCCEEDED"                    : "Instalacja zkończona sukcesem!",
    "INSTALL_FAILED"                       : "Instalacja nie powiodła się.",
    "CANCELING_INSTALL"                    : "Anulowanie\u2026",
    "CANCELING_HUNG"                       : "Anulowanie instalacji trwa zbyt długo. Możliwe, że wystąpił błąd wewnętrzny.",
    "INSTALL_CANCELED"                     : "Instalacja anulowana.",
    "VIEW_COMPLETE_DESCRIPTION"            : "Zobacz pełen opis",
    "VIEW_TRUNCATED_DESCRIPTION"           : "Zobacz skrócony opis",
    // These must match the error codes in ExtensionsDomain.Errors.* :
    "INVALID_ZIP_FILE"                     : "Pobrany plik nie jest prawidłowym plikiem ZIP.",
    "INVALID_PACKAGE_JSON"                 : "Plik package.json jest nieprawidłowy (Wystąpił błąd: {0}).",
    "MISSING_PACKAGE_NAME"                 : "Plik package.json nie zawiera nazwy pakietu.",
    "BAD_PACKAGE_NAME"                     : "{0} jest nieprawidłową nazwą pakietu.",
    "MISSING_PACKAGE_VERSION"              : "Plik package.json nie zawiera wersji pakietu.",
    "INVALID_VERSION_NUMBER"               : "Numer wersji pakietu ({0}) jest nieprawidłowy.",
    "INVALID_BRACKETS_VERSION"             : "Ciąg kompatybilności z {APP_NAME} ({0}) jest nieprawidłowy.",
    "DISALLOWED_WORDS"                     : "Słowo „{1}” jest niedozwolony w polu {0}.",
    "API_NOT_COMPATIBLE"                   : "Rozszerzenie nie jest kompatybilne z tą wersją {APP_NAME}. Rozszerzenie zostanie zainstalowane w folderze rozszerzeń nieaktywnych.",
    "MISSING_MAIN"                         : "Pakiet nie zawiera pliku main.js.",
    "EXTENSION_ALREADY_INSTALLED"          : "Instalowanie tego rozszerzenia nadpisze poprzednio zainstalowany pakiet - kontynuować?",
    "EXTENSION_SAME_VERSION"               : "To rozszerzenie jest w tej samej wersji jak obecnie zainstalowane – nadpisać?",
    "EXTENSION_OLDER_VERSION"              : "To rozszerzenie jest w starszej wersji {0} – ({1}) - zaktualizować?",
    "DOWNLOAD_ID_IN_USE"                   : "Błąd wewnętrzny: taki plik już istnieje.",
    "NO_SERVER_RESPONSE"                   : "Nie można połączyć z serwerem.",
    "BAD_HTTP_STATUS"                      : "Nie znaleziono pliku na serwerze (HTTP {0}).",
    "CANNOT_WRITE_TEMP"                    : "Nie można zapisać pobranego pliku w folderze tymczasowym.",
    "ERROR_LOADING"                        : "Rozszerzenie napotkało błąd podczas startu.",
    "MALFORMED_URL"                        : "Niepoprawny adres URL, sprawdź to.",
    "UNSUPPORTED_PROTOCOL"                 : "Adres URL musi zaczynać się od http lub https.",
    "UNKNOWN_ERROR"                        : "Nieznany błąd wewnętrzny.",
    // For NOT_FOUND_ERR, see generic strings above
    "EXTENSION_MANAGER_TITLE"              : "Menedżer rozszerzeń",
    "EXTENSION_MANAGER_ERROR_LOAD"         : "Nie udało się dostać do rejestru rozszerzeń.",
    "INSTALL_EXTENSION_DRAG"               : "Przeciągnij plik .zip tutaj lub",
    "INSTALL_EXTENSION_DROP"               : "Przeciągnij plik .zip aby zainstalować",
    "INSTALL_EXTENSION_DROP_ERROR"         : "Instalacja/Aktualizacja przerwana z następującymi błędami:",
    "INSTALL_FROM_URL"                     : "Zainstaluj z adresu\u2026",
    "INSTALL_EXTENSION_VALIDATING"         : "Sprawdzanie\u2026",
    "EXTENSION_AUTHOR"                     : "Autor",
    "EXTENSION_DATE"                       : "Data",
    "EXTENSION_INCOMPATIBLE_NEWER"         : "To rozszerzenie wymaga nowszej wersji {APP_NAME}.",
    "EXTENSION_INCOMPATIBLE_OLDER"         : "To rozszerzenie działa tylko ze starszą wersją {APP_NAME}.",
    "EXTENSION_LATEST_INCOMPATIBLE_NEWER"  : "Wersja {0} wymaga nowszej wersji {APP_NAME}, ale możesz zainstalować starszą wersję rozszerzenia - {1}.",
    "EXTENSION_LATEST_INCOMPATIBLE_OLDER"  : "Wersja {0} wymaga starszej wersji {APP_NAME}, ale możesz zainstalować wcześniejszą wersję - {1}.",
    "EXTENSION_NO_DESCRIPTION"             : "Brak opisu",
    "EXTENSION_MORE_INFO"                  : "Więcej informacji\u2026",
    "EXTENSION_ERROR"                      : "Błąd rozszerzenia",
    "EXTENSION_KEYWORDS"                   : "Słowa kluczowe",
    "EXTENSION_TRANSLATED_USER_LANG"       : "Przetłumaczono na {0} język, włączając w to Ciebie",
    "EXTENSION_TRANSLATED_GENERAL"         : "Przetłumaczono na {0} język",
    "EXTENSION_TRANSLATED_LANGS"           : "To rozszerzenie zostało przetłumaczone na: {0}",
    "EXTENSION_INSTALLED"                  : "Zainstalowano",
    "EXTENSION_UPDATE_INSTALLED"           : "Aktualizacja tego rozszerzenie zostanie pobrana i zainstalowana po restarcie {APP_NAME}.",
    "EXTENSION_SEARCH_PLACEHOLDER"         : "Wyszukaj",
    "EXTENSION_MORE_INFO_LINK"             : "Więcej",
    "BROWSE_EXTENSIONS"                    : "Przeglądaj rozszerzenia",
    "EXTENSION_MANAGER_REMOVE"             : "Usuń rozszerzenie",
    "EXTENSION_MANAGER_REMOVE_ERROR"       : "Nie można usunąć jednego lub więcej rozszerzeń: {0}. {APP_NAME} zostanie przełądowany.",
    "EXTENSION_MANAGER_UPDATE"             : "Aktualizuj rozszerzenie",
    "EXTENSION_MANAGER_UPDATE_ERROR"       : "Nie można zaktualizować jednego lub więcej rozszerzeń: {0}. {APP_NAME} zostanie przeładowany.",
    "EXTENSION_MANAGER_DISABLE"            : "Wyłącz rozszerzenie",
    "EXTENSION_MANAGER_DISABLE_ERROR"      : "Nie można wyłączyć jednego lub więcej rozszerzeń: {0}. {APP_NAME} zostanie przeładowany.",
    "MARKED_FOR_REMOVAL"                   : "Zaznaczono do usunięcia",
    "UNDO_REMOVE"                          : "Confnij",
    "MARKED_FOR_UPDATE"                    : "MZaznaczono do aktualizacji",
    "UNDO_UPDATE"                          : "Confnij",
    "MARKED_FOR_DISABLING"                 : "Zaznaczono do wyłączenia",
    "UNDO_DISABLE"                         : "Confnij",
    "CHANGE_AND_RELOAD_TITLE"              : "Aktualizacja rozszerzeń",
    "CHANGE_AND_RELOAD_MESSAGE"            : "Aby zaktualizować, usunąć lub wyłączyć zaznaczone rozszerzenia, {APP_NAME} musi zostać zrestartowany. Zostaniesz powiadomienie aby zapisać niezapisane zmiany.",
    "REMOVE_AND_RELOAD"                    : "Usuń u zrestartuj",
    "CHANGE_AND_RELOAD"                    : "Zmień i zrestartuj",
    "UPDATE_AND_RELOAD"                    : "Zaktualizuj i zrestartuj",
    "DISABLE_AND_RELOAD"                   : "Wyłacz i zrestartuj",
    "PROCESSING_EXTENSIONS"                : "Przetwarzanie\u2026",
    "EXTENSION_NOT_INSTALLED"              : "Nie można usunąć rozszerzenia {0} ponieważ nie jest zainstalowane.",
    "NO_EXTENSIONS"                        : "Nie masz jeszcze żadnych rozszerzeń.<br>Użyj zakładki \"Dostępne\" aby sprawdzić rozszerzenia.",
    "NO_EXTENSION_MATCHES"                 : "Nie znaleziono żadnych pasujących rozszerzeń.",
    "REGISTRY_SANITY_CHECK_WARNING"        : "Bądź ostrożny, instalując rozszerzenia z nieznanych źródeł możesz narazić się na niestabilność programu.",
    "EXTENSIONS_INSTALLED_TITLE"           : "Zainstalowano",
    "EXTENSIONS_AVAILABLE_TITLE"           : "Dostępne",
    "EXTENSIONS_THEMES_TITLE"              : "Motywy",
    "EXTENSIONS_UPDATES_TITLE"             : "Aktualizacje",

    "INLINE_EDITOR_NO_MATCHES"             : "Brak wyników.",
    "INLINE_EDITOR_HIDDEN_MATCHES"         : "Wszystkie wyniki są zwiniętę. rozwiń pliki z prawej strony aby zobaczyć wyniki.",
    "CSS_QUICK_EDIT_NO_MATCHES"            : "Brak reguł.<br> Kliknij \"Nowa Reguła\", aby utworzyć regułę.",
    "CSS_QUICK_EDIT_NO_STYLESHEETS"        : "Brak arkuszy stylów w tym projekcie.<br>Stwórz jakiś aby dodać reguły CSS.",

    // Custom Viewers
    "IMAGE_VIEWER_LARGEST_ICON"            : "największy",

    /**
     * Unit names
     */
    "UNIT_PIXELS"                          : "pikseli",

    // extensions/default/DebugCommands
    "DEBUG_MENU"                                : "Debuguj",
    "ERRORS"                                    : "Błędy",
    "CMD_SHOW_DEV_TOOLS"                        : "Pkaż narzędzia deweloperskie",
    "CMD_REFRESH_WINDOW"                        : "Uruchom ponownie z obsługą rozszerzeń",
    "CMD_RELOAD_WITHOUT_USER_EXTS"              : "Uruchom ponownie bez obsługi rozszerzeń",
    "CMD_NEW_BRACKETS_WINDOW"                   : "Otwórz nowe okno {APP_NAME}",
    "CMD_LAUNCH_SCRIPT_MAC"                     : "Zainstaluj skrót linii komend",
    "CMD_SWITCH_LANGUAGE"                       : "Zmień język",
    "CMD_RUN_UNIT_TESTS"                        : "Uruchom testy",
    "CMD_SHOW_PERF_DATA"                        : "Pokaż informacje o wydajności",
    "CMD_ENABLE_NODE_DEBUGGER"                  : "Włącz debugger",
    "CMD_LOG_NODE_STATE"                        : "Wyświetl błędy do konsoli",
    "CMD_RESTART_NODE"                          : "Restartuj debugger",
    "CMD_SHOW_ERRORS_IN_STATUS_BAR"             : "Pokaż błędy w pasku stanu",
    "CMD_OPEN_BRACKETS_SOURCE"                  : "Otwórz kod źródłowy {APP_NAME}",

    "CREATING_LAUNCH_SCRIPT_TITLE"              : "Konsola {APP_NAME}",
    "ERROR_CREATING_LAUNCH_SCRIPT"              : "Wystąpił błąd przy instalacji skrótu linii poleceń. Spróbuj <a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments#troubleshooting'>tych sugestii co do rozwiązywanie problemów</a>.<br/><br/>Powód: {0}",
    "ERROR_CLTOOLS_RMFAILED"                    : "Nie można usunąć istnejących <code>/usr/local/bin/brackets</code> odnośników.",
    "ERROR_CLTOOLS_MKDIRFAILED"                 : "Nie można utworzyć folderu <code>/usr/local/bin</code>.",
    "ERROR_CLTOOLS_LNFAILED"                    : "Nie można utworzyć odnośnika <code>/usr/local/bin/brackets</code>.",
    "ERROR_CLTOOLS_SERVFAILED"                  : "Błąd wewnętrzny.",
    "ERROR_CLTOOLS_NOTSUPPORTED"                : "Skrót linii poleceń nie jest dostępny w tym systemie.",
    "LAUNCH_SCRIPT_CREATE_SUCCESS"              : "Powodzenie! Teraz możesz łątwo uruchomić {APP_NAME} z linii poleceń: <code>brackets myFile.txt</code> aby otworzyć plik lub <code>brackets myFolder</code> aby zmienić projekt. <br/><br/><a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments'>Przeczytaj więcej<a> o używaniu {APP_NAME} z linii poleceń.",

    "LANGUAGE_TITLE"                            : "Zmień język",
    "LANGUAGE_MESSAGE"                          : "Język:",
    "LANGUAGE_SUBMIT"                           : "Przełąduj {APP_NAME}",
    "LANGUAGE_CANCEL"                           : "Anuluj",
    "LANGUAGE_SYSTEM_DEFAULT"                   : "Domyślny język",

    // extensions/default/HealthData
    "HEALTH_DATA_NOTIFICATION"                  : "Ustawienia raportu życia",
    "HEALTH_FIRST_POPUP_TITLE"                  : "{APP_NAME} raport życia",
    "HEALTH_DATA_DO_TRACK"                      : "Wysyłaj anonimowe informacje o {APP_NAME}",
    "HEALTH_DATA_NOTIFICATION_MESSAGE"          : "W celu poprawy {APP_NAME}, okresowo wyła, <strong>anonimowe</strong> statystyki do Adobe o działaniu {APP_NAME}. Informacje te pomagają w naprawie błędów, poprawie stabilności oraz przy tworzeniu nowych funkcji.<br><br>Możesz zobaczyć wysyłane dane lub je wyłączyć przechodząc do <strong>Pomoc > Raport życia</strong>.<br><br><a href='https://github.com/adobe/brackets/wiki/Health-Data'>Przeczytaj więcej na temat raportu życia {APP_NAME}</a>",
    "HEALTH_DATA_PREVIEW"                       : "{APP_NAME} raport życia",
    "HEALTH_DATA_PREVIEW_INTRO"                 : "<p>W celu poprawy {APP_NAME}, okresowo wysyła, <strong>anonimowe</strong> statystyki do Adobe o działaniu {APP_NAME}. Informacje te pomagają w naprawie błędów, poprawie stabilności oraz przy tworzeniu nowych funkcji. <a href='https://github.com/adobe/brackets/wiki/Health-Data'>Przeczytaj więcej o raporcie życia {APP_NAME}</a> I jakie daje to kożyści społeczności {APP_NAME} jedncześnie chroniąc twoją prywatność.</p><p>Ponożej znajduje się podgląd informacji jakie zostaną wysłane w następnym raporcie życia <em>jeśli</em> jest włączony.</p>",

    // extensions/default/InlineTimingFunctionEditor
    "INLINE_TIMING_EDITOR_TIME"                 : "Czas",
    "INLINE_TIMING_EDITOR_PROGRESSION"          : "Postęp",
    "BEZIER_EDITOR_INFO"                        : "<<kbd>↑</kbd><kbd>↓</kbd><kbd>←</kbd><kbd>→</kbd> Przenieś zaznaczony punkt<br><kbd class='text'>Shift</kbd> Przenieś zaznaczony punkt o 10 jednostek<br><kbd class='text'>Tab</kbd> Zmień punkt",
    "STEPS_EDITOR_INFO"                         : "<kbd>↑</kbd><kbd>↓</kbd> Zwiększ lub zmiejsz kroki<br><kbd>←</kbd><kbd>→</kbd> 'Start' lub 'End'",
    "INLINE_TIMING_EDITOR_INVALID"              : "Obecna wartość <code>{0}</code> jest niepoprawna, więc została zamieniona na <code>{1}</code>.",

    // extensions/default/InlineColorEditor
    "COLOR_EDITOR_CURRENT_COLOR_SWATCH_TIP"     : "Obecny kolor",
    "COLOR_EDITOR_ORIGINAL_COLOR_SWATCH_TIP"    : "Oryginalny kolor",
    "COLOR_EDITOR_RGBA_BUTTON_TIP"              : "Format RGBa",
    "COLOR_EDITOR_HEX_BUTTON_TIP"               : "Format Hex",
    "COLOR_EDITOR_HSLA_BUTTON_TIP"              : "Format HSLa",
    "COLOR_EDITOR_USED_COLOR_TIP_SINGULAR"      : "{0} (Użyto {1} raz)",
    "COLOR_EDITOR_USED_COLOR_TIP_PLURAL"        : "{0} (Użyto {1} razy)",

    // extensions/default/JavaScriptCodeHints
    "CMD_JUMPTO_DEFINITION"                     : "Przeskocz do definicji",
    "CMD_SHOW_PARAMETER_HINT"                   : "Pokaż podpowiedzi",
    "NO_ARGUMENTS"                              : "<brak parametrów>",
    "DETECTED_EXCLUSION_TITLE"                  : "JavaScript problem",
    "DETECTED_EXCLUSION_INFO"                   : "{APP_NAME} ma kłopoty z przetworzeniem <span class='dialog-filename'>{0}</span>.<br><br>Ten plik nie będzie już przetwarzany z podpowiedziami, Przeskocz do definicji lub użyj szybkiej edycji. Aby przywrócić tą funkcjonalność, otwórz <code>.brackets.json</code> w twoim projekcie i edytuj <code>jscodehints.detectedExclusions</code>.<br><br>Jest to prawopodobnie błąd {APP_NAME}. Jeżeli możesz dostarczyć kopię tego pliku, prosimy <a href='https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue'>Złożyć raport</a> z linkiem do problematycznego pliku.",

    // extensions/default/JSLint
    "JSLINT_NAME"                               : "JSLint",

    // extensions/default/QuickView
    "CMD_ENABLE_QUICK_VIEW"                     : "Podgląd po najechaniu",

    // extensions/default/RecentProjects
    "CMD_TOGGLE_RECENT_PROJECTS"                : "Ostatnie projekty",

    // extensions/default/WebPlatformDocs
    "DOCS_MORE_LINK"                            : "Czytaj więcej",

    // extensions/default/CodeFolding
    "COLLAPSE_ALL"                  : "Zwiń wszystko",
    "EXPAND_ALL"                    : "Rozwiń wszystko",
    "COLLAPSE_CURRENT"              : "Zwiń aktalnie używane",
    "EXPAND_CURRENT"                : "Rozwiń aktualnie używane",

    // Descriptions of core preferences
    "DESCRIPTION_CLOSE_BRACKETS"                     : "true to automatically close braces, brackets and parentheses",
    "DESCRIPTION_CLOSE_OTHERS_ABOVE"                 : "false to remove the \"Close Others Above\" from the Working Files context menu",
    "DESCRIPTION_CLOSE_OTHERS_BELOW"                 : "false to remove the \"Close Others Below\" from the Working Files context menu",
    "DESCRIPTION_CLOSE_OTHERS"                       : "false to remove the \"Close Others\" from the Working Files context menu",
    "DESCRIPTION_CLOSE_TAGS"                         : "Sets the tag closing options",
    "DESCRIPTION_CLOSE_TAGS_DONT_CLOSE_TAGS"         : "An array of tags that should not be auto-closed",
    "DESCRIPTION_CLOSE_TAGS_WHEN_OPENING"            : "Close when > of opening tag is typed",
    "DESCRIPTION_CLOSE_TAGS_WHEN_CLOSING"            : "Close when / of closing tag is typed",
    "DESCRIPTION_CLOSE_TAGS_INDENT_TAGS"             : "An array of tags that when opened has a blank line",
    "DESCRIPTION_CODE_FOLDING_ALWAY_USE_INDENT_FOLD" : "true to always generate collapsible section markers when indent level changes",
    "DESCRIPTION_CODE_FOLDING_ENABLED"               : "true to enable code folding",
    "DESCRIPTION_CODE_FOLDING_HIDE_UNTIL_MOUSEOVER"  : "true to make Section-collapsing markers visible only when you move the mouse over the gutter",
    "DESCRIPTION_CODE_FOLDING_MAX_FOLD_LEVEL"        : "Limits how many levels deep Collapse All applies",
    "DESCRIPTION_CODE_FOLDING_MIN_FOLD_SIZE"         : "Minimum lines before a collapsible section icon appears",
    "DESCRIPTION_CODE_FOLDING_SAVE_FOLD_STATES"      : "true to remember collapsed sections if you close and reopen a file or project",
    "DESCRIPTION_CODE_FOLDING_MAKE_SELECTIONS_FOLDABLE": "true to enable code folding on selected text in the editor",
    "DESCRIPTION_ATTR_HINTS"                         : "Enable/disable HTML attribute hints",
    "DESCRIPTION_CSS_PROP_HINTS"                     : "Enable/disable CSS/LESS/SCSS property hints",
    "DESCRIPTION_JS_HINTS"                           : "Enable/disable JavaScript code hints",
    "DESCRIPTION_JS_HINTS_TYPE_DETAILS"              : "Enable/disable datatype details in JavaScript code hints",
    "DESCRIPTION_PREF_HINTS"                         : "Enable/disable Preferences code hints",
    "DESCRIPTION_SPECIAL_CHAR_HINTS"                 : "Enable/disable HTML entity hints",
    "DESCRIPTION_SVG_HINTS"                          : "Enable/disable SVG code hints",
    "DESCRIPTION_HTML_TAG_HINTS"                     : "Enable/disable HTML tag hints",
    "DESCRIPTION_URL_CODE_HINTS"                     : "Enable/disable URL hints in HTML & CSS/LESS/SCSS",
    "DESCRIPTION_DRAG_DROP_TEXT"                     : "Enable/disable Drag & Drop functionality",
    "DESCRIPTION_HEALTH_DATA_TRACKING"               : "Enable the Health Data Tracking",
    "DESCRIPTION_HIGHLIGHT_MATCHES"                  : "Enables automatic highlighting of matching strings throughout the document",
    "DESCRIPTION_HIGHLIGHT_MATCHES_SHOW_TOKEN"       : "Highlight all strings that match the token the cursor is currently in (no selection needed)",
    "DESCRIPTION_HIGHLIGHT_MATCHES_WORDS_ONLY"       : "Highlight only when selection is a complete token",
    "DESCRIPTION_INSERT_HINT_ON_TAB"                 : "true to insert the currently selected code hint on tab",
    "DESCRIPTION_NO_HINTS_ON_DOT"                    : "true to not automatically show JS code hints when . is typed",
    "DESCRIPTION_JSLINT_OPTIONS"                     : "An object with the default options for JSLint",
    "DESCRIPTION_JSLINT_OPTIONS_ASS"                 : "true to allow assignment expressions",
    "DESCRIPTION_JSLINT_OPTIONS_BITWISE"             : "true to allow bitwise operators",
    "DESCRIPTION_JSLINT_OPTIONS_BROWSER"             : "true if standard browser globals should be predefined",
    "DESCRIPTION_JSLINT_OPTIONS_CLOSURE"             : "true to allow Google Closure idioms",
    "DESCRIPTION_JSLINT_OPTIONS_CONTINUE"            : "true to allow \"continue\" statement",
    "DESCRIPTION_JSLINT_OPTIONS_COUCH"               : "true if CouchDB globals should be predefined",
    "DESCRIPTION_JSLINT_OPTIONS_DEBUG"               : "true to allow debugger statements",
    "DESCRIPTION_JSLINT_OPTIONS_DEVEL"               : "true if browser globals useful in development should be predefined",
    "DESCRIPTION_JSLINT_OPTIONS_EQEQ"                : "true to allow == and !=",
    "DESCRIPTION_JSLINT_OPTIONS_ES6"                 : "true if ES6 globals should be predefined",
    "DESCRIPTION_JSLINT_OPTIONS_EVIL"                : "true to allow eval",
    "DESCRIPTION_JSLINT_OPTIONS_FORIN"               : "true to allow unfiltered \"for ... in\"",
    "DESCRIPTION_JSLINT_OPTIONS_INDENT"              : "Set a specific tab width",
    "DESCRIPTION_JSLINT_OPTIONS_MAXERR"              : "The maximum number of warnings reported",
    "DESCRIPTION_JSLINT_OPTIONS_MAXLEN"              : "The maximum number of characters in a line",
    "DESCRIPTION_JSLINT_OPTIONS_NEWCAP"              : "true to allow uncapitalized constructors",
    "DESCRIPTION_JSLINT_OPTIONS_NODE"                : "true if Node.js globals should be predefined",
    "DESCRIPTION_JSLINT_OPTIONS_NOMEN"               : "true to allow dangling underscore in identifiers",
    "DESCRIPTION_JSLINT_OPTIONS_PASSFAIL"            : "true to stop on first error",
    "DESCRIPTION_JSLINT_OPTIONS_PLUSPLUS"            : "true to allow ++ and --",
    "DESCRIPTION_JSLINT_OPTIONS_REGEXP"              : "true to allow . and [^...]. in RegExp",
    "DESCRIPTION_JSLINT_OPTIONS_RHINO"               : "true if Rhino globals should be predefined",
    "DESCRIPTION_JSLINT_OPTIONS_SLOPPY"              : "true to allow missing `use strict` pragma",
    "DESCRIPTION_JSLINT_OPTIONS_STUPID"              : "true if blocking ('...Sync') methods can be used.",
    "DESCRIPTION_JSLINT_OPTIONS_SUB"                 : "true to allow inefficient subscripting",
    "DESCRIPTION_JSLINT_OPTIONS_TODO"                : "true to allow TODO comments",
    "DESCRIPTION_JSLINT_OPTIONS_UNPARAM"             : "true to allow unused parameters",
    "DESCRIPTION_JSLINT_OPTIONS_VARS"                : "true to allow more than 1 vars in a function",
    "DESCRIPTION_JSLINT_OPTIONS_WHITE"               : "true to ignore white-space rules",
    "DESCRIPTION_LANGUAGE"                           : "Language specific settings",
    "DESCRIPTION_LANGUAGE_FILE_EXTENSIONS"           : "Additional mappings from file extension to language name",
    "DESCRIPTION_LANGUAGE_FILE_NAMES"                : "Additional mappings from file name to language name",
    "DESCRIPTION_LINTING_ENABLED"                    : "true to enable Code Inspection",
    "DESCRIPTION_ASYNC_TIMEOUT"                      : "The time in milliseconds after which asynchronous linters time out",
    "DESCRIPTION_LINTING_PREFER"                     : "Array of linters to run first",
    "DESCRIPTION_LIVE_DEV_MULTIBROWSER"              : "true to enable experimental Live Preview",
    "DESCRIPTION_USE_PREFERED_ONLY"                  : "true to run providers specified in linting.prefer only",
    "DESCRIPTION_MAX_CODE_HINTS"                     : "Maximum code hints displayed at once",
    "DESCRIPTION_PATH"                               : "Path specific settings",
    "DESCRIPTION_PROXY"                              : "The URL of the proxy server used for extension installation",
    "DESCRIPTION_SCROLL_PAST_END"                    : "true to enable scrolling beyond the end of the document",
    "DESCRIPTION_SHOW_CODE_HINTS"                    : "false to disable all code hints",
    "DESCRIPTION_SHOW_CURSOR_WHEN_SELECTING"         : "Keeps the blinking cursor visible when you have a text selection",
    "DESCRIPTION_SHOW_LINE_NUMBERS"                  : "true to show line numbers in a “gutter” to the left of the code",
    "DESCRIPTION_SMART_INDENT"                       : "Automatically indent when creating a new block",
    "DESCRIPTION_SOFT_TABS"                          : "false to turn off soft tabs behavior",
    "DESCRIPTION_SORT_DIRECTORIES_FIRST"             : "true to sort the directories first in the project tree",
    "DESCRIPTION_SPACE_UNITS"                        : "Number of spaces to use for space-based indentation",
    "DESCRIPTION_STATIC_SERVER_PORT"                 : "Port number that the built-in server should use for Live Preview",
    "DESCRIPTION_STYLE_ACTIVE_LINE"                  : "true to highlight background color of the line the cursor is on",
    "DESCRIPTION_TAB_SIZE"                           : "Number of spaces to display for tabs",
    "DESCRIPTION_USE_TAB_CHAR"                       : "true to use tabs instead of spaces",
    "DESCRIPTION_UPPERCASE_COLORS"                   : "true to generate uppercase hex colors in Inline Color Editor",
    "DESCRIPTION_WORD_WRAP"                          : "Wrap lines that exceed the viewport width",
    "DESCRIPTION_DETECTED_EXCLUSIONS"                : "A list of files that have been detected to cause Tern to run out of control",
    "DESCRIPTION_INFERENCE_TIMEOUT"                  : "The amount of time after which Tern will time out when trying to understand files",
    "DESCRIPTION_SHOW_ERRORS_IN_STATUS_BAR"          : "true to show errors in status bar",
    "DESCRIPTION_QUICK_VIEW_ENABLED"                 : "true to enable Quick View",
    "DESCRIPTION_EXTENSION_LESS_IMAGE_PREVIEW"       : "true to show image previews for URLs missing extensions",
    "DESCRIPTION_THEME"                              : "Select a {APP_NAME} theme",
    "DESCRIPTION_USE_THEME_SCROLLBARS"               : "true to allow custom scroll bars",
    "DESCRIPTION_LINTING_COLLAPSED"                  : "true to collapse linting panel",
    "DESCRIPTION_FONT_FAMILY"                        : "Change font family",
    "DESCRIPTION_FONT_SIZE"                          : "Change font size; e.g. 13px",
    "DESCRIPTION_FIND_IN_FILES_NODE"                 : "true to enable node based search",
    "DESCRIPTION_FIND_IN_FILES_INSTANT"              : "true to enable instant search",
    "DESCRIPTION_FONT_SMOOTHING"                     : "Mac-only: \"subpixel-antialiased\" to enable sub-pixel antialiasing or \"antialiased\" for gray scale antialiasing",
    "DESCRIPTION_OPEN_PREFS_IN_SPLIT_VIEW"           : "false to disable opening preferences file in split view",
    "DESCRIPTION_OPEN_USER_PREFS_IN_SECOND_PANE"     : "false to open user preferences file in left/top pane",
    "DESCRIPTION_MERGE_PANES_WHEN_LAST_FILE_CLOSED"  : "true to collapse panes after the last file from the pane is closed via pane header close button",
    "DESCRIPTION_SHOW_PANE_HEADER_BUTTONS"           : "Toggle when to show the close and flip-view buttons on the header.",
    "DEFAULT_PREFERENCES_JSON_HEADER_COMMENT"        : "/*\n * This is a read-only file with the preferences supported\n * by {APP_NAME}.\n * Use this file as a reference to modify your preferences\n * file \"brackets.json\" opened in the other pane.\n * For more information on how to use preferences inside\n * {APP_NAME}, refer to the web page at https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences\n */",
    "DEFAULT_PREFERENCES_JSON_DEFAULT"               : "Default",
    "DESCRIPTION_PURE_CODING_SURFACE"                : "true to enable code only mode and hide all other UI elements in {APP_NAME}"
});

/* Last translated fcd2e98ef35c110e00aebfbb6d3c3816e5156552 */
