/*
 * Copyright (c) 2012 - present Adobe Systems Incorporated. All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

define({

    /**
     * Errors
     */

    // General file io error strings
    "GENERIC_ERROR"                     : "(មានបញ្ហា {0})",
    "NOT_FOUND_ERR"                     : "មិនអាចរកឃើញឯកសារ / ថត។",
    "NOT_READABLE_ERR"                  : "មិនអាចអានឯកសារ / ថតបានទេ។",
    "EXCEEDS_MAX_FILE_SIZE"             : "ឯកសារដែលធំជាង {0} MB មិនអាចបើកនៅក្នុង {APP_NAME} ។",
    "NO_MODIFICATION_ALLOWED_ERR"       : "ថតគោលដៅមិនអាចកែប្រែបាន។",
    "NO_MODIFICATION_ALLOWED_ERR_FILE"  : "គ្មានសិទិ្ធកែប្រែ",
    "CONTENTS_MODIFIED_ERR"             : "ឯកសារត្រូវបានកែប្រែនៅក្រៅ {APP_NAME} ។",
    "UNSUPPORTED_ENCODING_ERR"          : "មិនស្គាល់ទ្រង់ទ្រាយអ៊ិនកូដ",
    "ENCODE_FILE_FAILED_ERR"            : "{APP_NAME} មិនអាចអិុនកូដលើមាតិកាឯកសារបានទេ។",
    "DECODE_FILE_FAILED_ERR"            : "{APP_NAME} មិនអាចឌិកូដមាតិកាឯកសារបានទេ។",
    "UNSUPPORTED_UTF16_ENCODING_ERR"    : "{APP_NAME} បច្ចុប្បន្នមិនគាំទ្រឯកសារអត្ថបទដែលបានអ៊ិនកូដជា UTF-16 ទេ។",
    "FILE_EXISTS_ERR"                   : "មានឯកសារឬថតនេះរួចហើយ។",
    "FILE"                              : "ឯកសារ",
    "FILE_TITLE"                        : "ឯកសារ",
    "DIRECTORY"                         : "ថត",
    "DIRECTORY_TITLE"                   : "ថត",
    "DIRECTORY_NAMES_LEDE"              : "ឈ្មេាះថត",
    "FILENAMES_LEDE"                    : "ឈ្មោះឯកសារ",
    "FILENAME"                          : "ឈ្មោះឯកសារ",
    "DIRECTORY_NAME"                    : "ឈ្មេាះថត",

    // Project error strings
    "ERROR_LOADING_PROJECT"             : "កំហុសក្នុងការផ្ទុកគម្រោង",
    "OPEN_DIALOG_ERROR"                 : "កំហុសមួយបានកើតឡើងនៅពេលបង្ហាញប្រអប់ឯកសារ។ (កំហុស {0})",
    "REQUEST_NATIVE_FILE_SYSTEM_ERROR"  : "កំហុសមួយបានកើតឡើងនៅពេលព្យាយាមបើកថត​​ <span class='dialog-filename'>{0}</span>. (កំហុស {1})",
    "READ_DIRECTORY_ENTRIES_ERROR"      : "កំហុសមួយបានកើតឡើងនៅពេលអានមាតិការបស់ថត <span class='dialog-filename'>{0}</span>. (កំហុស {1})",

    // File open/save error string
    "ERROR_OPENING_FILE_TITLE"          : "កំហុសក្នុងការបើកឯកសារ",
    "ERROR_OPENING_FILE"                : "កំហុសមួយបានកើតឡើងនៅពេលព្យាយាមបើកឯកសារ <span class='dialog-filename'>{0}</span>. {1}",
    "ERROR_OPENING_FILES"               : "កំហុសមួយបានកើតឡើងនៅពេលព្យាយាមបើកឯកសារខាងក្រោម:",
    "ERROR_RELOADING_FILE_TITLE"        : "កំហុសក្នុងការផ្ទុកការផ្លាស់ប្តូរពីថាស",
    "ERROR_RELOADING_FILE"              : "កំហុសមួយបានកើតឡើងនៅពេលដែលព្យាយាមផ្ទុកឯកសារឡើងវិញ <span class='dialog-filename'>{0}</span>. {1}",
    "ERROR_SAVING_FILE_TITLE"           : "កំហុសក្នុងការរក្សាផ្តុកឯកសារ",
    "ERROR_SAVING_FILE"                 : "កំហុសមួយបានកើតឡើងនៅពេលដែលព្យាយាមរក្សាទុកឯកសារ <span class='dialog-filename'>{0}</span>. {1}",
    "ERROR_RENAMING_FILE_TITLE"         : "កំហុសក្នុងការប្តូរឈ្មោះ {0}",
    "ERROR_RENAMING_FILE"               : "កំហុសមួយបានកើតឡើងនៅពេលដែលព្យាយាមប្តូរឈ្មោះ {2} <span class='dialog-filename'>{0}</span>. {1}",
    "ERROR_RENAMING_NOT_IN_PROJECT"     : "ឯកសារឬថតមិនមែនជាផ្នែកនៃគម្រោងដែលបានបើកបច្ចុប្បន្នទេ។ ជាអកុសលមានតែឯកសារគម្រោងដែលអាចត្រូវបានប្តូរឈ្មោះនៅចំណុចនេះ។",
    "ERROR_MOVING_FILE_TITLE"           : "កំហុសក្នុងការផ្លាស់ទី {0}",
    "ERROR_MOVING_FILE"                 : "កំហុសមួយបានកើតឡើងនៅពេលដែលព្យាយាមផ្លាស់ទី {2} <span class='dialog-filename'>{0}</span>. {1}",
    "ERROR_MOVING_NOT_IN_PROJECT"       : "មិនអាចផ្លាស់ទីឯកសារ / ថតបានទេពីព្រោះវាមិនមែនជាផ្នែកនៃគម្រោងបច្ចុប្បន្ន។",
    "ERROR_DELETING_FILE_TITLE"         : "កំហុសក្នុងការលុប {0}",
    "ERROR_DELETING_FILE"               : "កំហុសមួយបានកើតឡើងនៅពេលដែលព្យាយាមលុប {2} <span class='dialog-filename'>{0}</span>. {1}",
    "INVALID_FILENAME_TITLE"            : "មិនត្រឹមត្រូវ {0}",
    "INVALID_FILENAME_MESSAGE"          : "{0} មិនអាចប្រើពាក្យណារក្សាទុកប្រព័ន្ធណាមួយដោយបញ្ចប់ដោយសញ្ញា (​.) ឬប្រើតួអក្សរណាមួយដូចខាងក្រោម: <code class='emphasized'>{1}</code>",
    "ENTRY_WITH_SAME_NAME_EXISTS"       : "ឯកសារឬថតដែលមានឈ្មោះ <span class='dialog-filename'>{0}</span> ធ្លាប់​មាន​រួចហើយ។",
    "ERROR_CREATING_FILE_TITLE"         : "កំហុសក្នុងការបង្កើត {0}",
    "ERROR_CREATING_FILE"               : "កំហុសមួយបានកើតឡើងនៅពេលដែលកំពុងព្យាយាមបង្កើត {0} <span class='dialog-filename'>{1}</span>. {2}",
    "ERROR_MIXED_DRAGDROP"              : "មិនអាចបើកថតក្នុងពេលតែមួយបានទេដោយបើកឯកសារផ្សេង។",

    // User key map error strings
    "ERROR_KEYMAP_TITLE"                : "កំហុសក្នុងការអានផែនទីគន្លឹះអ្នកប្រើ",
    "ERROR_KEYMAP_CORRUPT"              : "ឯកសារផែនទីគន្លឹះរបស់អ្នកមិនត្រឹមត្រូវ JSON ។ ឯកសារនឹងត្រូវបានបើកដូច្នេះអ្នកអាចកែតម្រូវទ្រង់ទ្រាយ។",
    "ERROR_LOADING_KEYMAP"              : "ឯកសារផែនទីគន្លឹះរបស់អ្នកមិនមែនជាឯកសារអត្ថបទដែលបានអ៊ិនកូដ UTF-8 ដែលត្រឹមត្រូវហើយមិនអាចផ្ទុកបានទេ",
    "ERROR_RESTRICTED_COMMANDS"         : "អ្នកមិនអាចកំណត់ផ្លូវកាត់ឡើងវិញទៅពាក្យបញ្ជាទាំងនេះទេ: {0}",
    "ERROR_RESTRICTED_SHORTCUTS"        : "អ្នកមិនអាចកំណត់ផ្លូវកាត់ទាំងនេះម្នងទៀតបានទេ: {0}",
    "ERROR_MULTIPLE_SHORTCUTS"          : "អ្នកត្រូវបានផ្ដល់ផ្លូវកាត់ថ្មីទៅពាក្យបញ្ជាទាំងនេះ: {0}",
    "ERROR_DUPLICATE_SHORTCUTS"         : "អ្នកមានការចងច្រើននៃផ្លូវកាត់ទាំងនេះ: {0}",
    "ERROR_INVALID_SHORTCUTS"           : "ផ្លូវកាត់ទាំងនេះមិនត្រឹមត្រូវ: {0}",
    "ERROR_NONEXISTENT_COMMANDS"        : "អ្នកត្រូវបានផ្ដល់ផ្លូវកាត់ទៅពាក្យបញ្ជាដែលមិនទាន់មាន: {0}",

    // Application preferences corrupt error strings
    "ERROR_PREFS_CORRUPT_TITLE"         : "កំហុសអានតាមចំណង់ចំណូលចិត្ត",
    "ERROR_PREFS_CORRUPT"               : "ឯកសារចំណង់ចំណូលចិត្តរបស់អ្នកមិនត្រឹមត្រូវ JSON ។ ឯកសារនឹងត្រូវបានបើកដូច្នេះអ្នកអាចកែតម្រូវទ្រង់ទ្រាយ។ អ្នកនឹងត្រូវចាប់ផ្តើម {APP_NAME} ឡើងវិញសម្រាប់ការផ្លាស់ប្តូរដើម្បីឱ្យមានប្រសិទ្ធិភាព។",
    "ERROR_PROJ_PREFS_CORRUPT"          : "ឯកសារចំណង់ចំណូលចិត្តគម្រោងរបស់អ្នកមិនត្រឹមត្រូវ JSON ។ ឯកសារនឹងត្រូវបានបើកដូច្នេះអ្នកអាចកែតម្រូវទ្រង់ទ្រាយ។ អ្នកនឹងត្រូវផ្ទុកគម្រោងឡើងវិញដើម្បីឱ្យការផ្លាស់ប្តូរមានប្រសិទ្ធិភាព។",

    // Application error strings
    "ERROR_IN_BROWSER_TITLE"            : "អូ៎! {APP_NAME} មិនដំណើរការក្នុងកម្មវិធី Browsers ទេ។",
    "ERROR_IN_BROWSER"                  : "{APP_NAME} ត្រូវបានបង្កើតឡើងជា HTML ប៉ុន្តែឥឡូវនេះវាដំណើរការជាកម្មវិធីផ្ទៃតុដូច្នេះអ្នកអាចប្រើវាដើម្បីកែសម្រួលឯកសារមូលដ្ឋាន។ សូមប្រើសែលកម្មវិធីនៅក្នុងកម្មវិធី repo <b> github.com/adobe/brackets-shell </ b> ដើម្បីដំណើរការ {APP_NAME} ។",

    // ProjectManager max files error string
    "ERROR_MAX_FILES_TITLE"             : "កំហុសក្នុងការបង្កើតលិបិក្រម",
    "ERROR_MAX_FILES"                   : "គម្រោងនេះមានឯកសារច្រើនជាង 30,000 ។ លក្ខណៈពិសេសដែលដំណើរការលើឯកសារច្រើនអាចត្រូវបានបិទឬមានឥរិយាបថដូចជាគម្រោងទំនេរ។ <a href='https://github.com/adobe/brackets/wiki/Large-Projects'>អានបន្ថែមអំពីការធ្វើការជាមួយគម្រោងធំ ៗ</a>.",

    // Live Preview error strings
    "ERROR_LAUNCHING_BROWSER_TITLE"     : "កំហុសក្នុងការចាប់ផ្ដើម Browser",
    "ERROR_CANT_FIND_CHROME"            : "Google Chrome browser មិនអាចរកឃើញ។ សូមប្រាកដថាវាត្រូវបានដំឡើង។",
    "ERROR_LAUNCHING_BROWSER"           : "កំហុសមួយបានកើតឡើងនៅពេលបើកកម្មវិធីអ៊ីនធឺណិត។ (កំហុស {0})",

    "LIVE_DEVELOPMENT_ERROR_TITLE"      : "កំហុសការមើលជាមុនបន្តផ្ទាល់",
    "LIVE_DEVELOPMENT_RELAUNCH_TITLE"   : "កំពុងភ្ជាប់ទៅ Browser",
    "LIVE_DEVELOPMENT_ERROR_MESSAGE"    : "ដើម្បីឱ្យមើលជាមុនការមើលជាមុនដើម្បីភ្ជាប់, Chrome ត្រូវបានបើកដំណើរការឡើងវិញដោយប្រើការកែកំហុសពីចម្ងាយ។<br /><br />តើអ្នកចង់បើក Chrome និងបើកការកែកំហុសពីចម្ងាយទេ?<br /><br />",
    "LIVE_DEV_LOADING_ERROR_MESSAGE"    : "មិនអាចផ្ទុកទំព័រមើលជាមុនបន្តផ្ទាល់។",
    "LIVE_DEV_NEED_HTML_MESSAGE"        : "បើកឯកសារ HTML ឬត្រូវប្រាកដថាមានឯកសារ index.html ក្នុងគម្រោងរបស់អ្នកដើម្បីចាប់ផ្ដើមការមើលជាមុន។",
    "LIVE_DEV_NEED_BASEURL_MESSAGE"     : "ដើម្បីចាប់ផ្ដើមការមើលជាមុនដោយផ្ទាល់ជាមួយឯកសារផ្នែកខាងម៉ាស៊ីនបម្រើអ្នកត្រូវបញ្ជាក់ URL មូលដ្ឋានសម្រាប់គម្រោងនេះ។",
    "LIVE_DEV_SERVER_NOT_READY_MESSAGE" : "មានកំហុសក្នុងការចាប់ផ្ដើមម៉ាស៊ីនបម្រើ HTTP សម្រាប់ឯកសារការមើលជាមុន។ សូម​ព្យាយាម​ម្តង​ទៀត។",
    "LIVE_DEVELOPMENT_INFO_TITLE"       : "សូមស្វាគមន៍មកកាន់មើលជាមុនមើលផ្ទាល់!",
    "LIVE_DEVELOPMENT_INFO_MESSAGE"     : "ការមើលការផ្សាយបន្តផ្ទាល់ភ្ជាប់ {APP_NAME} ទៅកម្មវិធីរុករករបស់អ្នក។ វាបើកការមើលជាមុននៃឯកសារ HTML របស់អ្នកនៅក្នុងកម្មវិធីរុករកបន្ទាប់មកធ្វើការកែប្រែការមើលជាមុនភ្លាមនៅពេលអ្នកកែសម្រួលកូដរបស់អ្នក។ <br /> <br /> នៅក្នុងកំណែដើមនៃ {APP_NAME} ការមើលជាមុនការផ្សាយបន្តផ្ទាល់ធ្វើការជាមួយ <strong> Google Chrome </ strong> និងធ្វើបច្ចុប្បន្នភាពផ្ទាល់នៅពេលដែលអ្នកកែសម្រួល <strong> ឯកសារ CSS ឬ HTML </ strong> ។ ការផ្លាស់ប្តូរឯកសារ JavaScript ត្រូវបានផ្ទុកឡើងវិញដោយស្វ័យប្រវត្តិនៅពេលអ្នកសន្សំ។ <br /> <br /> (អ្នកនឹងឃើញសារនេះតែម្តងគត់) ។",
    "LIVE_DEVELOPMENT_TROUBLESHOOTING"  : "សម្រាប់ព័ត៌មានបន្ថែមសូមមើល <a href='{0}' title='{0}'>ការដោះស្រាយបញ្ហាកំហុសការតភ្ជាប់មើលជាមុន</a>.",

    "LIVE_DEV_STATUS_TIP_NOT_CONNECTED" : "មើលការផ្សាយបន្តផ្ទាល់",
    "LIVE_DEV_STATUS_TIP_PROGRESS1"     : "មើលការផ្សាយបន្តផ្ទាល់: ភ្ជាប់\u2026",
    "LIVE_DEV_STATUS_TIP_PROGRESS2"     : "មើលការផ្សាយបន្តផ្ទាល់: ការចាប់ផ្តើម\u2026",
    "LIVE_DEV_STATUS_TIP_CONNECTED"     : "ផ្ដាច់ការមើលជាមុនផ្ទាល់",
    "LIVE_DEV_STATUS_TIP_OUT_OF_SYNC"   : "មើលការផ្សាយផ្ទាល់ (រក្សាទុកឯកសារដើម្បីធ្វើឱ្យស្រស់)",
    "LIVE_DEV_STATUS_TIP_SYNC_ERROR"    : "មើលការផ្សាយបន្តផ្ទាល់ (មិនធ្វើបច្ចុប្បន្នភាពដោយសារកំហុសវាក្យសម្ព័ន្ធ)",

    "LIVE_DEV_DETACHED_REPLACED_WITH_DEVTOOLS" : "ការផ្សាយបន្តផ្ទាល់ត្រូវបានលុបចោលដោយសារតែឧបករណ៍អភិវឌ្ឍន៍របស់ browser ត្រូវបានបើក",
    "LIVE_DEV_DETACHED_TARGET_CLOSED"          : "ការមើលការផ្សាយបន្តផ្ទាល់ត្រូវបានលុបចោលដោយសារតែទំព័រត្រូវបានបិទនៅក្នុង browser",
    "LIVE_DEV_NAVIGATED_AWAY"                  : "ការមើលជាមុនការផ្សាយបន្តផ្ទាល់ត្រូវបានលុបចោលដោយសារតែកម្មវិធីរុករកបានរុករកទៅទំព័រមួយដែលមិនមែនជាផ្នែកនៃគម្រោងបច្ចុប្បន្ន",
    "LIVE_DEV_CLOSED_UNKNOWN_REASON"           : "ការមើលការផ្សាយបន្តផ្ទាល់ត្រូវបានលុបចោលដោយមិនដឹងមូលហេតុ ({0})",

    "SAVE_CLOSE_TITLE"                  : "រក្សាទុកការផ្លាស់ប្តូរ",
    "SAVE_CLOSE_MESSAGE"                : "តើអ្នកចង់រក្សាទុកការផ្លាស់ប្តូរដែលអ្នកបានធ្វើក្នុងឯកសារ <span class='dialog-filename'>{0}</span>?",
    "SAVE_CLOSE_MULTI_MESSAGE"          : "តើអ្នកចង់រក្សាទុកការផ្លាស់ប្ដូររបស់អ្នកទៅឯកសារដូចខាងក្រោមទេ?",
    "EXT_MODIFIED_TITLE"                : "ការផ្លាស់ប្តូរខាងក្រៅ",
    "CONFIRM_DELETE_TITLE"              : "បញ្ជាក់ការលុប",
    "CONFIRM_FILE_DELETE"               : "តើអ្នកប្រាកដជាចង់លុបឯកសារ <span class='dialog-filename'>{0}</span>?",
    "CONFIRM_FOLDER_DELETE"             : "តើអ្នកពិតជាចង់លុបថតមែនទេ? <span class='dialog-filename'>{0}</span>?",
    "FILE_DELETED_TITLE"                : "បានលុបឯកសារ",
    "EXT_MODIFIED_WARNING"              : "<span class='dialog-filename'>{0}</span> ត្រូវបានកែប្រែលើថាសនៅក្រៅ {APP_NAME} ។<br /><br />តើអ្នកចង់រក្សាទុកឯកសារនិងសរសេរជាន់លើការផ្លាស់ប្ដូរទាំងនោះឬ?",
    "EXT_MODIFIED_MESSAGE"              : "<span class='dialog-filename'>{0}</span> ត្រូវបានកែប្រែនៅលើថាសនៅក្រៅ {APP_NAME} ប៉ុន្តែក៏មានការផ្លាស់ប្តូរមិនបានរក្សាទុកនៅក្នុង {APP_NAME} ។<br /><br />តើអ្នកចង់រក្សាទុកកំណែណាមួយ? ",
    "EXT_DELETED_MESSAGE"               : "<span class='dialog-filename'>{0}</span> ត្រូវបានលុបនៅលើថាសនៅក្រៅ {APP_NAME} ប៉ុន្តែមានការផ្លាស់ប្ដូរមិនបានរក្សាទុកនៅក្នុង {APP_NAME} ។ <br /> <br /> តើអ្នកចង់រក្សាការផ្លាស់ប្តូររបស់អ្នកទេ?",
    
    // Window unload warning messages
    "WINDOW_UNLOAD_WARNING"                      : "តើអ្នកប្រាកដថាអ្នកចង់ស្វែងរក URL ខុសៗគ្នាហើយចាកចេញពីតង្កៀបទេ?",
    "WINDOW_UNLOAD_WARNING_WITH_UNSAVED_CHANGES" : "អ្នកមានការផ្លាស់ប្តូរមិនបានរក្សាទុក! តើអ្នកប្រាកដថាអ្នកចង់ស្វែងរក URL ខុសៗគ្នាហើយចាកចេញពីតង្កៀបទេ?",

    // Generic dialog/button labels
    "DONE"                              : "រួច",
    "OK"                                : "OK",
    "CANCEL"                            : "បោះបង់",
    "DONT_SAVE"                         : "កុំរក្សាទុក",
    "SAVE"                              : "រក្សាទុក",
    "SAVE_AS"                           : "រក្សាទុក​ជា\u2026",
    "SAVE_AND_OVERWRITE"                : "សរសេរជាន់លើ",
    "DELETE"                            : "លុប",
    "BUTTON_YES"                        : "បាន",
    "BUTTON_NO"                         : "ទេ",

    // Find, Replace, Find in Files
    "FIND_MATCH_INDEX"                  : "{0} នៃ {1}",
    "FIND_NO_RESULTS"                   : "គ្មាន​លិទ្ធផល",
    "FIND_QUERY_PLACEHOLDER"            : "រក\u2026",
    "FIND_HISTORY_MAX_COUNT"            : "ចំនួនអតិបរមានៃធាតុស្វែងរកនៅក្នុងប្រវត្តិស្វែងរក",
    "REPLACE_PLACEHOLDER"               : "ជំនួយ​ដោយ\u2026",
    "BUTTON_REPLACE_ALL"                : "ជំនួសទាំងអស់",
    "BUTTON_REPLACE_BATCH"              : "បាច់\u2026",
    "BUTTON_REPLACE_ALL_IN_FILES"       : "ជំនួស\u2026",
    "BUTTON_REPLACE"                    : "ជំនួស",
    "BUTTON_NEXT"                       : "\u25B6",
    "BUTTON_PREV"                       : "\u25C0",
    "BUTTON_NEXT_HINT"                  : "ការប្រកួតបន្ទាប់",
    "BUTTON_PREV_HINT"                  : "ការប្រកួតមុន",
    "BUTTON_CASESENSITIVE_HINT"         : "ករណី​ការ​ប្រកួត",
    "BUTTON_REGEXP_HINT"                : "ការបញ្ចេញមតិធម្មតា",
    "REPLACE_WITHOUT_UNDO_WARNING_TITLE": "ជំនួសដោយមិនធ្វើវិញ",
    "REPLACE_WITHOUT_UNDO_WARNING"      : "ដោយសារតែមានជាង {0} ឯកសារត្រូវការផ្លាស់ប្តូរ {APP_NAME} នឹងកែឯកសារដែលមិនបានបើកនៅលើថាស។ <br /> អ្នកនឹងមិនអាចមិនធ្វើវិញបានទេក្នុងឯកសារទាំងនោះ។",
    "BUTTON_REPLACE_WITHOUT_UNDO"       : "ជំនួសដោយមិនធ្វើវិញ",

    "OPEN_FILE"                         : "បើក​ឯកសារ",
    "SAVE_FILE_AS"                      : "រក្សាទុក​ឯកសារ",
    "CHOOSE_FOLDER"                     : "ជ្រើសថត",

    "RELEASE_NOTES"                     : "កំណត់ការចេញផ្សាយ",
    "NO_UPDATE_TITLE"                   : "អ្នកមានដូចបរិច្ឆេទហើយ!",
    "NO_UPDATE_MESSAGE"                 : "អ្នកកំពុងដំណើរការកំណែចុងក្រោយបំផុតរបស់ {APP_NAME} ។",

    // Find and Replace
    "FIND_REPLACE_TITLE_LABEL"          : "ជំនួស",
    "FIND_REPLACE_TITLE_WITH"           : "ជាមួយ",
    "FIND_TITLE_LABEL"                  : "បានរកឃើញ",
    "FIND_TITLE_SUMMARY"                : "&mdash; {0} {1} {2} in {3}",

    // Find in Files
    "FIND_NUM_FILES"                    : "{0} {1}",
    "FIND_IN_FILES_SCOPED"              : "ក្នុង <span class='dialog-filename'>{0}</span>",
    "FIND_IN_FILES_NO_SCOPE"            : "នៅក្នុងគម្រោង",
    "FIND_IN_FILES_ZERO_FILES"          : "តម្រងមិនរាប់បញ្ចូលឯកសារទាំងអស់ទេ {0}",
    "FIND_IN_FILES_FILE"                : "ឯកសារ",
    "FIND_IN_FILES_FILES"               : "ឯកសារ",
    "FIND_IN_FILES_MATCH"               : "ត្រូវ",
    "FIND_IN_FILES_MATCHES"             : "ត្រូវ",
    "FIND_IN_FILES_MORE_THAN"           : "ចប់ ",
    "FIND_IN_FILES_PAGING"              : "{0}&mdash;{1}",
    "FIND_IN_FILES_FILE_PATH"           : "<span class='dialog-filename'>{0}</span> {2} <span class='dialog-path'>{1}</span>", // We should use normal dashes on Windows instead of em dash eventually
    "FIND_IN_FILES_EXPAND_COLLAPSE"     : "Ctrl/Cmd ចុចដើម្បីពង្រីក / បង្រួមទាំងអស់",
    "FIND_IN_FILES_INDEXING"            : "លិបិក្រមសម្រាប់ការស្វែងរកបន្ទាន់\u2026",
    "REPLACE_IN_FILES_ERRORS_TITLE"     : "ជំនួសកំហុស",
    "REPLACE_IN_FILES_ERRORS"           : "ឯកសារខាងក្រោមមិនត្រូវបានកែប្រែទេព្រោះពួកគេបានផ្លាស់ប្តូរបន្ទាប់ពីការស្វែងរកឬមិនអាចសរសេរបាន។",

    "ERROR_FETCHING_UPDATE_INFO_TITLE"  : "កំហុសក្នុងការធ្វើឱ្យទាន់សម័យព័ត៌មាន",
    "ERROR_FETCHING_UPDATE_INFO_MSG"    : "មានបញ្ហាក្នុងការទទួលបានព័ត៌មានថ្មីៗពីម៉ាស៊ីនមេ។ សូមប្រាកដថាអ្នកបានភ្ជាប់អ៊ីនធឺណិតហើយព្យាយាមម្តងទៀត។",

    // File exclusion filters
    "NEW_FILE_FILTER"                   : "កំណត់ការដកចេញថ្មី\u2026",
    "CLEAR_FILE_FILTER"                 : "កុំមិនរាប់បញ្ចូលឯកសារ",
    "NO_FILE_FILTER"                    : "គ្មានឯកសារត្រូវបានដកចេញ",
    "EXCLUDE_FILE_FILTER"               : "ដកចេញ {0}",
    "EDIT_FILE_FILTER"                  : "កែប្រែ\u2026",
    "FILE_FILTER_DIALOG"                : "កែសម្រួលកំណត់ការបដិសេធ",
    "FILE_FILTER_INSTRUCTIONS"          : "មិនរាប់បញ្ចូលឯកសារនិងថតដែលផ្គូផ្គងទៅខ្សែអក្សរ / ខ្សរងឬខ្សែអក្សរខាងក្រោមណាមួយឬ <a href='{0}' title='{0}'>wildcards</a>. បញ្ចូលខ្សែអក្សរនីមួយៗនៅលើបន្ទាត់ថ្មី។",
    "FILTER_NAME_PLACEHOLDER"           : "ដាក់ឈ្មោះការលើកលែងនេះ (ស្រេចចិត្ត)",
    "FILTER_NAME_REMAINING"             : "{0} តួអក្សរដែលនៅសល់",
    "FILE_FILTER_CLIPPED_SUFFIX"        : "នឹង {0} ទៀត",
    "FILTER_COUNTING_FILES"             : "កំពុងរាប់ឯកសារ\u2026",
    "FILTER_FILE_COUNT"                 : "អនុញ្ញាតឱ្យ {0} នៃ {1} ឯកសារ {2}",
    "FILTER_FILE_COUNT_ALL"             : "អនុញ្ញាតឱ្យឯកសារ {0} ទាំងអស់ {1}",

    // Quick Edit
    "ERROR_QUICK_EDIT_PROVIDER_NOT_FOUND"   : "គ្មានការកែសំរួលរហ័សសម្រាប់ទស្សន៍ទ្រនិចបច្ចុប្បន្ន",
    "ERROR_CSSQUICKEDIT_BETWEENCLASSES"     : "CSS កែសម្រួលរហ័ស: ដាក់ទស្សន៍ទ្រនិចលើឈ្មោះថ្នាក់តែមួយ",
    "ERROR_CSSQUICKEDIT_CLASSNOTFOUND"      : "CSS កែសម្រួលរហ័ស: គុណលក្ខណៈថ្នាក់មិនពេញលេញ",
    "ERROR_CSSQUICKEDIT_IDNOTFOUND"         : "CSS កែសម្រួលរហ័ស: គុណលក្ខណៈ លេខសម្កាល់ មិនពេញលេញ",
    "ERROR_CSSQUICKEDIT_UNSUPPORTEDATTR"    : "CSS កែសម្រួលរហ័ស: ដាក់ទស្សន៍ទ្រនិចក្នុងស្លាក, ថ្នាក់ឬលេខសម្គាល់",
    "ERROR_TIMINGQUICKEDIT_INVALIDSYNTAX"   : "CSS មុខងារកំណត់ពេលកែសម្រួលរហ័ស: វាក្យសម្ពន្ធមិនត្រឹមត្រូវ",
    "ERROR_JSQUICKEDIT_FUNCTIONNOTFOUND"    : "JS កែសម្រួលរហ័ស: ដាក់ទស្សន៍ទ្រនិចក្នុងឈ្មោះអនុគមន៍",

    // Quick Docs
    "ERROR_QUICK_DOCS_PROVIDER_NOT_FOUND"   : "គ្មានឯកសាររហ័សដែលអាចរកបានសម្រាប់ទីតាំងទស្សន៍ទ្រនិចបច្ចុប្បន្ន",

    /**
     * ProjectManager
     */
    "PROJECT_LOADING"   : "កំពុងដំណើរការ\u2026",
    "UNTITLED"          : "គ្មានឈ្មោះ",
    "WORKING_FILES"     : "ឯកសារការងារ",

    /**
     * MainViewManager
     */
    "TOP"               : "ខាងលើ",
    "BOTTOM"            : "បាត",
    "LEFT"              : "ឆ្វេង",
    "RIGHT"             : "សិទ្ធិ",

    "CMD_SPLITVIEW_NONE"        : "គ្មានការពុះ",
    "CMD_SPLITVIEW_VERTICAL"    : "បញ្ឈរពុះ",
    "CMD_SPLITVIEW_HORIZONTAL"  : "បំបែកផ្ដេក",
    "SPLITVIEW_MENU_TOOLTIP"    : "បំបែកកម្មវិធីនិពន្ធបញ្ឈរឬផ្ដេក",
    "GEAR_MENU_TOOLTIP"         : "កំណត់រចនាសម្ព័ន្ធការងារ",

    "SPLITVIEW_INFO_TITLE"              : "រួចហើយបើក",
    "SPLITVIEW_MULTIPANE_WARNING"       : "ឯកសារត្រូវបានបើករួចហើយនៅក្នុងផ្ទាំងផ្សេងទៀត។ {APP_NAME} នឹងគាំទ្រក្នុងការបើកឯកសារដូចគ្នានៅក្នុងផ្ទាំងច្រើនជាងមួយ។ រហូតមកដល់ពេលនោះឯកសារនឹងត្រូវបានបង្ហាញក្នុងផ្ទាំងដែលបើករួចហើយ។ <br /> <br /> (អ្នកនឹងឃើញតែសារនេះប៉ុណ្ណោះ) ។",

    /**
     * Keyboard modifiers and special key names
     */
    "KEYBOARD_CTRL"         : "Ctrl",
    "KEYBOARD_SHIFT"        : "Shift",
    "KEYBOARD_SPACE"        : "Space",
    "KEYBOARD_PAGE_UP"      : "Page Up",
    "KEYBOARD_PAGE_DOWN"    : "Page Down",
    "KEYBOARD_HOME"         : "Home",
    "KEYBOARD_END"          : "End",
    "KEYBOARD_INSERT"       : "Insert",
    "KEYBOARD_DELETE"       : "Delete",

    /**
     * StatusBar strings
     */
    "STATUSBAR_CURSOR_POSITION"             : "បន្ទាត់ {0}, ជួរ {1}",
    "STATUSBAR_SELECTION_CH_SINGULAR"       : " \u2014 បានជ្រើសជួរឈរ {0}",
    "STATUSBAR_SELECTION_CH_PLURAL"         : " \u2014 បានជ្រើសជួរឈរ {0}",
    "STATUSBAR_SELECTION_LINE_SINGULAR"     : " \u2014 បានជ្រើសបន្ទាត់ {0}",
    "STATUSBAR_SELECTION_LINE_PLURAL"       : " \u2014 បានជ្រើសបន្ទាត់ {0}",
    "STATUSBAR_SELECTION_MULTIPLE"          : " \u2014 {0} ជម្រើស",
    "STATUSBAR_INDENT_TOOLTIP_SPACES"       : "ចុចដើម្បីប្ដូរការចូលបន្ទាត់ទៅដកឃ្លា",
    "STATUSBAR_INDENT_TOOLTIP_TABS"         : "ចុចដើម្បីប្ដូរការចូលបន្ទាត់ទៅផ្ទាំង",
    "STATUSBAR_INDENT_SIZE_TOOLTIP_SPACES"  : "ចុចដើម្បីប្ដូរទំហំចន្លោះដែលបានប្រើនៅពេលចូលបន្ទាត់",
    "STATUSBAR_INDENT_SIZE_TOOLTIP_TABS"    : "ចុចដើម្បីផ្លាស់ប្ដូរទទឹងតួអក្សរថេប",
    "STATUSBAR_SPACES"                      : "ចន្លោះ:",
    "STATUSBAR_TAB_SIZE"                    : "ទំហំផ្ទាំង:",
    "STATUSBAR_LINE_COUNT_SINGULAR"         : "\u2014 {0} បន្ទាត់",
    "STATUSBAR_LINE_COUNT_PLURAL"           : "\u2014 {0} បន្ទាត់",
    "STATUSBAR_USER_EXTENSIONS_DISABLED"    : "ផ្នែកបន្ថែមត្រូវបានបិទ",
    "STATUSBAR_INSERT"                      : "INS",
    "STATUSBAR_OVERWRITE"                   : "OVR",
    "STATUSBAR_INSOVR_TOOLTIP"              : "ចុចដើម្បីបង្វិលទស្សន៍ទ្រនិចរវាងរបៀបបញ្ចូល (INS) និង សរសេរជាន់លើ (OVR)",
    "STATUSBAR_LANG_TOOLTIP"                : "ចុចដើម្បីផ្លាស់ប្តូរប្រភេទឯកសារ",
    "STATUSBAR_CODE_INSPECTION_TOOLTIP"     : "{0}. ចុចដើម្បីបិទ / បើកបន្ទះរបាយការណ៍។",
    "STATUSBAR_DEFAULT_LANG"                : "(លំនាំដើម)",
    "STATUSBAR_SET_DEFAULT_LANG"            : "កំណត់ជាលំនាំដើមសម្រាប់។ {0} ឯកសារ",
    "STATUSBAR_ENCODING_TOOLTIP"            : "ជ្រើសការអ៊ិនកូដ",

    // CodeInspection: errors/warnings
    "ERRORS_PANEL_TITLE_MULTIPLE"           : "{0} បញ្ហា",
    "SINGLE_ERROR"                          : "1 {0} បញ្ហា",
    "MULTIPLE_ERRORS"                       : "{1} {0} បញ្ហា",
    "NO_ERRORS"                             : "រកមិនឃើញបញ្ហា {0} - ការងារល្អ!",
    "NO_ERRORS_MULTIPLE_PROVIDER"           : "គ្មានបញ្ហាត្រូវបានរកឃើញ - ការងារល្អ!",
    "LINT_DISABLED"                         : "Linting ត្រូវបានបិទ",
    "NO_LINT_AVAILABLE"                     : "មិនមាន linter សម្រាប់ {0}",
    "NOTHING_TO_LINT"                       : "គ្មានអ្វីដែលគួរឱ្យស្រលាញ់ទេ",
    "LINTER_TIMED_OUT"                      : "{0} បានអស់ម៉ោងបន្ទាប់ពីរងចាំ {1} ms",
    "LINTER_FAILED"                         : "{0} បានបញ្ចប់ដោយមានកំហុស: {1}",

    /**
     * Command Name Constants
     */

    // File menu commands
    "FILE_MENU"                           : "ឯកសារ",
    "CMD_FILE_NEW_UNTITLED"               : "ថ្មី",
    "CMD_FILE_NEW"                        : "ឯកសារ ថ្នី",
    "CMD_FILE_NEW_FOLDER"                 : "ថត ថ្មី",
    "CMD_FILE_OPEN"                       : "បើក\u2026",
    "CMD_RECENT_FILES_OPEN"               : "បើកឯកសារចាស់\u2026",
    "CMD_ADD_TO_WORKING_SET"              : "បើកទៅសំណុំការងារ",
    "CMD_OPEN_DROPPED_FILES"              : "បើកឯកសារដែលបានទម្លាក់",
    "CMD_OPEN_FOLDER"                     : "បើកថត\u2026",
    "CMD_FILE_CLOSE"                      : "បិទ",
    "CMD_FILE_CLOSE_ALL"                  : "បិទទាំងអស់",
    "CMD_FILE_CLOSE_LIST"                 : "បិទបញ្ជី",
    "CMD_FILE_CLOSE_OTHERS"               : "បិទអាផ្រេង",
    "CMD_FILE_CLOSE_ABOVE"                : "បិទអ្នកផ្សេងទៀតខាងលើ",
    "CMD_FILE_CLOSE_BELOW"                : "បិទអ្នកដទៃខាងក្រោម",
    "CMD_FILE_SAVE"                       : "រក្សាទុក",
    "CMD_FILE_SAVE_ALL"                   : "រក្សាទុកទាំងអស់",
    "CMD_FILE_SAVE_AS"                    : "រក្សាទុក​ជា\u2026",
    "CMD_LIVE_FILE_PREVIEW"               : "មើលការផ្សាយបន្តផ្ទាល់",
    "CMD_TOGGLE_LIVE_PREVIEW_MB_MODE"     : "បើកដំណើរការការមើលជាមុនសាកល្បងដោយផ្ទាល់",
    "CMD_RELOAD_LIVE_PREVIEW"             : "បង្ខំឱ្យផ្ទុកឡើងឡើងវិញជាមុន",
    "CMD_PROJECT_SETTINGS"                : "ការកំណត់គម្រោង\u2026",
    "CMD_FILE_RENAME"                     : "ប្តូរឈ្មោះ",
    "CMD_FILE_DELETE"                     : "លុប",
    "CMD_INSTALL_EXTENSION"               : "ដំឡើងផ្នែកបន្ថែម\u2026",
    "CMD_EXTENSION_MANAGER"               : "កម្មវិធីគ្រប់គ្រងផ្នែកបន្ថែម\u2026",
    "CMD_FILE_REFRESH"                    : "ធ្វើឱ្យមែកធាងឯកសារឡើងវិញ",
    "CMD_QUIT"                            : "ចេញ",
    // Used in native File menu on Windows
    "CMD_EXIT"                            : "ចាកចេញ",

    // Edit menu commands
    "EDIT_MENU"                           : "កែ",
    "CMD_UNDO"                            : "មិនធ្វើវិញ",
    "CMD_REDO"                            : "ធ្វើវិញ",
    "CMD_CUT"                             : "កាត់",
    "CMD_COPY"                            : "ចម្លង",
    "CMD_PASTE"                           : "បិទភ្ជាប់",
    "CMD_SELECT_ALL"                      : "ជ្រើសរើស​ទាំងអស់",
    "CMD_SELECT_LINE"                     : "ជ្រើសបន្ទាត់",
    "CMD_SPLIT_SEL_INTO_LINES"            : "បំបែកការជ្រើសរើសចូលទៅក្នុងបន្ទាត់",
    "CMD_ADD_CUR_TO_NEXT_LINE"            : "បន្ថែមទស្សន៍ទ្រនិចទៅបន្ទាត់បន្ទាប់",
    "CMD_ADD_CUR_TO_PREV_LINE"            : "បន្ថែមទស្សន៍ទ្រនិចទៅបន្ទាត់មុន",
    "CMD_INDENT"                          : "ចូលបន្ទាត់",
    "CMD_UNINDENT"                        : "មិនចូលបន្ទាត់",
    "CMD_DUPLICATE"                       : "ស្ទួន",
    "CMD_DELETE_LINES"                    : "លុបបន្ទាត់",
    "CMD_COMMENT"                         : "បិទបើកមតិយោបល់បន្ទាត់",
    "CMD_BLOCK_COMMENT"                   : "បិទបើកមតិយោបល់ប្លុក",
    "CMD_LINE_UP"                         : "ផ្លាស់ទីបន្ទាត់ឡើងលើ",
    "CMD_LINE_DOWN"                       : "ផ្លាស់ទីបន្ទាត់ចុះក្រោម",
    "CMD_OPEN_LINE_ABOVE"                 : "បើកបន្ទាត់ខាងលើ",
    "CMD_OPEN_LINE_BELOW"                 : "បើកបន្ទាត់ខាងក្រោម",
    "CMD_TOGGLE_CLOSE_BRACKETS"           : "បិទរណបដោយស្វ័យប្រវត្តិ",
    "CMD_SHOW_CODE_HINTS"                 : "បង្ហាញកូដជំនួយ",

    // Search menu commands
    "FIND_MENU"                           : "រក",
    "CMD_FIND"                            : "រក",
    "CMD_FIND_NEXT"                       : "រកបន្ទាប់",
    "CMD_FIND_PREVIOUS"                   : "ស្វែងរកមុន",
    "CMD_FIND_ALL_AND_SELECT"             : "រកទាំងអស់និងជ្រើសរើស",
    "CMD_ADD_NEXT_MATCH"                  : "បន្ថែមការផ្គូផ្គងបន្ទាប់ទៅជម្រើស",
    "CMD_SKIP_CURRENT_MATCH"              : "រំលងហើយបន្ថែមការផ្គូផ្គងបន្ទាប់",
    "CMD_FIND_IN_FILES"                   : "រកនៅក្នុងឯកសារ",
    "CMD_FIND_IN_SUBTREE"                 : "ស្វែងរក\u2026",
    "CMD_REPLACE"                         : "ជំនួស",
    "CMD_REPLACE_IN_FILES"                : "ជំនួសនៅក្នុងឯកសារ",
    "CMD_REPLACE_IN_SUBTREE"              : "ជំនួស ក្នុង\u2026",

    // View menu commands
    "VIEW_MENU"                           : "មើល",
    "CMD_HIDE_SIDEBAR"                    : "លាក់របារចំហៀង",
    "CMD_SHOW_SIDEBAR"                    : "បង្ហាញរបារចំហៀង",
    "CMD_TOGGLE_SIDEBAR"                  : "បិទ / បើករបារចំហៀង",
    "CMD_TOGGLE_PANELS"                   : "បិទបើកបន្ទះ",
    "CMD_TOGGLE_PURE_CODE"                : "គ្មានការរំខាន",
    "CMD_INCREASE_FONT_SIZE"              : "បង្កើនទំហំពុម្ពអក្សរ",
    "CMD_DECREASE_FONT_SIZE"              : "បន្ថយទំហំពុម្ពអក្សរ",
    "CMD_RESTORE_FONT_SIZE"               : "ស្តារទំហំពុម្ពអក្សរ",
    "CMD_SCROLL_LINE_UP"                  : "រមូរបន្ទាត់ឡើង",
    "CMD_SCROLL_LINE_DOWN"                : "រមូរបន្ទាត់ចុះក្រោម",
    "CMD_TOGGLE_LINE_NUMBERS"             : "លេខបន្ទាត់",
    "CMD_TOGGLE_ACTIVE_LINE"              : "បន្លិចបន្ទាត់សកម្ម",
    "CMD_TOGGLE_WORD_WRAP"                : "ការរុំពាក្យ",
    "CMD_LIVE_HIGHLIGHT"                  : "ការរំលេចការផ្សាយបន្តផ្ទាល់បន្តផ្ទាល់",
    "CMD_VIEW_TOGGLE_INSPECTION"          : "ឯកសារ Lint លើការរក្សាទុក",
    "CMD_WORKINGSET_SORT_BY_ADDED"        : "តម្រៀបតាមការបន្ថែម",
    "CMD_WORKINGSET_SORT_BY_NAME"         : "តម្រៀបតាមឈ្មោះ",
    "CMD_WORKINGSET_SORT_BY_TYPE"         : "តម្រៀបតាមប្រភេទ",
    "CMD_WORKING_SORT_TOGGLE_AUTO"        : "តម្រៀបស្វ័យប្រវត្តិ",
    "CMD_THEMES"                          : "ស្បែក\u2026",
    "CMD_TOGGLE_SEARCH_AUTOHIDE"          : "បិទការស្វែងរកដោយស្វ័យប្រវត្តិ",

    // Navigate menu commands
    "NAVIGATE_MENU"                       : "រុករក",
    "CMD_QUICK_OPEN"                      : "បើករហ័ស",
    "CMD_GOTO_LINE"                       : "ទៅកាន់បន្ទាត់",
    "CMD_GOTO_DEFINITION"                 : "ស្វែងរកនិយមន័យរហ័ស",
    "CMD_GOTO_FIRST_PROBLEM"              : "ទៅបញ្ហាដំបូង",
    "CMD_TOGGLE_QUICK_EDIT"               : "កែសម្រួលរហ័ស",
    "CMD_TOGGLE_QUICK_DOCS"               : "ឯកសាររហ័ស",
    "CMD_QUICK_EDIT_PREV_MATCH"           : "ការពាក់ពាន់មុន",
    "CMD_QUICK_EDIT_NEXT_MATCH"           : "ការពាក់ពាន់បន្តាប់",
    "CMD_CSS_QUICK_EDIT_NEW_RULE"         : "ច្បាប់ថ្មី",
    "CMD_NEXT_DOC"                        : "ឯកសារបន្ទាប់",
    "CMD_PREV_DOC"                        : "ឯកសារពីមុន",
    "CMD_NAVIGATE_BACKWARD"               : "រុករកថយក្រោយ",
    "CMD_NAVIGATE_FORWARD"                : "រុករកឆ្ពោះទៅមុខ",
    "CMD_NEXT_DOC_LIST_ORDER"             : "ឯកសារបន្ទាប់នៅក្នុងបញ្ជី",
    "CMD_PREV_DOC_LIST_ORDER"             : "ឯកសារមុនក្នុងបញ្ជី",
    "CMD_SHOW_IN_TREE"                    : "បង្ហាញក្នុងមែកធាងឯកសារ",
    "CMD_SHOW_IN_EXPLORER"                : "បង្ហាញក្នុងកម្មវិធីរុករក",
    "CMD_SHOW_IN_FINDER"                  : "បង្ហាញនៅក្នុងឧបករណ៍រក",
    "CMD_SHOW_IN_OS"                      : "បង្ហាញក្នុង OS",
    "CMD_SWITCH_PANE_FOCUS"               : "ប្ដូរចំណុចសំខាន់",

    // Help menu commands
    "HELP_MENU"                           : "ជំនួយ",
    "CMD_CHECK_FOR_UPDATE"                : "ពិនិត្យរកមើលភាពទាន់សម័យ",
    "CMD_HOW_TO_USE_BRACKETS"             : "របៀបប្រើ {APP_NAME}",
    "CMD_SUPPORT"                         : "{APP_NAME} ជំនួយ",
    "CMD_SUGGEST"                         : "ស្នើលក្ខណៈពិសេស",
    "CMD_RELEASE_NOTES"                   : "កំណត់ការចេញផ្សាយ",
    "CMD_GET_INVOLVED"                    : "ចូលរួម",
    "CMD_SHOW_EXTENSIONS_FOLDER"          : "បង្ហាញសមាសភាគថតឯកសារ",
    "CMD_HEALTH_DATA_STATISTICS"          : "របាយការណ៍សុខាភិបាល",
    "CMD_HOMEPAGE"                        : "{APP_TITLE} ទំព័រដើម",
    "CMD_TWITTER"                         : "{TWITTER_NAME} នៅលើ Twitter",
    "CMD_ABOUT"                           : "អំពី {APP_TITLE}",
    "CMD_OPEN_PREFERENCES"                : "បើកឯកសារចំណង់ចំណូលចិត្ត",
    "CMD_OPEN_KEYMAP"                     : "បើកផែនទីគន្លឹះរបស់អ្នកប្រើ",

    // Strings for main-view.html
    "EXPERIMENTAL_BUILD"                   : "ការសាកល្បង",
    "RELEASE_BUILD"                        : "ស្ថាបនា",
    "DEVELOPMENT_BUILD"                    : "អភិវឌ្ឍន៍",
    "PRERELEASE_BUILD"                     : "ស្ថាបនាមុន",
    "RELOAD_FROM_DISK"                     : "ផ្ទុកឡើងវិញពីថាស",
    "KEEP_CHANGES_IN_EDITOR"               : "រក្សាទុកការផ្លាស់ប្តូរក្នុងកម្មវិធីនិពន្ធ",
    "CLOSE_DONT_SAVE"                      : "បិទ (កុំរក្សាទុក)",
    "RELAUNCH_CHROME"                      : "បើកដំណើរការឡើងវិញ Chrome",
    "ABOUT"                                : "អំពី",
    "CLOSE"                                : "បិទ",
    "ABOUT_TEXT_LINE1"                     : "លែង {VERSION_MAJOR} ។ {VERSION_MINOR} {BUILD_TYPE} {VERSION}",
    "ABOUT_TEXT_BUILD_TIMESTAMP"           : "ស្ថាបនាត្រាពេលវេលា: ",
    "ABOUT_TEXT_LINE3"                     : "​សេចក្តីជូនដំណឹងល័ក្ខខ័ណ្ឌទាក់ទងទៅនឹងកម្មវិធីភាគីទីបីមានទីតាំងស្ថិតនៅ <a href='{ADOBE_THIRD_PARTY}'>{ADOBE_THIRD_PARTY}</a> និងបញ្ចូលគ្នាដោយសេចក្តីយោងនៅទីនេះ។",
    "ABOUT_TEXT_LINE4"                     : "ឯកសារនិងប្រភពនៅ <a href='https://github.com/adobe/brackets/'>https://github.com/adobe/brackets/</a>",
    "ABOUT_TEXT_LINE5"                     : "បង្កើត​ដោយ \u2764 និង JavaScript ដោយ:",
    "ABOUT_TEXT_LINE6"                     : "មនុស្សជាច្រើន (ប៉ុន្តែយើងកំពុងមានបញ្ហាក្នុងការផ្ទុកទិន្នន័យនោះឥឡូវនេះ) ។",
    "ABOUT_TEXT_MDN_DOCS"                  : "MDN Docs និងនិមិត្តសញ្ញាក្រាហ្វិក MDN ត្រូវបានផ្តល់អាជ្ញាប័ណ្ណក្រោមអាជ្ញាប័ណ្ណ Creative Commons Attribution, <a href='{MDN_DOCS_LICENSE}'>CC-BY-SA 2.5 Unported</a>.",
    "UPDATE_NOTIFICATION_TOOLTIP"          : "មានកំណែថ្មីនៃ {APP_NAME} ដែលអាចរកបាន! សូមចុចនៅទីនេះសម្រាប់ព័ត៌មានលម្អិត។",
    "UPDATE_AVAILABLE_TITLE"               : "ធ្វើបច្ចុប្បន្នភាព",
    "UPDATE_MESSAGE"                       : "ហេមានការបង្កើត {APP_NAME} ថ្មី។ នេះគឺជាលក្ខណៈពិសេសថ្មីៗមួយចំនួន:",
    "GET_IT_NOW"                           : "ទទួលបានវាឥឡូវនេះ!",
    "PROJECT_SETTINGS_TITLE"               : "ការកំណត់គម្រោងសម្រាប់: {0}",
    "PROJECT_SETTING_BASE_URL"             : "ការមើលជាមុន URL មូលដ្ឋាន",
    "PROJECT_SETTING_BASE_URL_HINT"        : "ដើម្បីប្រើម៉ាស៊ីនបម្រើមូលដ្ឋានបញ្ចូល URL ដូច http: // localhost: 8000 /",
    "BASEURL_ERROR_INVALID_PROTOCOL"       : "ពិធីការ {0} មិនត្រូវបានគាំទ្រដោយការមើលជាមុនផ្ទាល់ទេ & mdash; សូមប្រើ http: ឬ https: ។",
    "BASEURL_ERROR_SEARCH_DISALLOWED"      : "URL មូលដ្ឋានមិនអាចមានប៉ារ៉ាម៉ែត្រស្វែងរកដូចជា \"{0}\".",
    "BASEURL_ERROR_HASH_DISALLOWED"        : "URL មូលដ្ឋានមិនអាចមានសញ្ញាដូច \"{0}\".",
    "BASEURL_ERROR_INVALID_CHAR"           : "តួអក្សរពិសេសដូចជា '{0}' ត្រូវតែជា% កូដ។",
    "BASEURL_ERROR_UNKNOWN_ERROR"          : "កំហុសក្នុងការវិភាគកំហុស URL មូលដ្ឋាន",

    // Strings for Pane.js
    "EMPTY_VIEW_HEADER"                    : "<em>បើកឯកសារខណៈពេលដែលស្លាបព្រិលនេះមានការផ្តោតអារម្មណ៍</em>",
    "FLIPVIEW_BTN_TOOLTIP"                 : "ត្រឡប់ទិដ្ឋភាពនេះទៅផ្ទាំង {0}",

    // Strings for themes-settings.html and themes-general.html
    "CURRENT_THEME"                        : "ស្បែកបច្ចុប្បន្ន",
    "USE_THEME_SCROLLBARS"                 : "ប្រើរបាររមូរស្បែក",
    "FONT_SIZE"                            : "ទំហំ​អក្សរ",
    "FONT_FAMILY"                          : "គ្រួសារពុម្ពអក្សរ",
    "THEMES_SETTINGS"                      : "ការកំណត់រូបរាង",

    // CSS Quick Edit
    "BUTTON_NEW_RULE"                      : "ច្បាប់ថ្មី",

    // Extension Management strings
    "INSTALL"                              : "ដំឡើង",
    "UPDATE"                               : "ធ្វើបច្ចុប្បន្នភាព",
    "REMOVE"                               : "យកចេញ",
    "DISABLE"                              : "បិទ",
    "ENABLE"                               : "អនុញ្ញាត",
    "OVERWRITE"                            : "សរសេរជាន់លើ",
    "CANT_REMOVE_DEV"                      : "ផ្នែកបន្ថែមនៅក្នុងថត \"dev\" ត្រូវតែលុបដោយដៃ។",
    "CANT_UPDATE"                          : "ការធ្វើបច្ចុប្បន្នភាពមិនត្រូវគ្នាជាមួយកំណែ {APP_NAME} នេះទេ។",
    "CANT_UPDATE_DEV"                      : "ផ្នែកបន្ថែមនៅ \"dev\" មិនអាចធ្វើបច្ចុប្បន្នភាពថតដោយស្វ័យប្រវត្តិ។",
    "INSTALL_EXTENSION_TITLE"              : "ដំឡើងផ្នែកបន្ថែម",
    "UPDATE_EXTENSION_TITLE"               : "ធ្វើបច្ចុប្បន្នភាពផ្នែកបន្ថែម",
    "INSTALL_EXTENSION_LABEL"              : "URL របស់ ផ្នែកបន្ថែម",
    "INSTALL_EXTENSION_HINT"               : "URL នៃឯកសារ zip របស់ផ្នែកបន្ថែមឬ GitHub repo",
    "INSTALLING_FROM"                      : "ដំឡើងផ្នែកបន្ថែមពី {0}\u2026",
    "INSTALL_SUCCEEDED"                    : "ការដំឡើងជោគជ័យ!",
    "INSTALL_FAILED"                       : "ការដំឡើងបានបរាជ័យ។",
    "CANCELING_INSTALL"                    : "បោះបង់\u2026",
    "CANCELING_HUNG"                       : "ការបោះបង់ការដំឡើងកំពុងចំណាយពេលយូរ។ កំហុសខាងក្នុងមួយប្រហែលជាបានកើតឡើង។",
    "INSTALL_CANCELED"                     : "បានបោះបង់ការដំឡើង។",
    "VIEW_COMPLETE_DESCRIPTION"            : "មើលការពិពណ៌នាពេញលេញ",
    "VIEW_TRUNCATED_DESCRIPTION"           : "មើលការពិពណ៌នាខ្លី",
    "SORT_EXTENSION_METHOD"                : "តម្រៀបផ្នែកបន្ថែមដោយប្រើប្រាស់ downloadCount ឬ publishedDate",
    // These must match the error codes in ExtensionsDomain.Errors.* :
    "INVALID_ZIP_FILE"                     : "មាតិកាទាញយកមិនមែនជាឯកសារ zip ត្រឹមត្រូវទេ។",
    "MISSING_PACKAGE_JSON"                 : "កញ្ចប់មិនមាន package.json file.",
    "INVALID_PACKAGE_JSON"                 : "ឯកសារ package.jsonមិនត្រឹមត្រូវ (កំហុសគឺ: {0}).",
    "MISSING_PACKAGE_NAME"                 : "ឯកសារ package.json មិនបញ្ជាក់ឈ្មោះកញ្ចប់។",
    "BAD_PACKAGE_NAME"                     : "{0} ជាឈ្មោះកញ្ចប់មិនត្រឹមត្រូវ។",
    "MISSING_PACKAGE_VERSION"              : "ឯកសារ​ package.json មិនបញ្ជាក់កំណែកញ្ចប់។",
    "INVALID_VERSION_NUMBER"               : "លេខកំណែកញ្ចប់ ({0}) មិនត្រឹមត្រូវ។",
    "INVALID_BRACKETS_VERSION"             : "{{APP_NAME} ខ្សែអក្សរដែលត្រូវគ្នា ({0}) មិនត្រឹមត្រូវ។",
    "DISALLOWED_WORDS"                     : "ពាក្យ ({1}) មិនត្រូវបានអនុញ្ញាតនៅក្នុងវាល {0} ទេ។",
    "NPM_INSTALL_FAILED"                   : "ពាក្យបញ្ជាបានបរាជ័យ npm install: {0}",
    "API_NOT_COMPATIBLE"                   : "កម្មវិធីបន្ថែមមិនត្រូវគ្នាជាមួយកំណែ {APP_NAME} នេះទេ។ វាត្រូវបានដំឡើងនៅក្នុងថតផ្នែកបន្ថែមរបស់អ្នក។",
    "MISSING_MAIN"                         : "កញ្ចប់មិនមាន main.js ឯកសារ។",
    "EXTENSION_ALREADY_INSTALLED"          : "ការដំឡើងកញ្ចប់នេះនឹងសរសេរជាន់លើផ្នែកបន្ថែមដែលបានតំឡើងពីមុន។ សរសេរជាន់លើផ្នែកបន្ថែមចាស់?",
    "EXTENSION_SAME_VERSION"               : "កញ្ចប់នេះគឺជាកំណែដូចគ្នានឹងកំណែដែលបានដំឡើងបច្ចុប្បន្នដែរ។ សរសេរជាន់លើការដំឡើងដែលមានស្រាប់?",
    "EXTENSION_OLDER_VERSION"              : "កញ្ចប់នេះគឺជាកំណែ {0} ដែលចាស់ជាងការដំឡើងបច្ចុប្បន្ន ({1}) ។ សរសេរជាន់លើការដំឡើងដែលមានស្រាប់?",
    "DOWNLOAD_ID_IN_USE"                   : "កំហុសខាងក្នុង: លេខកូដទាញយកកំពុងប្រើ។",
    "NO_SERVER_RESPONSE"                   : "មិនអាចភ្ជាប់ទៅម៉ាស៊ីនមេ។",
    "BAD_HTTP_STATUS"                      : "រកមិនឃើញឯកសារនៅលើម៉ាស៊ីនបម្រើ (HTTP {0}) ។",
    "CANNOT_WRITE_TEMP"                    : "មិនអាចរក្សាទុកការទាញយកទៅឯកសារ temp ។",
    "ERROR_LOADING"                        : "កម្មវិធីបន្ថែមបានជួបប្រទះកំហុសនៅពេលចាប់ផ្តើម។",
    "MALFORMED_URL"                        : "URL មិនត្រឹមត្រូវ។ សូមពិនិត្យមើលថាអ្នកបានបញ្ចូលវាត្រឹមត្រូវ។",
    "UNSUPPORTED_PROTOCOL"                 : "URL ត្រូវតែជា URL http ឬ https ។",
    "UNKNOWN_ERROR"                        : "មិនស្គាល់កំហុសខាងក្នុង។",
    // For NOT_FOUND_ERR, see generic strings above
    "EXTENSION_MANAGER_TITLE"              : "កម្មវិធីគ្រប់គ្រងផ្នែកបន្ថែម",
    "EXTENSION_MANAGER_ERROR_LOAD"         : "មិនអាចចូលប្រើបញ្ជីឈ្មោះផ្នែកបន្ថែម។ សូម​ព្យាយាម​ម្តង​ទៀត​នៅ​ពេល​ក្រោយ។",
    "INSTALL_EXTENSION_DRAG"               : "អូស .zip នៅទីនេះឬ",
    "INSTALL_EXTENSION_DROP"               : "ទម្លាក់ .zip ដើម្បីដំឡើង",
    "INSTALL_EXTENSION_DROP_ERROR"         : "ដំឡើង / បន្ទាន់សម័យបានបោះបង់ដោយសារកំហុសដូចខាងក្រោម:",
    "INSTALL_FROM_URL"                     : "ដំឡើងពី URL\u2026",
    "INSTALL_EXTENSION_VALIDATING"         : "ពិនត្យសុពលភាព\u2026",
    "EXTENSION_AUTHOR"                     : "អ្នកនិពន្ធ",
    "EXTENSION_DATE"                       : "កាលបរិច្ឆេទ",
    "EXTENSION_INCOMPATIBLE_NEWER"         : "ផ្នែកបន្ថែមនេះតម្រូវឱ្យមានកំណែថ្មីនៃ {APP_NAME} ។",
    "EXTENSION_INCOMPATIBLE_OLDER"         : "ផ្នែកបន្ថែមបច្ចុប្បន្ននេះដំណើរការតែជាមួយកំណែចាស់របស់ {APP_NAME} ប៉ុណ្ណោះ។",
    "EXTENSION_LATEST_INCOMPATIBLE_NEWER"  : "កំណែ {0} នៃផ្នែកបន្ថែមនេះតម្រូវឱ្យមានកំណែថ្មីនៃ {APP_NAME} ។ ប៉ុន្តែអ្នកអាចដំឡើងកំណែមុន {1} ។",
    "EXTENSION_LATEST_INCOMPATIBLE_OLDER"  : "កំណែ {0} នៃផ្នែកបន្ថែមនេះដំណើរការតែជាមួយកំណែចាស់របស់ {APP_NAME} ប៉ុណ្ណោះ។ ប៉ុន្តែអ្នកអាចដំឡើងកំណែមុន {1} ។",
    "EXTENSION_NO_DESCRIPTION"             : "គ្មានការពិពណ៌នា",
    "EXTENSION_MORE_INFO"                  : "ព័​ត៍​មាន​បន្ថែម\u2026",
    "EXTENSION_ERROR"                      : "កំហុសផ្នែកបន្ថែម",
    "EXTENSION_KEYWORDS"                   : "ពាក្យគន្លឹះ",
    "EXTENSION_TRANSLATED_USER_LANG"       : "បានបកប្រែជា {0} ភាសារួមទាំងរបស់អ្នក",
    "EXTENSION_TRANSLATED_GENERAL"         : "បានបកប្រែជា {0} ភាសា",
    "EXTENSION_TRANSLATED_LANGS"           : "ផ្នែកបន្ថែមនេះត្រូវបានបកប្រែទៅជាភាសាទាំងនេះ: {0}",
    "EXTENSION_INSTALLED"                  : "បានដំឡើង",
    "EXTENSION_UPDATE_INSTALLED"           : "ការធ្វើបច្ចុប្បន្នភាពផ្នែកបន្ថែមនេះត្រូវបានទាញយកហើយនឹងត្រូវបានដំឡើងបន្ទាប់ពី {APP_NAME} ផ្ទុកឡើងវិញ។",
    "EXTENSION_SEARCH_PLACEHOLDER"         : "ស្វែងរក",
    "EXTENSION_MORE_INFO_LINK"             : "ច្រើនទៀត",
    "BROWSE_EXTENSIONS"                    : "រុករកផ្នែកបន្ថែម",
    "EXTENSION_MANAGER_REMOVE"             : "យកផ្នែកបន្ថែមចេញ",
    "EXTENSION_MANAGER_REMOVE_ERROR"       : "មិនអាចដកផ្នែកបន្ថែមមួយឬច្រើន: {0} ។ {APP_NAME} នឹងនៅតែផ្ទុកឡើងវិញ។",
    "EXTENSION_MANAGER_UPDATE"             : "ធ្វើបច្ចុប្បន្នភាពផ្នែកបន្ថែម",
    "EXTENSION_MANAGER_UPDATE_ERROR"       : "មិនអាចធ្វើបច្ចុប្បន្នភាពផ្នែកបន្ថែមមួយឬច្រើន: {0} ។ {APP_NAME} នឹងនៅតែផ្ទុកឡើងវិញ។",
    "EXTENSION_MANAGER_DISABLE"            : "បិទដំណើរការផ្នែកបន្ថែម",
    "EXTENSION_MANAGER_DISABLE_ERROR"      : "មិនអាចបិទកន្ទុយមួយឬច្រើន: {0} ។ {APP_NAME} នឹងនៅតែផ្ទុកឡើងវិញ។",
    "MARKED_FOR_REMOVAL"                   : "បានសម្គាល់សម្រាប់ការដកចេញ",
    "UNDO_REMOVE"                          : "មិនធ្វើវិញ",
    "MARKED_FOR_UPDATE"                    : "បានសម្គាល់សម្រាប់ការធ្វើបច្ចុប្បន្នភាព",
    "UNDO_UPDATE"                          : "មិនធ្វើវិញ",
    "MARKED_FOR_DISABLING"                 : "បានសម្គាល់សម្រាប់បិទ",
    "UNDO_DISABLE"                         : "មិនធ្វើវិញ",
    "CHANGE_AND_RELOAD_TITLE"              : "ប្ដូរផ្នែកបន្ថែម",
    "CHANGE_AND_RELOAD_MESSAGE"            : "ដើម្បីធ្វើបច្ចុប្បន្នភាពដកចេញឬបិទដំណើរការផ្នែកបន្ថែមដែលបានសម្គាល់នោះ {APP_NAME} នឹងត្រូវដំណើរការឡើងវិញ។ អ្នកនឹងត្រូវបានសួរឱ្យរក្សាទុកការផ្លាស់ប្តូរដែលមិនបានរក្សាទុក។",
    "REMOVE_AND_RELOAD"                    : "យកផ្នែកបន្ថែមនិងផ្ទុកឡើងវិញ",
    "CHANGE_AND_RELOAD"                    : "ប្ដូរផ្នែកបន្ថែមនិងផ្ទុកឡើងវិញ",
    "UPDATE_AND_RELOAD"                    : "ធ្វើបច្ចុប្បន្នភាពផ្នែកបន្ថែមនិងផ្ទុកឡើងវិញ",
    "DISABLE_AND_RELOAD"                   : "បិទដំណើរការផ្នែកបន្ថែមនិងផ្ទុកឡើងវិញ",
    "PROCESSING_EXTENSIONS"                : "កំពុងដំណើរការផ្លាស់ប្តូរផ្នែកបន្ថែម\u2026",
    "EXTENSION_NOT_INSTALLED"              : "មិនអាចលុបផ្នែកបន្ថែម {0} ដោយសារតែវាមិនត្រូវបានដំឡើង។",
    "NO_EXTENSIONS"                        : "គ្មានផ្នែកបន្ថែមដែលបានតំឡើងនៅឡើយទេ។ ចុចលើផ្ទាំងដែលមាននៅខាងលើដើម្បីចាប់ផ្ដើម។",
    "NO_EXTENSION_MATCHES"                 : "គ្មានផ្នែកបន្ថែមត្រូវនឹងការស្វែងរករបស់អ្នក។",
    "REGISTRY_SANITY_CHECK_WARNING"        : "ចំណាំ: ផ្នែកបន្ថែមទាំងនេះអាចមកពីអ្នកនិពន្ធខុសគ្នាជាង {APP_NAME} ខ្លួនឯង។ ផ្នែកបន្ថែមមិនត្រូវបានពិនិត្យឡើងវិញទេហើយមានសិទ្ធិមូលដ្ឋានពេញលេញ។ ត្រូវប្រយ័ត្នពេលដំឡើងផ្នែកបន្ថែមពីប្រភពមិនស្គាល់។",
    "EXTENSIONS_INSTALLED_TITLE"           : "បានដំឡើង",
    "EXTENSIONS_DEFAULT_TITLE"             : "លំនាំដើម",
    "EXTENSIONS_AVAILABLE_TITLE"           : "មាន",
    "EXTENSIONS_THEMES_TITLE"              : "ស្បែក",
    "EXTENSIONS_UPDATES_TITLE"             : "ការធ្វើបច្ចុប្បន្នភាព",
    "EXTENSIONS_LAST_UPDATED"              : "ធ្វើ​ឱ្យ​ទាន់សម័យ​ចុងក្រោយ",
    "EXTENSIONS_DOWNLOADS"                 : "ការទាញយក",

    "INLINE_EDITOR_NO_MATCHES"             : "មិនមានការប្រកួត។",
    "INLINE_EDITOR_HIDDEN_MATCHES"         : "ការប្រកួតទាំងអស់ត្រូវបានបង្រួម។ ពង្រីកឯកសារដែលបានរាយនៅខាងស្ដាំដើម្បីមើលការប្រកួត។",
    "CSS_QUICK_EDIT_NO_MATCHES"            : "មិនមានក្បួន CSS ដែលមានស្រាប់ដែលត្រូវនឹងការជ្រើសរើសរបស់អ្នកទេ។<br> សូមចុច \"New Rule\" ដើម្បីបង្កើតមួយ។",
    "CSS_QUICK_EDIT_NO_STYLESHEETS"        : "មិនមានសន្លឹករចនាប័ទ្មក្នុងគម្រោងរបស់អ្នកទេ។<br>បង្កើតមួយដើម្បីបន្ថែមក្បួន CSS ។",

    // Custom Viewers
    "IMAGE_VIEWER_LARGEST_ICON"            : "ធំបំផុត",

    /**
     * Unit names
     */
    "UNIT_PIXELS"                          : "ភីកសែល",

    // extensions/default/DebugCommands
    "DEBUG_MENU"                                : "បំបាត់កំហុស",
    "ERRORS"                                    : "កំហុស",
    "CMD_SHOW_DEV_TOOLS"                        : "បង្ហាញឧបករណ៍អ្នកអភិវឌ្ឍន៍",
    "CMD_REFRESH_WINDOW"                        : "ផ្ទុកឡើងវិញដោយផ្នែកបន្ថែម",
    "CMD_RELOAD_WITHOUT_USER_EXTS"              : "ដំណើរការឡើងវិញដោយគ្មានផ្នែកបន្ថែម",
    "CMD_NEW_BRACKETS_WINDOW"                   : "{APP_NAME} បង្អួចថ្មី",
    "CMD_LAUNCH_SCRIPT_MAC"                     : "ដំឡើងផ្លូវកាត់បន្ទាត់ពាក្យបញ្ជា",
    "CMD_SWITCH_LANGUAGE"                       : "ប្តូរភាសា",
    "CMD_RUN_UNIT_TESTS"                        : "ដំណើរការការធ្វើតេស្ត",
    "CMD_SHOW_PERF_DATA"                        : "បង្ហាញទិន្នន័យប្រតិបត្តិការ",
    "CMD_ENABLE_NODE_DEBUGGER"                  : "បើកដំណើរការកម្មវិធីបំបាត់កំហុសថ្នាំង",
    "CMD_LOG_NODE_STATE"                        : "ចុះកំណត់ចំណាំនូវថ្នាំងទៅកុងសូល",
    "CMD_RESTART_NODE"                          : "Node ចាប់ផ្តើមឡើងវិញ",
    "CMD_SHOW_ERRORS_IN_STATUS_BAR"             : "បង្ហាញកំហុសក្នុងរបារស្ថានភាព",
    "CMD_OPEN_BRACKETS_SOURCE"                  : "បើក {APP_NAME} ប្រភព",

    "CREATING_LAUNCH_SCRIPT_TITLE"              : "{APP_NAME} ផ្លូវកាត់បន្ទាត់ពាក្យបញ្ជា",
    "ERROR_CREATING_LAUNCH_SCRIPT"              : "មានកំហុសមួយបានកើតឡើងពេលដំឡើងផ្លូវកាត់បន្ទាត់ពាក្យបញ្ជា។ សូម​ព្យាយាម <a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments#troubleshooting'>ការផ្តល់យោបល់ដោះស្រាយបញ្ហាទាំងនេះ</a>.<br/><br/>ហេតុផល: {0}",
    "ERROR_CLTOOLS_RMFAILED"                    : "មិនអាចយកចេញដែលមានស្រាប់ <code>/usr/local/bin/brackets</code> symlink.",
    "ERROR_CLTOOLS_MKDIRFAILED"                 : "មិនអាចបង្កើត <code>/usr/local/bin</code> directory.",
    "ERROR_CLTOOLS_LNFAILED"                    : "Unable to create <code>/usr/local/bin/brackets</code> symlink.",
    "ERROR_CLTOOLS_SERVFAILED"                  : "កំហុស​ខាងក្នុង។",
    "ERROR_CLTOOLS_NOTSUPPORTED"                : "ផ្លូវកាត់ពាក្យបញ្ជាមិនត្រូវបានគាំទ្រនៅលើ OS នេះទេ​។",
    "LAUNCH_SCRIPT_CREATE_SUCCESS"              : "ជោគជ័យ! ឥឡូវនេះអ្នកអាចបើកដំណើរការ {APP_NAME} យ៉ាងងាយស្រួលពីបន្ទាត់ពាក្យបញ្ជា: <code>brackets myFile.txt</code> ដើម្បីបើកឯកសារឬ <code>brackets myFolder</code> ដើម្បីផ្លាស់ប្តូរគម្រោង។ <br/><br/><a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments'>ស្វែង​យល់​បន្ថែម</a> អំពីការប្រើ {APP_NAME} ពីបន្ទាត់ពាក្យបញ្ជា។",

    "LANGUAGE_TITLE"                            : "ប្តូរភាសា",
    "LANGUAGE_MESSAGE"                          : "ភាសា:",
    "LANGUAGE_SUBMIT"                           : "ដំណើរការឡើងវិញ {APP_NAME}",
    "LANGUAGE_CANCEL"                           : "បោះបង់",
    "LANGUAGE_SYSTEM_DEFAULT"                   : "លំនាំដើមនៃប្រព័ន្ធ",

    // extensions/default/HealthData
    "HEALTH_DATA_NOTIFICATION"                  : "ចំណូលចិត្តរបាយការណ៍សុខាភិបាល",
    "HEALTH_FIRST_POPUP_TITLE"                  : "{APP_NAME} របាយការណ៍សុខាភិបាល",
    "HEALTH_DATA_DO_TRACK"                      : "ចែករំលែកព័ត៌មានអនាមិកពីរបៀបដែលខ្ញុំប្រើ {APP_NAME}",
    "HEALTH_DATA_NOTIFICATION_MESSAGE"          : "ដើម្បីធ្វើឱ្យ {APP_NAME} ប្រសើរឡើងយើងផ្ញើរមានកំណត់, <strong>អនាមិក</strong> ស្ថិតិទៅ Adobe អំពីរបៀបដែលអ្នកប្រើ {APP_NAME} ។ ព័ត៌មាននេះជួយកំណត់អាទិភាពលក្ខណៈពិសេសរកកំហុសនិងបញ្ហាដែលអាចប្រើប្រាស់បាន។<br><br>អ្នកអាចមើលទិន្នន័យរបស់អ្នកឬជ្រើសមិនចែករំលែកទិន្នន័យដោយជ្រើសរើស <strong> ជំនួយ> របាយការណ៍សុខភាព </ strong> ។ <br> <br> <a href = 'https: //github.com/adobe/brackets/wiki/ ទិន្នន័យសុខភាព '> ស្វែងយល់បន្ថែមអំពី {APP_NAME} របាយការណ៍សុខភាព </a>",
    "HEALTH_DATA_PREVIEW"                       : "{APP_NAME} របាយការណ៍សុខាភិបាល",
    "HEALTH_DATA_PREVIEW_INTRO"                 : "<p> ដើម្បីធ្វើឱ្យ {APP_NAME} ប្រសើរឡើងយើងផ្ញើរកំនត់កំនត់ពេលវេលា, <strong>អនាមិក</strong> ស្ថិតិទៅ Adobe អំពីរបៀបដែលអ្នកប្រើ {APP_NAME} ។ ព័ត៌មាននេះជួយកំណត់អាទិភាពលក្ខណៈពិសេសរកកំហុសនិងបញ្ហាដែលអាចប្រើប្រាស់បាន។ <a href='https://github.com/adobe/brackets/wiki/Health-Data'> ស្វែងយល់បន្ថែមអំពី {APP_NAME} របាយការណ៍សុខាភិបាល </a> និងរបៀបដែលវាមានប្រយោជន៍ដល់សហគមន៍ {APP_NAME} ខណៈដែលការពារភាពឯកជនរបស់អ្នក។ </ p> <p> ខាងក្រោមនេះជាការមើលជាមុននៃទិន្នន័យដែលនឹងត្រូវបានផ្ញើនៅក្នុងរបាយការណ៍សុខភាពបន្ទាប់ <em> ប្រសិនបើ </ em> របស់វាត្រូវបានបើក។</p>",

    // extensions/default/InlineTimingFunctionEditor
    "INLINE_TIMING_EDITOR_TIME"                 : "ពេលវេលា",
    "INLINE_TIMING_EDITOR_PROGRESSION"          : "ការវិវត្ត",
    "BEZIER_EDITOR_INFO"                        : "<kbd>↑</kbd><kbd>↓</kbd><kbd>←</kbd><kbd>→</kbd> ផ្លាស់ទីចំណុចដែលបានជ្រើស<br><kbd class='text'>Shift</kbd> ផ្លាស់ទីដោយដប់គ្រឿង<br><kbd class='text'>Tab</kbd> ប្ដូរចំណុច",
    "STEPS_EDITOR_INFO"                         : "<kbd>↑</kbd><kbd>↓</kbd> បង្កើនឬបន្ថយជំហាន<br><kbd>←</kbd><kbd>→</kbd> 'ចាប់ផ្ដើម' ឬ 'បញ្ចប់'",
    "INLINE_TIMING_EDITOR_INVALID"              : "តម្លៃចាស់ <code> {0} </ code> មិនត្រឹមត្រូវទេដូច្នេះមុខងារដែលបានបង្ហាញត្រូវបានប្តូរទៅជា <code> {1} </ code> ។ ឯកសារនឹងត្រូវបានធ្វើបច្ចុប្បន្នភាពជាមួយការកែប្រែទីមួយ។",

    // extensions/default/InlineColorEditor
    "COLOR_EDITOR_CURRENT_COLOR_SWATCH_TIP"     : "ពណ៌បច្ចុប្បន្ន",
    "COLOR_EDITOR_ORIGINAL_COLOR_SWATCH_TIP"    : "ពណ៌ដើម",
    "COLOR_EDITOR_RGBA_BUTTON_TIP"              : "ទ្រង់ទ្រាយ RGBa",
    "COLOR_EDITOR_HEX_BUTTON_TIP"               : "ទ្រង់ទ្រាយ Hex",
    "COLOR_EDITOR_HSLA_BUTTON_TIP"              : "ទ្រង់ទ្រាយ HSLa",
    "COLOR_EDITOR_0X_BUTTON_TIP"                : "ទ្រង់ទ្រាយ Hex (0x)",
    "COLOR_EDITOR_USED_COLOR_TIP_SINGULAR"      : "{0} (ប្រើ {1} ពេលវេលា)",
    "COLOR_EDITOR_USED_COLOR_TIP_PLURAL"        : "{0} (ប្រើ {1} ពេលវេលា)",

    // extensions/default/JavaScriptCodeHints
    "CMD_JUMPTO_DEFINITION"                     : "លោតទៅនិយមន័យ",
    "CMD_SHOW_PARAMETER_HINT"                   : "បង្ហាញប៉ារ៉ាម៉ែត្រប៉ារ៉ាម៉ែត្រ",
    "NO_ARGUMENTS"                              : "<no parameters>",
    "DETECTED_EXCLUSION_TITLE"                  : "បញ្ហាក្នុងការញែកឯកសារ JavaScript",
    "DETECTED_EXCLUSION_INFO"                   : "{APP_NAME} បានបរាជ័យក្នុងដំណើរការ <span class='dialog-filename'>{0}</span>.<br><br>ឯកសារនេះនឹងលែងត្រូវបានដំណើរការសម្រាប់ជំនួយកូដ, លោតទៅនិយមន័យឬកែសម្រួលរហ័ស។ ដើម្បីបើកដំណើរការឯកសារនេះឡើងវិញបើក <code> .brackets.json </ code> នៅក្នុងគម្រោងរបស់អ្នកហើយកែសម្រួល <code> jscodehints.detectedExclusions </ code> ។ <br> <br> នេះទំនងជាកំហុស {APP_NAME} ។ ប្រសិនបើអ្នកអាចផ្ដល់ច្បាប់ចម្លងនៃឯកសារនេះសូម <a href='https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue'> ដាក់កំហុស </a> ជាមួយ ភ្ជាប់ទៅឯកសារដែលមានឈ្មោះនៅទីនេះ។",

    // extensions/default/JavascriptRefactoring
    "CMD_REFACTOR"                              : "នាក់កត្តា",
    "CMD_EXTRACTTO_VARIABLE"                    : "ដកស្រង់ទៅអថេរ",
    "CMD_EXTRACTTO_FUNCTION"                    : "ស្រង់ទៅមុខងារ",
    "ERROR_TERN_FAILED"                         : "មិនអាចទទួលបានទិន្នន័យពី Tern",
    "ERROR_EXTRACTTO_VARIABLE_NOT_VALID"        : "ជម្រើសមិនបង្កើតកន្សោមទេ",
    "ERROR_EXTRACTTO_FUNCTION_NOT_VALID"        : "ប្លុកដែលបានជ្រើសគួរតំណាងឱ្យសំណុំសេចក្តីថ្លែងការណ៍ឬកន្សោមមួយ",
    "ERROR_EXTRACTTO_VARIABLE_MULTICURSORS"     : "ស្រង់ចេញអថេរមិនដំណើរការនៅពហុតួរ",
    "ERROR_EXTRACTTO_FUNCTION_MULTICURSORS"     : "ស្រង់ទៅអនុគមន៍មិនដំណើរការនៅក្នុងពហុគ្រូពេទ្យទេ",
    "EXTRACTTO_FUNCTION_SELECT_SCOPE"           : "ជ្រើសវិសាលភាពទិសដៅ",
    "EXTRACTTO_VARIABLE_SELECT_EXPRESSION"      : "ជ្រើសរើសកន្សោម",
    "CMD_REFACTORING_RENAME"                    : "ប្តូរឈ្មោះ",
    "CMD_REFACTORING_TRY_CATCH"                 : "រុំក្នុងការព្យាយាមចាប់",
    "CMD_REFACTORING_CONDITION"                 : "រុំក្នុងលក្ខខណ្ឌ",
    "CMD_REFACTORING_GETTERS_SETTERS"           : "បង្កើតហ្គីតា / អ្នកសំរេច",
    "CMD_REFACTORING_ARROW_FUNCTION"            : "បម្លែងទៅជាអនុគមន៍ព្រួញ",
    "DESCRIPTION_CODE_REFACTORING"              : "អនុញ្ញាត / មិនអនុញ្ញាត JavaScript Code Refactoring",
    "ERROR_TRY_CATCH"                           : "ជ្រើសរើសលេខកូដត្រឹមត្រូវដើម្បីរុំនៅក្នុងប្លុកព្យាយាមចាប់",
    "ERROR_WRAP_IN_CONDITION"                   : "ជ្រើសកូដត្រឹមត្រូវដើម្បីរុំនៅក្នុងប្លុកលក្ខខណ្ឌ",
    "ERROR_ARROW_FUNCTION"                      : "ដាក់ទស្សន៍ទ្រនិចក្នុងកន្សោមអនុគមន៍",
    "ERROR_GETTERS_SETTERS"                     : "ដាក់ទស្សន៍ទ្រនិចនៅសមាជិកនៃកន្សោមវត្ថុ",
    "ERROR_RENAME_MULTICURSOR"                  : "មិនអាចប្តូរឈ្មោះពេលប្រើទស្សន៍ទ្រនិចពហុ",
    "ERROR_RENAME_QUICKEDIT"                    : "មិនអាចប្តូរឈ្មោះអ្នកកំណត់អត្តសញ្ញាណនេះបានទេព្រោះវាត្រូវបានយោងនៅកន្លែងផ្សេងទៀតខាងក្រៅអនុគមន៍នេះ",
    "ERROR_RENAME_GENERAL"                      : "មិនអាចប្តូរឈ្មោះអត្ថបទដែលបានជ្រើស",

    // extensions/default/JSLint
    "JSLINT_NAME"                               : "JSLint",

    // extensions/default/QuickView
    "CMD_ENABLE_QUICK_VIEW"                     : "មើលរហ័សនៅលើសំកាំង",

    // extensions/default/RecentProjects
    "CMD_TOGGLE_RECENT_PROJECTS"                : "គម្រោងថ្មីៗ",

    // extensions/default/MDNDocs
    "DOCS_MORE_LINK"                            : "អាន​បន្ថែម",

    // extensions/default/CodeFolding
    "COLLAPSE_ALL"                  : "វេញទាំងអស់",
    "EXPAND_ALL"                    : "ពង្រីកទាំងអស់",
    "COLLAPSE_CURRENT"              : "វេញបច្ចុប្បន្ន",
    "EXPAND_CURRENT"                : "ពង្រីកបច្ចុប្បន្ន",

    // extensions/default/NavigationAndHistory
    "RECENT_FILES_DLG_HEADER"                    : "ឯកសារថ្មីៗ",
    "RECENT_FILES_DLG_CLEAR_BUTTON_LABEL"        : "ជម្រះ",
    "RECENT_FILES_DLG_CLEAR_BUTTON_TITLE"        : "ជម្រះឯកសារដែលមិននៅក្នុងសំណុំការងារ",

    // Descriptions of core preferences
    "DESCRIPTION_CLOSE_BRACKETS"                     : "ពិតដើម្បីបិទដង្កៀបតង្កៀបនិងវង់ក្រចកដោយស្វ័យប្រវត្តិ",
    "DESCRIPTION_CLOSE_OTHERS_ABOVE"                 : "មិនពិតដើម្បីយកចេញ \"Close Others Above\" ពីម៉ឺនុយបរិបទឯកសារការងារ",
    "DESCRIPTION_CLOSE_OTHERS_BELOW"                 : "មិនពិតដើម្បីយកចេញ \"Close Others Below\" ពីម៉ឺនុយបរិបទឯកសារការងារ",
    "DESCRIPTION_CLOSE_OTHERS"                       : "មិនពិតដើម្បីយកចេញ \"Close Others\" ពីម៉ឺនុយបរិបទឯកសារការងារ",
    "DESCRIPTION_CLOSE_TAGS"                         : "កំណត់ជម្រើសបិទស្លាក",
    "DESCRIPTION_CLOSE_TAGS_DONT_CLOSE_TAGS"         : "អារេនៃស្លាកដែលមិនគួរត្រូវបានបិទដោយស្វ័យប្រវត្តិ",
    "DESCRIPTION_CLOSE_TAGS_WHEN_OPENING"            : "បិទពេល> នៃការបើកស្លាកត្រូវបានវាយបញ្ចូល",
    "DESCRIPTION_CLOSE_TAGS_WHEN_CLOSING"            : "បិទពេល / នៃការបិទស្លាកត្រូវបានវាយបញ្ចូល",
    "DESCRIPTION_CLOSE_TAGS_INDENT_TAGS"             : "អារេនៃស្លាកដែលនៅពេលបានបើកមានបន្ទាត់ទទេមួយ",
    "DESCRIPTION_CODE_FOLDING_ALWAY_USE_INDENT_FOLD" : "ពិតប្រាកដដើម្បីបង្កើតបង្គោលផ្នែកដែលអាចដុះដាលនៅពេលដែលមានការផ្លាស់ប្តូរកម្រិតចូល",
    "DESCRIPTION_CODE_FOLDING_ENABLED"               : "ពិតដើម្បីបើកការបញ្ចូលកូដ",
    "DESCRIPTION_CODE_FOLDING_HIDE_UNTIL_MOUSEOVER"  : "ពិតប្រាកដដើម្បីបង្កើតសញ្ញាសម្គាល់ដួលរលំដែលអាចមើលឃើញតែនៅពេលដែលអ្នកផ្លាស់ទីកណ្តុរពីលើទឹកជ្រោះប៉ុណ្ណោះ",
    "DESCRIPTION_CODE_FOLDING_MAX_FOLD_LEVEL"        : "កំណត់ចំនួនស្នាមជ្រុះកម្រិតជ្រៅច្រើនត្រូវបានអនុវត្ត",
    "DESCRIPTION_CODE_FOLDING_MIN_FOLD_SIZE"         : "បន្ទាត់អប្បបរមាមុនពេលរូបតំណាងផ្នែកដែលអាចបត់ចូលបានលេចឡើង",
    "DESCRIPTION_CODE_FOLDING_SAVE_FOLD_STATES"      : "ពិតដើម្បីចងចាំផ្នែកដែលបានដួលរលំប្រសិនបើអ្នកបិទនិងបើកឯកសារឬគម្រោងម្តងទៀត",
    "DESCRIPTION_CODE_FOLDING_MAKE_SELECTIONS_FOLDABLE": "ពិតដើម្បីបើកកូដបញ្ចូលកូដនៅលើអត្ថបទដែលបានជ្រើសក្នុងកម្មវិធីនិពន្ធ",
    "DESCRIPTION_DISABLED_DEFAULT_EXTENSIONS"        : "ផ្នែកបន្ថែមលំនាំដើមដែលត្រូវបានបិទ",
    "DESCRIPTION_ATTR_HINTS"                         : "បើក / បិទគន្លឹះគុណលក្ខណៈ HTML",
    "DESCRIPTION_CSS_PROP_HINTS"                     : "បើកដំណើរការ / បិទដំណើរការជំនួយ CSS / LESS / SCSS",
    "DESCRIPTION_JS_HINTS"                           : "បើក / បិទជំនួយ JavaScript",
    "DESCRIPTION_JS_HINTS_TYPE_DETAILS"              : "បើកដំណើរការ / បិទព័ត៌មានលម្អិតប្រភេទទិន្នន័យនៅក្នុងគន្លឹះកូដ JavaScript",
    "DESCRIPTION_PREF_HINTS"                         : "បើក / មិនផ្តល់ជំនួយព័ត៌មានជំនួយកូដ",
    "DESCRIPTION_SPECIAL_CHAR_HINTS"                 : "បើក / បិទព័ត៌មានជំនួយធាតុរបស់ HTML",
    "DESCRIPTION_SVG_HINTS"                          : "បើក / បិទព័ត៌មានជំនួយកូដ SVG",
    "DESCRIPTION_HTML_TAG_HINTS"                     : "បើក / បិទព័ត៌មានជំនួយស្លាក HTML",
    "DESCRIPTION_URL_CODE_HINTS"                     : "បើក / បិទព័ត៌មានជំនួយ URL ក្នុង HTML & CSS / LESS / SCSS",
    "DESCRIPTION_DRAG_DROP_TEXT"                     : "បើកដំណើរការ / បិទមុខងារអូសនិងទម្លាក់",
    "DESCRIPTION_HEALTH_DATA_TRACKING"               : "បើកដំណើរការតាមដានទិន្នន័យសុខាភិបាល",
    "DESCRIPTION_HIGHLIGHT_MATCHES"                  : "បើកដំណើរការការបន្លិចខ្សែអក្សរដែលផ្គូផ្គងដោយស្វ័យប្រវត្តិនៅទូទាំងឯកសារ",
    "DESCRIPTION_HIGHLIGHT_MATCHES_SHOW_TOKEN"       : "បន្លិចខ្សែអក្សរទាំងអស់ដែលផ្គូផ្គងថូខឹនបច្ចុប្បន្នទស្សន៍ទ្រនិចបច្ចុប្បន្ន (គ្មានជម្រើសដែលត្រូវការ) បើកការបន្លិចខ្សែអក្សរផ្គូផ្គងពេញលេញនៅលើឯកសារ",
    "DESCRIPTION_HIGHLIGHT_MATCHES_WORDS_ONLY"       : "បន្លិចតែនៅពេលជ្រើសរើសជានិមិត្តសញ្ញាពេញលេញ",
    "DESCRIPTION_INSERT_HINT_ON_TAB"                 : "ពិតដើម្បីបញ្ចូលព័ត៌មានជំនួយដែលបានជ្រើសបច្ចុប្បន្ននៅលើផ្ទាំង",
    "DESCRIPTION_NO_HINTS_ON_DOT"                    : "ពិតដើម្បីបញ្ចូលព័ត៌មានជំនួយដែលបានជ្រើសបច្ចុប្បន្ននៅលើផ្ទាំង",
    "DESCRIPTION_JSLINT_OPTIONS"                     : "វត្ថុដែលមានជម្រើសលំនាំដើមសម្រាប់ JSLint",
    "DESCRIPTION_JSLINT_OPTIONS_ASS"                 : "ពិតដើម្បីអនុញ្ញាតកន្សោមដ្រាយ",
    "DESCRIPTION_JSLINT_OPTIONS_BITWISE"             : "ពិតដើម្បីអនុញ្ញាតឱ្យប្រតិបត្តិករប៊ីត",
    "DESCRIPTION_JSLINT_OPTIONS_BROWSER"             : "ពិតប្រសិនបើស្ដង់ដារ browser globals គួរត្រូវបានកំណត់ជាមុន",
    "DESCRIPTION_JSLINT_OPTIONS_CLOSURE"             : "ពិតប្រាកដដើម្បីអនុញ្ញាត Google Closure កំណាព្យ",
    "DESCRIPTION_JSLINT_OPTIONS_CONTINUE"            : "ពិត ដើម្បីអនុញ្ញាត \"បន្ត \" សេចក្តីថ្លែងការណ៍",
    "DESCRIPTION_JSLINT_OPTIONS_COUCH"               : "ពិតប្រសិនបើគរុកោសល្យ CouchDB គួរត្រូវបានកំណត់ជាមុន",
    "DESCRIPTION_JSLINT_OPTIONS_DEBUG"               : "ពិតដើម្បីអនុញ្ញាតសេចក្តីថ្លែងការណ៍បំបាត់កំហុស",
    "DESCRIPTION_JSLINT_OPTIONS_DEVEL"               : "ពិតប្រសិនបើកម្មវិធីរុករកសកលមានប្រយោជន៍នៅក្នុងការអភិវឌ្ឍគួរតែត្រូវបានកំណត់ជាមុន",
    "DESCRIPTION_JSLINT_OPTIONS_EQEQ"                : "ពិតប្រាកដដើម្បីអនុញ្ញាត == នឹង !=",
    "DESCRIPTION_JSLINT_OPTIONS_ES6"                 : "ពិតប្រសិនបើ ES6 globals គួរតែត្រូវបានកំណត់ជាមុន",
    "DESCRIPTION_JSLINT_OPTIONS_EVIL"                : "ពិតដើម្បីអនុញ្ញាត eval",
    "DESCRIPTION_JSLINT_OPTIONS_FORIN"               : "ពិតដើម្បីអនុញ្ញាតមិនបានត្រង \"for ... in\"",
    "DESCRIPTION_JSLINT_OPTIONS_INDENT"              : "កំណត់ទទឹងថេបជាក់លាក់",
    "DESCRIPTION_JSLINT_OPTIONS_MAXERR"              : "ចំនួនការព្រមានអតិបរមាដែលបានរាយការណ៍",
    "DESCRIPTION_JSLINT_OPTIONS_MAXLEN"              : "ចំនួនអតិបរមានៃតួអក្សរក្នុងបន្ទាត់",
    "DESCRIPTION_JSLINT_OPTIONS_NEWCAP"              : "ពិតប្រាកដដើម្បីអនុញ្ញាតឱ្យអ្នកសាងសង់មិនមានតំរូវការ",
    "DESCRIPTION_JSLINT_OPTIONS_NODE"                : "ពិតប្រសិនបើ Node.js globals គួរតែត្រូវបានកំណត់ជាមុន",
    "DESCRIPTION_JSLINT_OPTIONS_NOMEN"               : "ពិតប្រាកដដើម្បីអនុញ្ញាតឱ្យមានសញ្ញាគូសបន្ទាត់ចុះក្រោមនៅក្នុងអត្តសញ្ញាណ",
    "DESCRIPTION_JSLINT_OPTIONS_PASSFAIL"            : "ពិតដើម្បីបញ្ឈប់កំហុសលើកដំបូង",
    "DESCRIPTION_JSLINT_OPTIONS_PLUSPLUS"            : "ពិតប្រាកដដើម្បីអនុញ្ញាត ++ និង --",
    "DESCRIPTION_JSLINT_OPTIONS_REGEXP"              : "ពិតប្រាកដដើម្បីអនុញ្ញាត . និង [^...]. ក្នុង RegExp",
    "DESCRIPTION_JSLINT_OPTIONS_RHINO"               : "ពិតប្រសិនបើ Rhino globals គួរតែត្រូវបានកំណត់ជាមុន",
    "DESCRIPTION_JSLINT_OPTIONS_SLOPPY"              : "ពិតដើម្បីអនុញ្ញាតឱ្យបាត់ `use strict`",
    "DESCRIPTION_JSLINT_OPTIONS_STUPID"              : "ពិតប្រសិនបើបិទ ('...Sync') វិធីសាស្រ្តអាចត្រូវបានប្រើ។",
    "DESCRIPTION_JSLINT_OPTIONS_SUB"                 : "ពិតប្រាកដដើម្បីអនុញ្ញាតឱ្យមានអក្សរតូចក្រោម",
    "DESCRIPTION_JSLINT_OPTIONS_TODO"                : "ពិតដើម្បីអនុញ្ញាតឱ្យ TODO យោបល់",
    "DESCRIPTION_JSLINT_OPTIONS_UNPARAM"             : "ពិតដើម្បីអនុញ្ញាតប៉ារ៉ាម៉ែត្រដែលមិនប្រើ",
    "DESCRIPTION_JSLINT_OPTIONS_VARS"                : "ពិតប្រាកដដើម្បីអនុញ្ញាតឱ្យមានច្រើនជាង 1 vars នៅក្នុងអនុគមន៍មួយ",
    "DESCRIPTION_JSLINT_OPTIONS_WHITE"               : "ពិតដើម្បីមិនអើពើច្បាប់ចន្លោះពណ៌ស",
    "DESCRIPTION_LANGUAGE"                           : "ការកំណត់ជាក់លាក់នៃភាសា",
    "DESCRIPTION_LANGUAGE_FILE_EXTENSIONS"           : "ការផ្គូផ្គងបន្ថែមពីកន្ទុយឯកសារទៅជាឈ្មោះភាសា",
    "DESCRIPTION_LANGUAGE_FILE_NAMES"                : "ការផ្គូផ្គងបន្ថែមពីឈ្មោះឯកសារទៅជាឈ្មោះភាសា",
    "DESCRIPTION_LINEWISE_COPY_CUT"                  : "ការថតចម្លងនិងកាត់បន្ថយនៅពេលគ្មានការជ្រើសរើសនឹងចម្លងឬកាត់ខ្សែបន្ទាត់ដែលមានទស្សន៍ទ្រនិចនៅក្នុងវា",
    "DESCRIPTION_INPUT_STYLE"                        : "ជ្រើសវិធីដែល CodeMirror គ្រប់គ្រងការបញ្ចូលនិងផ្ដោតលើ។ វាអាចជា textarea ដែលជាលំនាំដើមឬមាតិកាដែលសមស្របដែលប្រសើរសម្រាប់អ្នកអានអេក្រង់ (មិនស្ថិតស្ថេរ)",
    "DESCRIPTION_LINTING_ENABLED"                    : "ពិតដើម្បីអនុញ្ញាតការត្រួតពិនិត្យកូដ",
    "DESCRIPTION_ASYNC_TIMEOUT"                      : "ពេលវេលាគិតជាមិល្លីវិនាទីដែលអន្ទាក់អ័ក្សអាកាសអស់ពេល",
    "DESCRIPTION_LINTING_PREFER"                     : "អារេស្រោមអនាម័យត្រូវដំណើរការជាមុនសិន",
    "DESCRIPTION_LIVE_DEV_MULTIBROWSER"              : "ពិតដើម្បីអនុញ្ញាតការមើលជាមុនសាកល្បង",
    "DESCRIPTION_USE_PREFERED_ONLY"                  : "ពិតប្រាកដដើម្បីដំណើរការអ្នកផ្តល់សេវាដែលបានបញ្ជាក់នៅក្នុង linting.prefer only",
    "DESCRIPTION_MAX_CODE_HINTS"                     : "សេចក្តីណែនាំកូដអតិបរមាដែលបង្ហាញក្នុងពេលតែមួយ",
    "DESCRIPTION_PATH"                               : "កំណត់ផ្លូវជាក់លាក់",
    "DESCRIPTION_PROXY"                              : "URL នៃម៉ាស៊ីនមេប្រូកស៊ីដែលបានប្រើសម្រាប់តំឡើងកម្មវិធីបន្ថែម",
    "DESCRIPTION_SCROLL_PAST_END"                    : "ពិតដើម្បីបើករមូរលើសពីចុងឯកសារ",
    "DESCRIPTION_SHOW_CODE_HINTS"                    : "មិនពិតដើម្បីបិទកូដជំនួយទាំងអស់",
    "DESCRIPTION_SHOW_CURSOR_WHEN_SELECTING"         : "រក្សាទស្សន៍ទ្រនិចលោតភ្លឹបភ្លែតៗពេលអ្នកមានជម្រើសអត្ថបទ",
    "DESCRIPTION_SHOW_LINE_NUMBERS"                  : "ពិតដើម្បីបង្ហាញលេខបន្ទាត់នៅក្នុង “gutter” ទៅខាងឆ្វេងនៃកូដ",
    "DESCRIPTION_SMART_INDENT"                       : "ចូលបន្ទាត់ដោយស្វ័យប្រវត្តិនៅពេលបង្កើតប្លុកថ្មី",
    "DESCRIPTION_SOFT_TABS"                          : "មិនពិតដើម្បីបិទអាកប្បកិរិយាផ្ទាំងទន់",
    "DESCRIPTION_SORT_DIRECTORIES_FIRST"             : "ពិតដើម្បីតម្រៀបថតមុនគេនៅក្នុងមែកធាងគម្រោង",
    "DESCRIPTION_SPACE_UNITS"                        : "ចំនួនដកឃ្លាដែលត្រូវប្រើសម្រាប់ការចូលបន្ទាត់ដែលមានមូលដ្ឋានលើ",
    "DESCRIPTION_STATIC_SERVER_PORT"                 : "លេខច្រកដែលម៉ាស៊ីនបម្រើដែលភ្ជាប់មកជាមួយគួរប្រើសម្រាប់មើលជាមុនមើលជាមុន",
    "DESCRIPTION_STYLE_ACTIVE_LINE"                  : "ពិត ដើម្បីបន្លិចពណ៌ផ្ទៃខាងក្រោយនៃបន្ទាត់ដែលទស្សន៍ទ្រនិចបើក",
    "DESCRIPTION_TAB_SIZE"                           : "ចំនួនចន្លោះដែលត្រូវបង្ហាញសម្រាប់ផ្ទាំង",
    "DESCRIPTION_USE_TAB_CHAR"                       : "ពិតដើម្បីប្រើផ្ទាំងជំនួសឱ្យចន្លោះ",
    "DESCRIPTION_UPPERCASE_COLORS"                   : "ពិតដើម្បីបង្កើតពណ៌គោលដប់បួននៅក្នុងកម្មវិធីនិពន្ធពណ៌ក្នុងតួ",
    "DESCRIPTION_WORD_WRAP"                          : "រុំបន្ទាត់ដែលលើសពីទទឹងការបង្ហាញ",
    "DESCRIPTION_SEARCH_AUTOHIDE"                    : "បិទការស្វែងរកភ្លាមៗនៅពេលអ្នកនិពន្ធផ្តោតអារម្មណ៍",
    "DESCRIPTION_DETECTED_EXCLUSIONS"                : "បញ្ជីឯកសារដែលត្រូវបានរកឃើញធ្វើឱ្យ Tern អស់ពីសមត្ថភាព",
    "DESCRIPTION_INFERENCE_TIMEOUT"                  : "ពេលវេលាដែល Tern នឹងអស់ពេលព្យាយាមយល់ឯកសារ",
    "DESCRIPTION_SHOW_ERRORS_IN_STATUS_BAR"          : "ពិតដើម្បីបង្ហាញកំហុសក្នុងរបារស្ថានភាព",
    "DESCRIPTION_QUICK_VIEW_ENABLED"                 : "ពិតដើម្បីបើកទិដ្ឋភាពរហ័ស",
    "DESCRIPTION_EXTENSION_LESS_IMAGE_PREVIEW"       : "ពិតដើម្បីបង្ហាញការមើលរូបភាពជាមុនសម្រាប់ URL ដែលបាត់ផ្នែកបន្ថែម",
    "DESCRIPTION_THEME"                              : "ជ្រើសរើសស្បែក {APP_NAME}",
    "DESCRIPTION_USE_THEME_SCROLLBARS"               : "ពិតដើម្បីអនុញ្ញាតរបាររមូរផ្ទាល់ខ្លួន",
    "DESCRIPTION_LINTING_COLLAPSED"                  : "ពិតប្រាកដដើម្បីបង្រួមបន្ទះ linting",
    "DESCRIPTION_FONT_FAMILY"                        : "ផ្លាស់ប្ដូរគ្រួសារពុម្ពអក្សរ",
    "DESCRIPTION_FONT_SIZE"                          : "ផ្លាស់ប្តូរទំហំពុម្ពអក្សរ; e.g. 13px",
    "DESCRIPTION_FIND_IN_FILES_NODE"                 : "ពិត ដើម្បីបើកការស្វែងរកដែលមានមូលដ្ឋានលើថ្នាំង",
    "DESCRIPTION_FIND_IN_FILES_INSTANT"              : "ពិតដើម្បីបើកការស្វែងរកបន្ទាន់",
    "DESCRIPTION_FONT_SMOOTHING"                     : "មានតែ Mac: \"subpixel-antialiased \" ដើម្បីបើកការប្រឆាំង anti-aliasing រងឬ \"antialiased \" សម្រាប់ការប្រឆាំង antialiasing ខ្នាតពណ៌ប្រផេះ។",
    "DESCRIPTION_OPEN_PREFS_IN_SPLIT_VIEW"           : "មិនពិតដើម្បីបិទបើកឯកសារចំណង់ចំណូលចិត្តក្នុងទិដ្ឋភាពបំបែក",
    "DESCRIPTION_OPEN_USER_PREFS_IN_SECOND_PANE"     : "មិនពិតដើម្បីបើកឯកសារចំណង់ចំណូលចិត្តអ្នកប្រើនៅក្នុងស្លាបព្រិលខាងឆ្វេង / កំពូល",
    "DESCRIPTION_MERGE_PANES_WHEN_LAST_FILE_CLOSED"  : "ពិតប្រាកដដើម្បីបង្រួមស្លាបព្រិលបន្ទាប់ពីឯកសារចុងក្រោយពីស្លាបព្រិលត្រូវបានបិទតាមរយៈប៊ូតុងបិទបឋមកថាស្លាបព្រិល",
    "DESCRIPTION_SHOW_PANE_HEADER_BUTTONS"           : "បិទ / បើកនៅពេលណាដើម្បីបង្ហាញប៊ូតុងបិទជិតនិងទិដ្ឋភាពត្រឡប់នៅលើបឋមកថា។",
    "DEFAULT_PREFERENCES_JSON_HEADER_COMMENT"        : "/ * \ n * នេះជាឯកសារដែលបានតែអានជាមួយចំណង់ចំណូលចិត្តដែលគាំទ្រ \ n * ដោយ {APP_NAME} ។ \ n * ប្រើឯកសារនេះជាសេចក្ដីយោងដើម្បីកែចំណូលចិត្តរបស់អ្នក \ n * file \"brackets.json \" ដែលបានបើកនៅក្នុង ផ្ទាំងផ្សេងទៀត។ \ n * សម្រាប់ព័ត៌មានបន្ថែមអំពីរបៀបប្រើចំណង់ចំណូលចិត្តនៅខាងក្នុង \ n * {APP_NAME} សូមមើលគេហទំព័រនៅ https://github.com/adobe/brackets/wiki/How-to-Use-Brackets # preferences \ n * /",
    "DEFAULT_PREFERENCES_JSON_DEFAULT"               : "លំនាំដើម",
    "DESCRIPTION_PURE_CODING_SURFACE"                : "ពិតដើម្បីបើករបៀបកូដតែប៉ុណ្ណោះហើយលាក់ធាតុ UI ផ្សេងទៀតទាំងអស់នៅក្នុង {APP_NAME}",
    "DESCRIPTION_INDENT_LINE_COMMENT"                : "ពិតដើម្បីអនុញ្ញាតការចូលបន្ទាត់នៃមតិយោបល់បន្ទាត់",
    "DESCRIPTION_RECENT_FILES_NAV"                   : "បើក / បិទការរុករកនៅក្នុងឯកសារថ្មីៗ",
    "DESCRIPTION_LIVEDEV_WEBSOCKET_PORT"             : "ច្រកនៅលើម៉ាស៊ីនបម្រើ WebSocket រត់សម្រាប់ការមើលជាមុនការផ្សាយបន្តផ្ទាល់",
    "DESCRIPTION_LIVE_DEV_HIGHLIGHT_SETTINGS"        : "មើលការផ្សាយបន្តផ្ទាល់ការបន្លិចការកំណត់",
    "DESCRIPTION_LIVEDEV_ENABLE_REVERSE_INSPECT"     : "មិនពិតដើម្បីបិទការមើលជាមុនបញ្ចាំងពិនិត្យឡើងវិញ",
    
    // Strings for Auto Update
    "DOWNLOAD_FAILED"                                : "ការទាញយកបានបរាជ័យ។",
    "DOWNLOAD_COMPLETE"                              : "ការទាញយកបានបញ្ចប់!",
    "UPDATE_SUCCESSFUL"                              : "ធ្វើបច្ចុប្បន្នភាពទទួលបានជោគជ័យ!",
    "UPDATE_FAILED"                                  : "ការធ្វើបច្ចុប្បន្នភាពបានបរាជ័យ!",
    "VALIDATION_FAILED"                              : "សុពលភាពបានបរាជ័យ!",
    "INITIALISATION_FAILED"                          : "ការចាប់ផ្ដើមបានបរាជ័យ!",
    "CLEANUP_FAILED"                                 : "សម្អាតបានបរាជ័យ!",
    "WARNING_TYPE"                                   : "ព្រមាន!",
    "CLICK_RESTART_TO_UPDATE"                        : "ចុចចាប់ផ្ដើមឡើងវិញដើម្បីធ្វើបច្ចុប្បន្នភាព Brackets.",
    "UPDATE_ON_NEXT_LAUNCH"                          : "ការធ្វើបច្ចុប្បន្នភាពនឹងត្រូវបានអនុវត្តនៅការបើកដំណើរការឡើងវិញ។",
    "GO_TO_SITE"                                     : "ទៅ <a href = \"http://brackets.io/\"> brackets.io </a> ព្យាយាមម្តងទៀត។",
    "INTERNET_UNAVAILABLE"                           : "មិនមានការតភ្ជាប់អ៊ីនធឺណិតទេ។",
    "UPDATEDIR_READ_FAILED"                          : "ធ្វើបច្ចុប្បន្នភាពថតមិនអាចអានបានទេ។",
    "UPDATEDIR_CLEAN_FAILED"                         : "ធ្វើបច្ចុប្បន្នភាពថតមិនអាចសម្អាត។",
    "INITIAL_DOWNLOAD"                               : "កំពុងទាញយកបច្ចុប្បន្នភាព...",
    "RETRY_DOWNLOAD"                                 : "ការទាញយកបានបរាជ័យ។ ព្យាយាមម្តងទៀត...ការប៉ុនប៉ង ",
    "VALIDATING_INSTALLER"                           : "ការទាញយកបានបញ្ចប់! សុពលភាពកម្មវិធីដំឡើង...",
    "CHECKSUM_DID_NOT_MATCH"                         : "Checksum មិនត្រូវគ្នា។",
    "INSTALLER_NOT_FOUND"                            : "កម្មវិធីរកមិនឃើញ។",
    "DOWNLOAD_ERROR"                                 : "កំហុសបានកើតឡើងខណៈពេលកំពុងទាញយក។",
    "NETWORK_SLOW_OR_DISCONNECTED"                   : "បណ្តាញត្រូវបានផ្តាច់ឬយឺតពេក។",
    "RESTART_BUTTON"                                 : "ចាប់ផ្តើមឡើងវិញ",
    "LATER_BUTTON"                                   : "ក្រោយមក",
    "DESCRIPTION_AUTO_UPDATE"                        : "បើក / បិទដំណើរការតង្កៀបធ្វើបច្ចុប្បន្នភាពដោយស្វ័យប្រវត្តិ",
    "AUTOUPDATE_ERROR"                               : "កំហុស!",
    "AUTOUPDATE_IN_PROGRESS"                         : "ការធ្វើបច្ចុប្បន្នភាពមានរួចហើយ។",
    
    "NUMBER_WITH_PERCENTAGE"                         : "{0}%",
    // Strings for Related Files
    "CMD_FIND_RELATED_FILES"                         : "រកឯកសារដែលទាក់ទង"
});
/* Last translated for afcbff03bb51b1e275dac2f9f0afbfa23ef79856 */
