/*jslint vars: true, plusplus: true, devel: true, nomen: true, indent: 4, maxerr: 50 */
/*global define */

define({
    "ATTRIBUTE_IN_CLOSING_TAG": "<p>关闭<code>&lt;/[[closeTag.name]]&gt;</code>标签<em data-highlight='[[closeTag.start]],[[closeTag.end]]'>这儿</em>不能包含任何属性。</p>",
    "CLOSE_TAG_FOR_VOID_ELEMENT": "<p>关闭<code>&lt;/[[closeTag.name]]&gt;</code>标签<em data-highlight='[[closeTag.start]],[[closeTag.end]]'>这里</em>是为无效元素(即元素是不需要被关闭的)。</p>",
    "CSS_MIXED_ACTIVECONTENT": "<p>CSS 属性 <em data-highlight='[[cssProperty.start]],[[cssProperty.end]]'>[[cssProperty.property]]</em> 有一个 url()属性值<em data-highlight='[[cssValue.start]],[[cssValue.end]]'>这儿</em>，目前指向了一个不安全的资源。 你可以让这个错误消失记录在Webmaker日志里。更多关于现代浏览器的不安全信号内容信息，访问 <a href='https://developer.mozilla.org/en-US/docs/Security/MixedContent'>这个链接</a>.</p>",
    "EVENT_HANDLER_ATTR_NOT_ALLOWED": "<p>对不起，出于安全目此网站阻止你在<em data-highlight='[[name.start]],[[name.end]]'>这里</em>使用JavaScript事件处理程序属性。 如果你真的需要使用JavaScript，可以考虑使用<a href='http://jsbin.com/'>jsbin</a>或<a href='http://jsfiddle.net/'>jsfiddle</a>。</p>",
    "HTML_CODE_IN_CSS_BLOCK": "<p>在CSS的内容开始处检测出HTML代码<em data-highlight='[[html.start]],[[html.end]]'>这里</em></p>",
    "HTTP_LINK_FROM_HTTPS_PAGE": "<p><code>&lt;[[openTag.name]]&gt;</code> 标签的 <code>[[attribute.name.value]]</code> 属性 (<em data-highlight='[[attribute.value.start]],[[attribute.value.end]]'>here</em>)目前指向了一个不安全的资源。 你可以让这个错误消失记录在Webmaker日志里。更多关于现代浏览器的不安全信号内容信息，访问 <a href='https://developer.mozilla.org/en-US/docs/Security/MixedContent'>这个链接</a>.</p>",
    "INVALID_ATTR_NAME": "<p><em data-highlight='[[start]],[[end]]'>这个</em>属性的名字不符合 HTML5 的命名惯例。</p>",
    "UNSUPPORTED_ATTR_NAMESPACE": "<p>属性<em data-highlight='[[start]],[[end]]'>这儿</em> 使用了一个在HTML5规范下不被允许的属性名称空间。</p>",
    "MULTIPLE_ATTR_NAMESPACES": "<p>属性<em data-highlight='[[start]],[[end]]'>这里</em>含有多个名称空间。 请检查文本并确保本属性只有一个含前缀的名称空间。</p>",
    "INVALID_CSS_DECLARATION": "<p><em data-highlight='[[cssDeclaration.start]],[[cssDeclaration.end]]'>此</em>CSS声明都不用关闭的。</p>",
    "INVALID_CSS_PROPERTY_NAME": "<p>CSS属性<em data-highlight='[[cssProperty.start]],[[cssProperty.end]]'>[[cssProperty.property]]</em>不存在。 你可能想要看下<a href='https://developer.mozilla.org/en/CSS/CSS_Reference'>CSS属性列表</a>。</p>",
    "INVALID_CSS_RULE": "<p><em data-highlight='[[cssRule.start]],[[cssRule.end]]'>此</em>CSS规则不是合法的CSS。</p>",
    "INVALID_TAG_NAME": "<p><code>&lt;</code>字符<em data-highlight='[[openTag.start]],[[openTag.end]]'>这里</em> 似乎是一个标签的开始标记，但紧随其后的也不是一个有效的标签名。</p> <p>如果你只是想要一个 <code>&lt;</code> 出现在你的Web页面，可尝试使用 <code>&amp;lt;</code> 替代.</p> <p>或者，查看 <a href='https://developer.mozilla.org/en/docs/Web/Guide/HTML/HTML5/HTML5_element_list'>HTML5标签列表</a>。.</p>",
    "JAVASCRIPT_URL_NOT_ALLOWED": "<p>对不起，但这个网站的安全限制阻止你<em data-highlight='[[openTag.start]],[[closeTag.end]]'>在这里</em>使用<code>&lt;script&gt;</code>标签。  如果你真的需要使用JavaScript，可以考虑使用<a href='http://jsbin.com/'>jsbin</a>或<a href='http://jsfiddle.net/'>jsfiddle</a>。</p>",
    "MISMATCHED_CLOSE_TAG": "<p> 关闭 <code>&lt;/[[closeTag.name]]&gt;</code> 标记 <em data-highlight='[[closeTag.start]],[[closeTag.end]]'> 这里 </em> 与开始 <code>&lt;[[openTag.name]]&gt;</code> 标记 <em data-highlight='[[openTag.start]],[[openTag.end]]'>这里</em>不匹配， 这可能是由于丢失了一个 <code>&lt;/[[openTag.name]]&gt;</code> 标记。",
    "MISSING_CSS_BLOCK_CLOSER": "<p><em data-highlight='[[cssValue.start]],[[cssValue.end]]'>[[cssValue.value]]</em>后缺少段关闭或下一个属性：值;对。</p>",
    "MISSING_CSS_BLOCK_OPENER": "<p>缺少<em data-highlight='[[cssSelector.start]],[[cssSelector.end]]'>[[cssSelector.selector]]</em>后的段开启。</p>",
    "MISSING_CSS_PROPERTY": "<p>缺失<em data-highlight='[[cssSelector.start]],[[cssSelector.end]]'>[[cssSelector.selector]]</em>的属性。</p>",
    "MISSING_CSS_SELECTOR": "<p><em data-highlight='[[cssBlock.start]],[[cssBlock.end]]'>这里</em>可能缺少新的CSS选择器或&lt;/style&gt;标签。</p>",
    "MISSING_CSS_VALUE": "<p>缺少 <em data-highlight='[[cssProperty.start]],[[cssProperty.end]]'>[[cssProperty.property]]</em> 的值。</p>",
    "SCRIPT_ELEMENT_NOT_ALLOWED": "<p>对不起，但这个网站的安全限制阻止你<em data-highlight='[[openTag.start]],[[closeTag.end]]'>在这里</em>使用<code>&lt;script&gt;</code>标签。  如果你真的需要使用JavaScript，可以考虑使用<a href='http://jsbin.com/'>jsbin</a>或<a href='http://jsfiddle.net/'>jsfiddle</a>。</p>",
    "SELF_CLOSING_NON_VOID_ELEMENT": "<p>这个 <code>&lt;[[name]]&gt;</code> 标签 <em data-highlight='[[start]],[[end]]'></em> 不能自闭合，因为 <code>&lt;[[name]]&gt;</code> 不是一个空元素；必须用一个单独的 <code>&lt;/[[name]]&gt;</code> 标签闭合。</p>",
    "UNCAUGHT_CSS_PARSE_ERROR": "<p>发生超出预期情况下的解析错误：<em data-highlight='[[error.start]],[[error.end]]'>[[error.msg]]</em></p>",
    "UNCLOSED_TAG": "<p><em data-highlight='[[openTag.start]],[[openTag.end]]'>此</em><code>&lt;[[openTag.name]]&gt;</code>标签不用关闭。</p>",
    "UNEXPECTED_CLOSE_TAG": "<p><em data-highlight='[[closeTag.start]],[[closeTag.end]]'>这里</em>的关闭标签<code>&lt;/[[closeTag.name]]&gt;</code>不用和其他一对，因为打开的标签需要被关闭。</p>",
    "UNFINISHED_CSS_PROPERTY": "<p>属性 <em data-highlight='[[cssProperty.start]],[[cssProperty.end]]'>[[cssProperty.property]]</em> 依然需要以下述内容结束：</p>",
    "UNFINISHED_CSS_SELECTOR": "<p><em data-highlight='[[cssSelector.start]],[[cssSelector.end]]'>[[cssSelector.selector]]</em>选择器仍然需要以{结尾</p>",
    "UNFINISHED_CSS_VALUE": "<p><em data-highlight='[[cssValue.start]],[[cssValue.end]]'>[[cssValue.value]]</em>值仍然需要以；结尾</p>",
    "UNKOWN_CSS_KEYWORD": "<p>CSS 关键字 @keyword <em data-highlight='[[cssKeyword.start]],[[cssKeyword.end]]'>[[cssKeyword.value]]</em> 未能匹配任何关键字 @keywords。</p>",
    "UNQUOTED_ATTR_VALUE": "<p>属性值 <em data-highlight='[[start]]'>这里</em>应该以双引号开头。</p>",
    "UNTERMINATED_ATTR_VALUE": "<p><em data-highlight='[[attribute.value.start]]'>这里</em>有个<code>&lt;[[openTag.name]]&gt;</code>标签<code>[[attribute.name.value]]</code>属性值没有用关闭双引号结尾。</p>",
    "UNTERMINATED_CLOSE_TAG": "<p>关闭<code>&lt;/[[closeTag.name]]&gt;</code>标签<em data-highlight='[[closeTag.start]],[[closeTag.end]]'>这里</em>不用以<code>&gt;</code>结尾。</p>",
    "UNTERMINATED_COMMENT": "<p><em data-highlight='[[start]]'>这里</em>的注释不用以<code>--&gt;</code>结尾。</p>",
    "UNTERMINATED_CSS_COMMENT": "<p>CSS注释<em data-highlight='[[start]]'>在这里</em>不是以<code>*/</code>结尾的。</p>",
    "UNTERMINATED_OPEN_TAG": "<p>开始 <code>&lt;[[openTag.name]]&gt;</code> 标签 <em data-highlight='[[openTag.start]],[[openTag.end]]'>这里</em> 不用以 <code>&gt;</code>结尾。</p>"
});
