// Generated by CoffeeScript 1.3.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(function(require, exports, module) {
    'use strict';

    var ColorEditor, InlineColorEditor, InlineWidget, inlineEditorTemplate;
    InlineWidget = brackets.getModule("editor/InlineWidget").InlineWidget;
    ColorEditor = require('ColorEditor');
    inlineEditorTemplate = require("text!InlineColorEditorTemplate.html");
    InlineColorEditor = (function(_super) {

      __extends(InlineColorEditor, _super);

      InlineColorEditor.prototype.parentClass = InlineWidget.prototype;

      function InlineColorEditor(initialColor) {
        this.initialColor = initialColor;
        this._colorUpdateHandler = __bind(this._colorUpdateHandler, this);

        InlineWidget.call(this);
      }

      InlineColorEditor.prototype.load = function(hostEditor) {
        this.hostEditor = hostEditor;
        this.parentClass.load.call(this, hostEditor);
        this.$wrapperDiv = $(inlineEditorTemplate);
        this.$htmlContent.append(this.$wrapperDiv);
        return this.colorEditor = new ColorEditor(this.$wrapperDiv, this.initialColor, this._colorUpdateHandler);
      };

      InlineColorEditor.prototype.close = function() {
        console.log('closing');
        return this.hostEditor.removeInlineWidget(this);
      };

      InlineColorEditor.prototype.onAdded = function() {
        return window.setTimeout(this._sizeEditorToContent.bind(this));
      };

      InlineColorEditor.prototype._sizeEditorToContent = function() {
        return this.hostEditor.setInlineWidgetHeight(this, this.$wrapperDiv.outerHeight(), true);
      };

      InlineColorEditor.prototype._colorUpdateHandler = function(colorLabel) {
        return this.hostEditor._codeMirror.replaceSelection(colorLabel);
      };

      return InlineColorEditor;

    })(InlineWidget);
    return module.exports = InlineColorEditor;
  });

}).call(this);
