// Generated by CoffeeScript 1.3.3
(function() {
  var link;

  link = document.createElement('link');

  link.type = "text/css";

  link.rel = "stylesheet";

  link.href = 'extensions/default/InlineColorEditor/css/main.css';

  document.getElementsByTagName("head")[0].appendChild(link);

  define(function(require, exports, module) {
    "use strict";

    var EditorManager, InlineColorEditor, ProjectManager, hexRegEx, hslRegEx, inlineColorEditorProvider, rgbRegEx;
    EditorManager = brackets.getModule("editor/EditorManager");
    ProjectManager = brackets.getModule("project/ProjectManager");
    InlineColorEditor = require("InlineColorEditor");
    hexRegEx = /#([a-f0-9]{6}|[a-f0-9]{3})/i;
    hslRegEx = /hsla?\((\d|,|%| |.)*\)/i;
    rgbRegEx = /rgba?\((\d|,|%| |.)*\)/i;
    inlineColorEditorProvider = function(hostEditor, pos) {
      var colorRegEx, cursorLine, cursorPos, end, inlineColorEditor, match, result, sel, start;
      sel = hostEditor.getSelection(false);
      if (sel.start.line !== sel.end.line) {
        return null;
      }
      colorRegEx = /#[a-f0-9]{6}|#[a-f0-9]{3}|rgb\( ?\b([0-9]{1,2}|1[0-9]{2}|2[0-4][0-9]|25[0-5])\b ?, ?\b([0-9]{1,2}|1[0-9]{2}|2[0-4][0-9]|25[0-5])\b ?, ?\b([0-9]{1,2}|1[0-9]{2}|2[0-4][0-9]|25[0-5])\b ?\)|rgba\( ?\b([0-9]{1,2}|1[0-9]{2}|2[0-4][0-9]|25[0-5])\b ?, ?\b([0-9]{1,2}|1[0-9]{2}|2[0-4][0-9]|25[0-5])\b ?, ?\b([0-9]{1,2}|1[0-9]{2}|2[0-4][0-9]|25[0-5])\b ?, ?\b(1|0|0\.[0-9]{1,3}) ?\)|hsl\( ?\b([0-9]{1,2}|[12][0-9]{2}|3[0-5][0-9]|360)\b ?, ?\b([0-9]{1,2}|100)\b% ?, ?\b([0-9]{1,2}|100)\b% ?\)|hsla\( ?\b([0-9]{1,2}|[12][0-9]{2}|3[0-5][0-9]|360)\b ?, ?\b([0-9]{1,2}|100)\b% ?, ?\b([0-9]{1,2}|100)\b% ?, ?\b(1|0|0\.[0-9]{1,3}) ?\)/i;
      cursorPos = hostEditor._codeMirror.getCursor();
      cursorLine = hostEditor._codeMirror.getLine(hostEditor.getSelection(false).start.line);
      match = cursorLine.match(colorRegEx);
      if (!match) {
        return null;
      } else {
        start = match.index;
        end = start + match[0].length;
        if (cursorPos.ch < start || cursorPos.ch > end) {
          return null;
        }
      }
      hostEditor._codeMirror.setSelection({
        line: cursorPos.line,
        ch: start
      }, {
        line: cursorPos.line,
        ch: end
      });
      result = new $.Deferred();
      inlineColorEditor = new InlineColorEditor(match[0]);
      inlineColorEditor.load(hostEditor);
      result.resolve(inlineColorEditor);
      return result.promise();
    };
    return EditorManager.registerInlineEditProvider(inlineColorEditorProvider);
  });

}).call(this);
