// Generated by CoffeeScript 1.3.3
(function() {

  require.config({
    paths: {
      "jquery": "//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min",
      "trello": "https://api.trello.com/1/client.js?key=1953abc13ad18fd16a66a2a1d938a07a&dummy="
    },
    shim: {
      "trello": {
        "deps": ["jquery"]
      },
      "jquery.timeago": {
        "deps": ["jquery"]
      }
    }
  });

  require(['jquery', 'mustache', 'trello', 'text!views/issue.html', 'text!views/feature.html', 'jquery.timeago'], function($, Mustache, Trello, issueTemplate, featureTemplate) {
    $.ajax({
      url: 'https://api.github.com/repos/adobe/brackets/issues?labels=starter+bug',
      dataType: 'jsonp',
      success: function(data) {
        var issue, issuesHTML, _i, _len;
        data = data.data;
        issuesHTML = '';
        for (_i = 0, _len = data.length; _i < _len; _i++) {
          issue = data[_i];
          issue.date = jQuery.timeago(new Date(issue.created_at));
          issuesHTML += Mustache.render(issueTemplate, issue);
        }
        $('#starter-issues > .content').html(issuesHTML);
        return $('#starter-issues').show();
      }
    });
    return $.ajax({
      url: 'https://api.trello.com/1/boards/4f90a6d98f77505d7940ce88/cards?key=1953abc13ad18fd16a66a2a1d938a07a&filter=open&fields=badges,name,url,labels',
      dataType: 'jsonp',
      success: function(data) {
        var card, cards, featuresHTML, _i, _len;
        cards = data.filter(function(card) {
          var keep, label, _i, _len, _ref;
          keep = false;
          _ref = card.labels;
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            label = _ref[_i];
            if (label.name === 'Starter Feature') {
              keep = true;
              break;
            }
          }
          return keep;
        });
        featuresHTML = '';
        for (_i = 0, _len = cards.length; _i < _len; _i++) {
          card = cards[_i];
          featuresHTML += Mustache.render(featureTemplate, card);
        }
        $('#starter-features > .content').html(featuresHTML);
        return $('#starter-features').show();
      }
    });
  });

}).call(this);
